import { useHudStore } from '@/lib/store/useHudStore';
import { useMemo, useEffect, useState } from 'react';

export function ExportMask() {
  const settings = useHudStore(s => s.exportSettings);
  const isDark = useHudStore(s => s.theme === 'dark');
  const [containerSize, setContainerSize] = useState({ w: 0, h: 0 });

  useEffect(() => {
    const updateSize = () => setContainerSize({ w: window.innerWidth, h: window.innerHeight });
    window.addEventListener('resize', updateSize);
    updateSize();
    return () => window.removeEventListener('resize', updateSize);
  }, []);

  const maskStyle = useMemo(() => {
    if (settings.paperSize === 'screen' || containerSize.w === 0) return { display: 'none' };
    
    // A4 ratio: 1 : 1.414
    let targetRatio = settings.orientation === 'landscape' ? 1.414 : 1 / 1.414;
    
    // Calculate the maximum box fitting inside the container
    const containerRatio = containerSize.w / containerSize.h;
    let boxW = 0; let boxH = 0;
    if (containerRatio > targetRatio) {
      boxH = containerSize.h;
      boxW = boxH * targetRatio;
    } else {
      boxW = containerSize.w;
      boxH = boxW / targetRatio;
    }
    
    const padX = (containerSize.w - boxW) / 2;
    const padY = (containerSize.h - boxH) / 2;

    return {
      borderWidth: `${Math.max(0, padY)}px ${Math.max(0, padX)}px`,
      borderColor: 'rgba(0,0,0,0.6)',
      borderStyle: 'solid',
      pointerEvents: 'none' as const,
      position: 'absolute' as const,
      inset: 0,
      zIndex: 20
    };
  }, [settings.paperSize, settings.orientation, containerSize]);

  if (!settings.isExportMode) return null;

  return (
    <div style={maskStyle}>
       {/* Preview Header */}
       {(settings.title || settings.subtitle) && (
         <div className="absolute top-0 left-0 w-full p-8 pointer-events-none" style={{ background: `linear-gradient(to bottom, ${isDark ? 'rgba(0,10,20,0.8)' : 'rgba(255,255,255,0.9)'}, transparent)` }}>
            {settings.title && <h1 className={`text-3xl font-bold ${isDark ? 'text-[#00f2ff]' : 'text-slate-800'}`}>{settings.title}</h1>}
            {settings.subtitle && <h2 className={`text-xl mt-2 ${isDark ? 'text-slate-300' : 'text-slate-600'}`}>{settings.subtitle}</h2>}
         </div>
       )}
       {/* Preview Watermark */}
       {settings.showWatermark && (
         <div className="absolute bottom-4 right-4 pointer-events-none opacity-50 text-sm font-mono font-bold" style={{ color: isDark ? '#fff' : '#000' }}>
           Generated by WebGIS AI Agent
         </div>
       )}
    </div>
  );
}
