import React from 'react';
import { render } from '@testing-library/react';
import { describe, it, expect, beforeEach, vi, Mock, beforeAll, afterAll } from 'vitest';
import '@testing-library/jest-dom';
import { ExportMask } from '@/components/map/export-mask';
import { useHudStore } from '@/lib/store/useHudStore';

// Mock the store
vi.mock('@/lib/store/useHudStore', () => ({
  useHudStore: vi.fn(),
}));

describe('ExportMask', () => {
  beforeAll(() => {
    global.ResizeObserver = class ResizeObserver {
      observe() {}
      unobserve() {}
      disconnect() {}
    };
  });

  afterAll(() => {
    delete (global as any).ResizeObserver;
  });

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders nothing when not in export mode', () => {
    (useHudStore as unknown as Mock).mockImplementation((selector) => {
      const state = {
        exportSettings: {
          isExportMode: false,
          paperSize: 'A4',
          orientation: 'landscape',
          title: '',
          subtitle: '',
          showWatermark: false,
        },
        theme: 'light',
      };
      return selector(state);
    });

    const { container } = render(<ExportMask />);
    expect(container.firstChild).toBeNull();
  });

  it('renders the mask and preview header when in export mode', () => {
    (useHudStore as unknown as Mock).mockImplementation((selector) => {
      const state = {
        exportSettings: {
          isExportMode: true,
          paperSize: 'A4',
          orientation: 'landscape',
          title: 'Test Title',
          subtitle: 'Test Subtitle',
          showWatermark: true,
        },
        theme: 'light',
      };
      return selector(state);
    });

    const { getByText } = render(<ExportMask />);
    expect(getByText('Test Title')).toBeInTheDocument();
    expect(getByText('Test Subtitle')).toBeInTheDocument();
    expect(getByText('Generated by WebGIS AI Agent')).toBeInTheDocument();
  });

  it('keeps text and watermark visible when paperSize is screen', () => {
    (useHudStore as unknown as Mock).mockImplementation((selector) => {
      const state = {
        exportSettings: {
          isExportMode: true,
          paperSize: 'screen',
          orientation: 'landscape',
          title: 'Screen Title',
          subtitle: 'Screen Subtitle',
          showWatermark: true,
        },
        theme: 'light',
      };
      return selector(state);
    });

    const { getByText, container } = render(<ExportMask />);
    expect(getByText('Screen Title')).toBeInTheDocument();
    expect(getByText('Screen Subtitle')).toBeInTheDocument();
    expect(getByText('Generated by WebGIS AI Agent')).toBeInTheDocument();
    
    // Check if the wrapper div does not have display: none
    const div = container.firstChild as HTMLElement;
    expect(div).not.toHaveStyle({ display: 'none' });
    expect(div).toHaveStyle({ borderWidth: '0px' });
  });
});
