from typing import Any, Optional, Protocol


class SessionDataProtocol(Protocol):
    async def get(self, session_id: str, ref_id_or_alias: str) -> Optional[Any]: ...
    async def store(self, session_id: str, data: Any, prefix: str = "data") -> str: ...
    async def set_alias(self, session_id: str, ref_id: str, alias: str) -> None: ...
    async def list_refs(self, session_id: str) -> dict[str, str]: ...
    async def resolve_alias(self, session_id: str, ref_or_alias: str) -> str: ...
    async def get_map_state(self, session_id: str) -> dict[str, Any]: ...
    async def set_map_state(self, session_id: str, key: str, value: Any) -> None: ...
    async def update_layer_in_state(self, session_id: str, layer_id: str, updates: dict) -> None: ...
    async def remove_layer_from_state(self, session_id: str, layer_id: str) -> None: ...
    async def get_event_log(self, session_id: str) -> list[dict]: ...
    async def append_event(self, session_id: str, event: str, data: dict) -> None: ...
    async def get_started_at(self, session_id: str) -> Optional[str]: ...
    async def get_session_metadata(self, session_id: str) -> dict[str, Any]: ...
    async def clear_session(self, session_id: str) -> None: ...
