import React from 'react';
import { render } from '@testing-library/react';
import { describe, it, expect, beforeEach, vi, Mock } from 'vitest';
import '@testing-library/jest-dom';
import { ExportMask } from '@/components/map/export-mask';
import { useHudStore } from '@/lib/store/useHudStore';

// Mock the store
vi.mock('@/lib/store/useHudStore', () => ({
  useHudStore: vi.fn(),
}));

describe('ExportMask', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders nothing when not in export mode', () => {
    (useHudStore as unknown as Mock).mockImplementation((selector) => {
      const state = {
        exportSettings: {
          isExportMode: false,
          paperSize: 'a4',
          orientation: 'landscape',
          title: '',
          subtitle: '',
          showWatermark: false,
        },
        theme: 'light',
      };
      return selector(state);
    });

    const { container } = render(<ExportMask />);
    expect(container.firstChild).toBeNull();
  });

  it('renders the mask and preview header when in export mode', () => {
    (useHudStore as unknown as Mock).mockImplementation((selector) => {
      const state = {
        exportSettings: {
          isExportMode: true,
          paperSize: 'a4',
          orientation: 'landscape',
          title: 'Test Title',
          subtitle: 'Test Subtitle',
          showWatermark: true,
        },
        theme: 'light',
      };
      return selector(state);
    });

    const { getByText } = render(<ExportMask />);
    expect(getByText('Test Title')).toBeInTheDocument();
    expect(getByText('Test Subtitle')).toBeInTheDocument();
    expect(getByText('Generated by WebGIS AI Agent')).toBeInTheDocument();
  });
});
