"""PDF Cartography Rendering Engine (app/lib/cartography/pdf_renderer.py).

Pure domain module for rendering Canvas map images into standard A4 landscape thematic PDF maps.
Encapsulates Matplotlib layout geometry, thread-safe CJK font resolution, and PDF metadata embedding.
"""
import io
import logging
import time
from typing import Optional

logger = logging.getLogger(__name__)

# CJK font fallback keywords
_CJK_KEYWORDS = (
    "cjk", "noto", "source han", "wqy", "simhei",
    "simsun", "microsoft yahei", "pingfang", "heiti"
)


def _resolve_cjk_font_properties():
    """Find a CJK font and return a Matplotlib FontProperties object for thread-safe isolation."""
    import matplotlib.font_manager as fm
    for f in fm.fontManager.ttflist:
        if any(kw in f.name.lower() for kw in _CJK_KEYWORDS):
            return fm.FontProperties(family=f.name)
    logger.warning(
        "[pdf_renderer] CJK font not found in system. Chinese titles may render as tofu boxes. "
        "Recommend installing Noto CJK, Source Han Sans, or Microsoft YaHei."
    )
    return None


def generate_map_pdf(
    img_bytes: bytes,
    title: Optional[str] = None,
    subtitle: Optional[str] = None,
    author: Optional[str] = "WebGIS AI Agent",
    scale_text: Optional[str] = None,
    dpi: int = 150,
) -> bytes:
    """Render raw map image bytes into a compiled A4 landscape PDF bytes.

    Args:
        img_bytes: Raw image bytes (PNG, JPEG) of the map canvas
        title: Main map title (defaults to "专题地图")
        subtitle: Optional map subtitle
        author: Cartographer / author string
        scale_text: Scale text description (e.g. "1:10,000")
        dpi: Output PDF DPI resolution (default: 150)

    Returns:
        Compiled PDF file bytes

    Raises:
        ValueError: If img_bytes cannot be parsed as a valid image
    """
    if not img_bytes:
        raise ValueError("img_bytes cannot be empty")

    try:
        from PIL import Image
        import numpy as np
        img = Image.open(io.BytesIO(img_bytes)).convert("RGB")
        img_arr = np.array(img)
    except Exception as e:
        raise ValueError(f"Invalid or unparseable image bytes for map rendering: {e}") from e

    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    cjk_font_prop = _resolve_cjk_font_properties()

    # ── A4 Landscape (297×210 mm ≈ 11.69×8.27 in) ──
    fig = plt.figure(figsize=(11.69, 8.27), facecolor="white")

    try:
        map_top = 0.88
        map_bottom = 0.10
        ax_map = fig.add_axes([0.04, map_bottom, 0.92, map_top - map_bottom])
        ax_map.imshow(img_arr, aspect="auto")
        ax_map.axis("off")

        # Map Frame Border
        for spine in ax_map.spines.values():
            spine.set_visible(True)
            spine.set_linewidth(0.8)
            spine.set_edgecolor("#cccccc")

        # ── Title & Subtitle ──
        map_title = title or "专题地图"
        title_kwargs = {"fontsize": 15, "fontweight": "bold", "color": "#1e293b"}
        if cjk_font_prop:
            title_kwargs["fontproperties"] = cjk_font_prop

        fig.text(0.5, 0.955, map_title, ha="center", va="top", **title_kwargs)

        if subtitle:
            sub_kwargs = {"fontsize": 10, "color": "#64748b"}
            if cjk_font_prop:
                sub_kwargs["fontproperties"] = cjk_font_prop
            fig.text(0.5, 0.925, subtitle, ha="center", va="top", **sub_kwargs)

        # ── Footer ──
        date_str = time.strftime("%Y-%m-%d")
        footer_parts = [f"制图日期: {date_str}"]
        if author:
            footer_parts.append(f"制图者: {author}")
        if scale_text:
            footer_parts.append(f"比例尺: {scale_text}")
        footer_parts.append("Generated by WebGIS AI Agent")

        footer_kwargs = {"fontsize": 7, "color": "#94a3b8", "style": "italic"}
        if cjk_font_prop:
            footer_kwargs["fontproperties"] = cjk_font_prop

        fig.text(0.5, 0.025, "  |  ".join(footer_parts), ha="center", va="bottom", **footer_kwargs)

        # ── In-Memory PDF Compilation ──
        pdf_buf = io.BytesIO()
        import warnings
        with warnings.catch_warnings():
            warnings.filterwarnings("ignore", message="Glyph .* missing from font", category=UserWarning)
            fig.savefig(
                pdf_buf,
                format="pdf",
                dpi=dpi,
                bbox_inches="tight",
                metadata={
                    "Title": map_title,
                    "Author": author or "WebGIS AI Agent",
                    "Subject": subtitle or "",
                    "Creator": "WebGIS AI Agent",
                },
            )
        return pdf_buf.getvalue()

    finally:
        plt.close(fig)
