"""MapSpec schema → TypeScript projection (V6, ADR-0120 W3).

authoritative schema（mapspec_schema.py 的 Pydantic 模型族）是唯一契约真相；
本模块把它**确定性投影**为 ``frontend/lib/mapspec-compiler/types.generated.ts``。
手维护平行 schema 自此消除：types.ts 只 re-export generated 并保留
compile-runtime（非契约）类型。

投影策略（R1-M8 冻结）：
- generated 覆盖 schema-backed 核心文档类型（文档骨架/源/图层/布局/帧）。
- 开放面（MapLibre paint/layout 任意键、inlineData、filter 表达式、
  legend_spec）按显式策略表投影为索引签名/any/unknown —— 与手写时代的
  编译兼容面逐名等价，`export *` 后既有 import 不变。
- 生成文件带 DO-NOT-EDIT 头；再生成幂等（byte 级，契约测试锁定）。

运行：``python -m app.lib.cartography.ts_projection``
"""
from __future__ import annotations

from pathlib import Path
from typing import Annotated, Any, Union, get_args, get_origin

from pydantic import BaseModel

from app.lib.cartography.mapspec_schema import (
    SCHEMA_EXPORT_MODELS,
)

REPO_ROOT = Path(__file__).resolve().parents[3]
OUTPUT = REPO_ROOT / "frontend" / "lib" / "mapspec-compiler" / "types.generated.ts"

HEADER = """\
/**
 * AUTO-GENERATED by app/lib/cartography/ts_projection.py —— DO NOT EDIT.
 *
 * MapSpec 契约的权威 schema 在 app/lib/cartography/mapspec_schema.py
 * （Pydantic 模型族）；本文件是其 TypeScript 投影。修改契约请改 schema
 * 后运行 `python -m app.lib.cartography.ts_projection` 再生成。
 *
 * V6（ADR-0120 W3）：消除手维护平行 schema（原 types.ts 手写镜像）。
 */
"""

# ── 投影策略表（开放面的显式、可审查决策点）──────────────────────────────

#: 字段级 TS 覆盖：model → field → TS 片段（无法从 Pydantic 注释干净推出的
#: 开放面在此声明；注释说明理由）。
FIELD_TS_OVERRIDES: dict[str, dict[str, str]] = {
    "MapView": {"center": "[number, number]"},
    "RasterMapSpecSource": {
        "bounds": "[number, number, number, number]",
        "imageSize": "[number, number]",
    },
    "MapSpecFrame": {"extent": "[number, number, number, number]"},
    "GeoJSONMapSpecSource": {
        # 开放 GeoJSON 载荷（FeatureCollection 任意形状）
        "inlineData": "any",
    },
    "MapSpecLayer": {
        # MapLibre paint/layout 开放面 → 策略表复合体（索引签名放行任意键）
        "paint": "MapSpecLayerPaint",
        "layout": "MapSpecLayerLayout",
        # MapLibre filter 表达式（开放词表）
        "filter": "unknown[]",
        # 工具层专题图例标记（开放 dict；语义推导唯一权威 =
        # deriveLegendModel / render_scene.derive_legend_items）
        "legend_spec": "Record<string, unknown>",
    },
    "MapSpecLayerLabel": {
        # paint 同源开放面：数值或 StyleMethod
        "size": "number | StyleMethod",
        "color": "string | StyleMethod",
    },
}

#: 必填字段策略：模型中 Optional（容忍半成品文档）但生产写入方恒产出的
#: 字段，投影为必填 —— 与手写时代的 TS 逐字段等价（编译兼容面）。
REQUIRED_FIELDS: dict[str, tuple[str, ...]] = {
    "MapSpec": ("sources", "layers"),
}

#: 索引签名面：model → 追加索引签名（MapLibre paint/layout 开放键）。
INDEX_SIGNATURES: dict[str, str] = {
    "MapSpecLayerPaint": "[key: string]: StyleMethod | undefined;",
    "MapSpecLayerLayout": "[key: string]: any;",
}

#: 手写时代的 paint 已知键面（开放词表的已知部分；任意键经索引签名合法）。
PAINT_KNOWN_KEYS: tuple[tuple[str, str], ...] = (
    ("color", "StyleMethod"),
    ("radius", "StyleMethod"),
    ("width", "StyleMethod"),
    ("opacity", "StyleMethod"),
    ("strokeColor", "StyleMethod"),
    ("strokeWidth", "StyleMethod"),
)

LAYOUT_KNOWN_KEYS: tuple[tuple[str, str], ...] = (
    ("visibility", '"visible" | "none"'),
    ("labelField", "string"),
    ("labelSize", "number | StyleMethod"),
    ("labelColor", "string | StyleMethod"),
)

#: 完全由生成器权威声明的开放联合（paint 值契约；孪生编译器消费口径）。
STYLE_METHOD_BLOCK = """\
export type StyleMethodType = "constant" | "interpolate" | "step" | "match" | "field";

export interface ConstantStyleMethod {
  method: "constant";
  value: string | number | boolean;
}

export interface InterpolateStyleMethod {
  method: "interpolate";
  field: string;
  stops: Array<[number, string | number]>;
}

export interface StepStyleMethod {
  method: "step";
  field: string;
  stops: Array<[number, string | number]>;
  default?: string | number;
}

export interface MatchStyleMethod {
  method: "match";
  field: string;
  cases: Array<[string | number, string | number]>;
  default: string | number;
}

export interface FieldStyleMethod {
  method: "field";
  field: string;
}

export type StyleMethod =
  | ConstantStyleMethod
  | InterpolateStyleMethod
  | StepStyleMethod
  | MatchStyleMethod
  | FieldStyleMethod
  | string
  | number
  | boolean;
"""

#: 生成器内的模型别名 → 投影名（TS 侧沿用手写时代的名字，import 不变）。
MODEL_TS_NAMES: dict[str, str] = {
    "MapSpecDocument": "MapSpec",
    "MapView": "MapSpecView",
    "MapThresholds": "MapThresholds",
}

#: 手写 paint/layout 复合体（非 Pydantic 模型，策略表驱动）。
HAND_BLOCK_MODELS: dict[str, str] = {
    "MapSpecLayerPaint": None,  # None → 由 _emit_paint_layout 生成
    "MapSpecLayerLayout": None,
}

# ── Pydantic 注释 → TS ───────────────────────────────────────────────────


def _literal_values(annotation: Any) -> tuple[str, ...] | None:
    origin = get_origin(annotation)
    if origin is not None and origin.__name__ == "Literal":
        vals = get_args(annotation)
        if all(isinstance(v, str) for v in vals):
            return tuple(f'"{v}"' for v in vals)
    args = get_args(annotation)
    if args and all(isinstance(a, str) for a in args) and origin is not None and hasattr(origin, "__name__") and origin.__name__ == "Literal":
        return tuple(f'"{a}"' for a in args)
    return None


def _ts_of(annotation: Any, owner: str, field: str, optional_mark: bool) -> str:
    """单字段类型投影（optional_mark=是否带 `?`，由调用方拼）。"""
    override = FIELD_TS_OVERRIDES.get(owner, {}).get(field)
    if override:
        return override

    # pydantic strict 标量是 Annotated 载体（StrictStr = Annotated[str, Strict()]）
    if get_origin(annotation) is Annotated:
        return _ts_of(get_args(annotation)[0], owner, field, optional_mark)

    lit = _literal_values(annotation)
    if lit:
        return " | ".join(lit)

    origin = get_origin(annotation)
    args = get_args(annotation)

    if origin is Union:
        non_none = [a for a in args if a is not type(None)]
        if len(non_none) == 1:
            return _ts_of(non_none[0], owner, field, optional_mark)
        parts = sorted({_ts_of(a, owner, field, False) for a in non_none})
        return " | ".join(parts)

    if origin is not None and origin.__name__ in ("list", "List"):
        inner = _ts_of(args[0], owner, field, False) if args else "unknown"
        if inner.startswith("["):
            return inner  # 元组 override 已含完整形状
        return f"{inner}[]"
    if origin is not None and origin.__name__ == "dict":
        if args and len(args) == 2:
            return f"Record<string, {_ts_of(args[1], owner, field, False)}>"
        return "Record<string, unknown>"

    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return MODEL_TS_NAMES.get(annotation.__name__, annotation.__name__)

    if annotation is Any:
        return "unknown"
    if annotation is str:
        return "string"
    if annotation is bool:
        return "boolean"
    if annotation in (int, float):
        return "number"

    # pydantic strict 标量（StrictStr/StrictInt/StrictFloat/StrictBool）
    name = getattr(annotation, "__name__", "") or str(annotation)
    if "StrictStr" in name or name == "StrictStr":
        return "string"
    if "StrictBool" in name or name == "StrictBool":
        return "boolean"
    if "StrictInt" in name or "StrictFloat" in name or "Number" in name:
        return "number"
    return "unknown"


def _fields_of(model: type) -> list[tuple[str, Any, bool, bool]]:
    """(field, annotation, optional, has_default)。"""
    out = []
    for name, f in model.model_fields.items():
        optional = f.is_required() is False
        out.append((name, f.annotation, optional, not f.is_required()))
    return out


def _emit_interface(model_name: str, model: type, lines: list[str]) -> None:
    ts_name = MODEL_TS_NAMES.get(model_name, model_name)
    required = REQUIRED_FIELDS.get(model_name, ())
    lines.append(f"export interface {ts_name} {{")
    for fname, annotation, optional, _has_default in _fields_of(model):
        is_req = fname in required
        mark = "" if is_req else "?" if optional else "?"
        # 模型里必填（无默认）的字段投影为必填
        if not optional and not is_req:
            mark = ""
        inner = _ts_of(annotation, model_name, fname, not mark)
        doc = ""
        lines.append(f"{doc}  {fname}{mark}: {inner};")
    if model_name in INDEX_SIGNATURES:
        lines.append(f"  {INDEX_SIGNATURES[model_name]}")
    lines.append("}")
    lines.append("")


def _emit_paint_layout(lines: list[str]) -> None:
    lines.append("export interface MapSpecLayerPaint {")
    for key, ts in PAINT_KNOWN_KEYS:
        lines.append(f"  {key}?: {ts};")
    lines.append(f"  {INDEX_SIGNATURES['MapSpecLayerPaint']}")
    lines.append("}")
    lines.append("")
    lines.append("export interface MapSpecLayerLayout {")
    for key, ts in LAYOUT_KNOWN_KEYS:
        lines.append(f"  {key}?: {ts};")
    lines.append(f"  {INDEX_SIGNATURES['MapSpecLayerLayout']}")
    lines.append("}")
    lines.append("")


def _emit_union_alias(ts_name: str, members: tuple[str, ...], lines: list[str]) -> None:
    lines.append(f"export type {ts_name} =")
    for i, m in enumerate(members):
        prefix = "    | " if i == 0 else "  | "
        terminator = ";" if i == len(members) - 1 else ""
        lines.append(f"{prefix}{m}{terminator}")
    lines.append("")


def emit_typescript() -> str:
    """确定性投影（同输入恒同输出 —— 幂等由契约测试锁定）。"""
    lines: list[str] = [HEADER, STYLE_METHOD_BLOCK]

    # MapSpecLayerPaint/Layout（策略表驱动）先行 —— Layer 引用它们
    _emit_paint_layout(lines)

    skip = {"MapSpecLayerPaint", "MapSpecLayerLayout"}
    for model_name, model in SCHEMA_EXPORT_MODELS:
        if model_name == "MapSpecSource":
            members = tuple(
                MODEL_TS_NAMES.get(m.__name__, m.__name__)
                for (_, m) in SCHEMA_EXPORT_MODELS
                if isinstance(m, type) and issubclass(m, BaseModel) and m.__name__.endswith("MapSpecSource") and m.__name__ != "MapSpecSource"
            )
            _emit_union_alias("MapSpecSource", members, lines)
            continue
        if model_name in skip or model is None:
            continue
        assert isinstance(model, type) and issubclass(model, BaseModel), model_name
        _emit_interface(model_name, model, lines)

    return "\n".join(lines).rstrip() + "\n"


def write_projection() -> Path:
    content = emit_typescript()
    OUTPUT.write_text(content, encoding="utf-8")
    return OUTPUT


if __name__ == "__main__":
    path = write_projection()
    print(f"wrote {path}")
