"""领域包：Accessibility（服务覆盖 / 可达性）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_BASE,
    MAP_COMPONENTS_CHART,
    boundary_role,
    denominator_role,
    fb,
    obl,
    role,
    standard_completion,
    subject_role,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_FACILITY_ROLE = subject_role()
_DEMAND_ROLE = role(
    "population", acquisition="data_fabric",
    artifacts=("polygon_feature_set", "grid_aggregate", "admin_aggregate_table"),
    geometry=("polygon", "table"), required=False,
    note="需求侧人口/用户分布（覆盖 ratio 时为分母）",
)

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="service_area_isochrone",
        name="服务区/等时圈",
        description="设施服务区（步行/车程 N 分钟等时圈）：路网口径与时间阈值披露。",
        intent_tasks=["accessibility_analysis", "proximity_analysis"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "service_area", "point_profile"],
        optional_analysis=["admin_boundary_query"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=[RecipeFallback(when="network unavailable", reason_code="NETWORK_DISCONNECTED",
                                  use="euclidean_buffer")],
        export_profile={"formats": ["png"]},
        priority=43,
        schema_version=2,
        workflow=wf(
            "accessibility", "service_area",
            zh=["服务区", "等时圈", "15分钟生活圈", "步行范围"],
            en=["service area", "isochrone"],
            roles=[_FACILITY_ROLE],
            obligations=[
                obl("isochrone_mode_disclosure", "disclosure",
                    code="ISOCHRONE_MODE_DISCLOSURE",
                    desc="等时圈的时间阈值与出行方式必须显式披露。"),
            ],
            completion=standard_completion(),
            fallbacks=[fb("NETWORK_DISCONNECTED", frm="network_isochrone", to="euclidean_buffer",
                          downgrade="proxy",
                          disclosure="路网不可用：以欧氏缓冲圈近似服务范围（代理）。")],
        ),
    ),
    CartographyRecipe(
        id="walking_accessibility_gap",
        name="步行可达盲区",
        description="设施步行覆盖盲区识别（覆盖/未覆盖分区 + 缺口 disclosure）：网络口径义务。",
        intent_tasks=["accessibility_analysis"],
        intent_cartography=["proximity_overlay", "administrative_choropleth"],
        preferred_analysis=["poi_query", "service_area", "admin_boundary_query", "spatial_join",
                            "admin_aggregation"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "accessibility", "coverage_gap",
            zh=["盲区", "覆盖缺口", "未覆盖", "服务空白"],
            en=["coverage gap", "underserved area", "blind zone"],
            roles=[_FACILITY_ROLE, boundary_role()],
            obligations=[
                obl("gap_network_semantics", "disclosure",
                    code="GAP_NETWORK_SEMANTICS",
                    desc="盲区判定必须披露覆盖判据（方式/时间阈值/路网口径）。"),
            ],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="facility_coverage_ratio",
        name="设施覆盖率评价",
        description="行政区设施覆盖率（覆盖人口/总人口）：分母义务，缺人口不得称覆盖率。",
        intent_tasks=["accessibility_analysis", "spatial_equity", "administrative_statistic"],
        intent_cartography=["administrative_choropleth"],
        preferred_analysis=["poi_query", "service_area", "admin_boundary_query", "admin_aggregation",
                            "rate_aggregation"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="admin units unavailable", reason_code="NEEDS_ADMIN_UNITS",
                                  use="point_overlay")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "accessibility", "coverage_ratio",
            zh=["覆盖率", "覆盖人口", "覆盖评价"],
            en=["coverage ratio", "covered population"],
            roles=[_FACILITY_ROLE, boundary_role(), denominator_role()],
            obligations=[
                obl("coverage_ratio_denominator", "denominator",
                    code="COVERAGE_RATIO_MISSING_DENOMINATOR",
                    desc="覆盖率需要人口分母；缺失时只能报覆盖面积/设施数。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(),
            fallbacks=[fb("DATA_ROLE_MISSING_DENOMINATOR", frm="coverage_ratio_map", to="coverage_area_map",
                          downgrade="degraded",
                          disclosure="缺少人口分母：仅呈现覆盖面积/范围，不称人口覆盖率。")],
        ),
    ),
    CartographyRecipe(
        id="emergency_response_coverage",
        name="应急响应覆盖",
        description="消防/医疗应急响应时间覆盖（响应圈 + 盲区）：阈值口径强披露。",
        intent_tasks=["accessibility_analysis", "risk_exposure"],
        intent_cartography=["proximity_overlay", "administrative_choropleth"],
        preferred_analysis=["poi_query", "service_area", "closest_facility", "admin_boundary_query",
                            "admin_aggregation"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png"]},
        priority=45,
        schema_version=2,
        workflow=wf(
            "accessibility", "emergency_coverage",
            zh=["消防覆盖", "急救圈", "应急响应", "5分钟救援"],
            en=["emergency response coverage", "fire coverage"],
            roles=[_FACILITY_ROLE, boundary_role()],
            obligations=[
                obl("response_time_semantics", "disclosure",
                    code="RESPONSE_TIME_SEMANTICS",
                    desc="响应时间覆盖为路网行车近似，不含出警准备时间，需披露口径。"),
            ],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="transit_stop_accessibility",
        name="轨道站点步行可达",
        description="轨道站点 N 分钟步行可达范围与覆盖居住区：接驳口径披露。",
        intent_tasks=["accessibility_analysis"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "service_area", "point_profile", "admin_boundary_query"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=[],
        export_profile={"formats": ["png"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "accessibility", "transit_walk_access",
            zh=["地铁站步行", "轨道接驳", "站点覆盖"],
            en=["metro walk access"],
            roles=[_FACILITY_ROLE, _DEMAND_ROLE],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="location_allocation_planning",
        name="选址-分配优化",
        description="设施区位-分配（location-allocation）规划：容量/需求角色与模型口径披露。",
        intent_tasks=["site_selection", "accessibility_analysis"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "location_allocation", "closest_facility", "point_profile"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"]},
        priority=47,
        schema_version=2,
        workflow=wf(
            "accessibility", "location_allocation",
            zh=["选址分配", "设施布局优化", "服务点优化"],
            en=["location allocation"],
            roles=[_FACILITY_ROLE, _DEMAND_ROLE, boundary_role()],
            obligations=[
                obl("la_model_semantics", "disclosure",
                    code="LA_MODEL_SEMANTICS",
                    desc="选址-分配的目标函数（最小化距离/最大化覆盖）必须披露。"),
            ],
            completion=standard_completion(uncertainty=True),
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
