"""领域包：Change Detection（变化检测 / 变更台账）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CHART,
    MAP_COMPONENTS_CONTINUOUS,
    boundary_role,
    fb,
    obl,
    role,
    standard_completion,
    subject_role,
    wf,
    auto_fallback,
)
from app.services.gis_harness.recipes import CartographyRecipe

_DUAL_DATE = [
    role("baseline", capability="raster_source", artifacts=("raster_surface",),
         geometry=("raster",), policy="degrade",
         disclosure="缺少基期数据：无法做两期对比。"),
    role("target_time", capability="raster_source", artifacts=("raster_surface",),
         geometry=("raster",), policy="degrade",
         disclosure="缺少目标期数据：无法做两期对比。"),
]
_DUAL_OBLIGATION = obl(
    "change_dual_date_required", "temporal",
    code="CHANGE_DUAL_DATE_REQUIRED",
    desc="变化检测需要基期+目标期两期数据；任一缺失阻断变化结论。",
    action="degrade_with_disclosure",
)
_DUAL_FALLBACK = fb(
    "CHANGE_DUAL_DATE_REQUIRED", frm="change_map", to="single_date_view",
    downgrade="degraded",
    disclosure="两期数据不全：仅呈现单期，不做变化结论。",
)

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="bitemporal_raster_change",
        name="两期栅格变化检测",
        description="两期栅格差值/分类后对比变化：配准义务 + 变化阈值披露。",
        intent_tasks=["change_detection"],
        intent_cartography=["raster_surface"],
        preferred_analysis=["raster_source", "raster_change_detection", "zonal_statistics"],
        primary_cartography="raster_surface",
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=[],
        fallback_links=auto_fallback(),  # ADR-0151 P7：通用兜底链（auto_generated）
        export_profile={"formats": ["png"]},
        priority=43,
        schema_version=2,
        workflow=wf(
            "change_detection", "bitemporal_change",
            zh=["两期对比", "变化检测", "前后对比"],
            en=["change detection", "two date comparison"],
            roles=_DUAL_DATE,
            obligations=[
                _DUAL_OBLIGATION,
                obl("change_registration", "transformation",
                    code="CHANGE_REGISTRATION_REQUIRED",
                    desc="两期栅格需配准一致；未配准的变化图斑不可信。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[_DUAL_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="landcover_change_inventory",
        name="地类变化台账",
        description="两期地类转移台账（转移矩阵 + 变化图斑）：分类口径一致性义务。",
        intent_tasks=["change_detection", "administrative_statistic"],
        intent_cartography=["administrative_choropleth", "raster_surface"],
        preferred_analysis=["raster_source", "raster_change_detection", "zonal_statistics",
                            "admin_boundary_query", "admin_aggregation"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["raster_surface"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        fallback_links=auto_fallback(),  # ADR-0151 P7：通用兜底链（auto_generated）
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "change_detection", "landcover_change_accounting",
            zh=["地类变化", "转移矩阵", "土地利用变化", "占地变化"],
            en=["land cover change", "change accounting"],
            roles=[*_DUAL_DATE, boundary_role()],
            obligations=[
                _DUAL_OBLIGATION,
                obl("change_class_scheme_consistent", "disclosure",
                    code="CHANGE_CLASS_SCHEME_CONSISTENCY",
                    desc="两期分类口径（类体系/分辨率）必须一致，否则台账不可比。"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[_DUAL_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="urban_expansion_monitor",
        name="城市扩张监测",
        description="建成区/城镇扩张监测（两期建成区范围对比 + 行政区扩张统计）。",
        intent_tasks=["change_detection", "administrative_statistic"],
        intent_cartography=["raster_surface", "administrative_choropleth"],
        preferred_analysis=["raster_source", "raster_change_detection", "band_math",
                            "zonal_statistics", "admin_boundary_query", "admin_aggregation"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["raster_surface"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        fallback_links=auto_fallback(),  # ADR-0151 P7：通用兜底链（auto_generated）
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "change_detection", "urban_expansion",
            zh=["城市扩张", "建成区扩张", "城镇扩展", "扩张监测"],
            en=["urban expansion", "urban growth"],
            roles=[*_DUAL_DATE, boundary_role()],
            obligations=[_DUAL_OBLIGATION],
            completion=standard_completion(uncertainty=True),
            fallbacks=[_DUAL_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="ndvi_change_trend",
        name="植被变化趋势",
        description="植被指数多期变化趋势（退化/恢复方向判断）：趋势期数义务。",
        intent_tasks=["change_detection", "temporal_trend", "vegetation_index"],
        intent_cartography=["raster_surface", "administrative_choropleth"],
        preferred_analysis=["raster_source", "ndvi", "spectral_index", "temporal_trend",
                            "raster_change_detection", "zonal_statistics"],
        primary_cartography="raster_surface",
        secondary_cartography=["administrative_aggregation"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=[],
        fallback_links=auto_fallback(),  # ADR-0151 P7：通用兜底链（auto_generated）
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=45,
        schema_version=2,
        workflow=wf(
            "change_detection", "vegetation_trend",
            zh=["植被退化", "绿化变化", "植被恢复", "生态变化"],
            en=["vegetation degradation", "ndvi change"],
            roles=[*_DUAL_DATE],
            obligations=[
                obl("veg_trend_min_observations", "precondition",
                    precondition="min_temporal_observations:4",
                    code="VEG_TREND_INSUFFICIENT_OBSERVATIONS",
                    desc="多期趋势需要 ≥4 期；两期仅是差值。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("VEG_TREND_INSUFFICIENT_OBSERVATIONS", frm="veg_trend", to="bitemporal_difference",
                          downgrade="degraded",
                          disclosure="期数不足：仅做两期差值，不称退化/恢复趋势。")],
        ),
    ),
    CartographyRecipe(
        id="change_area_accounting",
        name="变化面积台账",
        description="变化图斑面积台账（新增/减少面积 + 行政区归集）：面积口径披露。",
        intent_tasks=["change_detection", "administrative_statistic"],
        intent_cartography=["administrative_choropleth", "raster_surface"],
        preferred_analysis=["raster_source", "raster_change_detection", "zonal_statistics",
                            "admin_boundary_query", "admin_aggregation", "rate_aggregation"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["raster_surface"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        fallback_links=auto_fallback(),  # ADR-0151 P7：通用兜底链（auto_generated）
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=45,
        schema_version=2,
        workflow=wf(
            "change_detection", "area_accounting",
            zh=["变化面积", "新增面积", "减少面积", "面积台账"],
            en=["change area accounting"],
            roles=[*_DUAL_DATE, boundary_role()],
            obligations=[_DUAL_OBLIGATION],
            completion=standard_completion(),
            fallbacks=[_DUAL_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="poi_temporal_comparison",
        name="POI 两期对比",
        description="POI/设施两期数量对比（新增/消失点位）：数据源时点一致性义务。",
        intent_tasks=["change_detection", "administrative_statistic"],
        intent_cartography=["point_overlay", "administrative_choropleth"],
        preferred_analysis=["poi_query", "temporal_profile", "admin_boundary_query", "admin_aggregation",
                            "spatial_join"],
        primary_cartography="point_overlay",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        fallback_links=auto_fallback(),  # ADR-0151 P7：通用兜底链（auto_generated）
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "change_detection", "poi_comparison",
            zh=["新增了", "比去年", "两期点位", "点位变化"],
            en=["new venues compared to"],
            roles=[subject_role(),
                   role("comparison_time", capability="poi_query", artifacts=("poi_feature_set",),
                        geometry=("point",), policy="degrade",
                        disclosure="缺少对比期 POI 快照：无法做新增/消失对比。")],
            obligations=[
                obl("poi_snapshot_time_consistent", "disclosure",
                    code="POI_SNAPSHOT_TIME_CONSISTENCY",
                    desc="两期 POI 需为同一数据源同时点口径；混源对比必须披露。"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("DATA_ROLE_MISSING_COMPARISON_TIME", frm="poi_change_map", to="current_view",
                          downgrade="degraded",
                          disclosure="缺少对比期快照：仅呈现本期点位。")],
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
