"""领域包：Density / Hotspot（密度与热点）。

语义分界（C4 红线）：视觉密度（descriptive）≠ KDE 密度面 ≠ 热点显著性。
只有统计条件满足时才允许显著性结论；不足时确定性降级并披露。
"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CHART,
    MAP_COMPONENTS_CONTINUOUS,
    boundary_role,
    denominator_role,
    fb,
    min_points_rule,
    obl,
    point_fallback,
    standard_completion,
    subject_role,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="density_visual_overview",
        name="视觉密度概览",
        description="纯视觉密度感知（descriptive）：热力图表达疏密，不附统计显著性声明。",
        intent_tasks=["distribution_overview", "concentration_analysis"],
        intent_cartography=["density_overview", "point_overlay"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "point_profile"],
        optional_analysis=["admin_aggregation"],
        primary_cartography="visual_heatmap",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=43,
        schema_version=2,
        workflow=wf(
            "density", "visual_density",
            zh=["疏密", "密度大概", "密集程度", "哪里密"],
            en=["visual density", "density impression"],
            roles=[subject_role()],
            obligations=[obl(
                "density_visual_not_significance", "disclosure",
                code="DENSITY_VISUAL_NOT_SIGNIFICANCE",
                desc="视觉热力是描述性表达，不得表述为统计显著热点。",
            )],
            completion=standard_completion(),
            fallbacks=[fb("INSUFFICIENT_POINTS", frm="visual_heatmap", to="point_distribution",
                          downgrade="degraded",
                          disclosure="样本不足，热力图降级为点分布（描述性展示）。")],
        ),
    ),
    CartographyRecipe(
        id="density_quantitative_per_area",
        name="定量密度分析",
        description="单位面积定量密度（个/km²）：行政聚合 + 面积分母归一化，分母缺失时禁止密度结论。",
        intent_tasks=["analytical_density", "administrative_statistic"],
        intent_cartography=["administrative_choropleth"],
        preferred_analysis=["admin_boundary_query", "admin_aggregation", "rate_aggregation", "point_profile"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="admin boundaries unavailable", reason_code="NEEDS_ADMIN_UNITS", use="point_distribution")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=43,
        schema_version=2,
        workflow=wf(
            "density", "quantitative_density",
            zh=["定量密度", "单位面积", "密度排名"],
            en=["quantitative density", "density per area"],
            roles=[subject_role(), boundary_role(), denominator_role()],
            obligations=[obl(
                "density_requires_denominator", "denominator",
                code="DENSITY_MISSING_AREA_DENOMINATOR",
                desc="定量密度需要面积分母；缺失时只能给计数，不得称密度。",
                action="degrade_with_disclosure",
            )],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("DATA_ROLE_MISSING_DENOMINATOR", frm="density_per_area", to="raw_counts",
                          downgrade="degraded",
                          disclosure="缺少面积分母：仅呈现计数统计，不称密度。",
                          blocks=False)],
        ),
    ),
    CartographyRecipe(
        id="density_grid_h3",
        name="H3 六边形格网密度",
        description="H3 六边形格网聚合密度：格网计数 choropleth（聚合表达，非核密度估计）。",
        intent_tasks=["distribution_overview", "analytical_density", "concentration_analysis"],
        intent_cartography=["aggregate_grid", "density_overview"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("aggregate_grid", min_points=20)],
        preferred_analysis=["poi_query", "grid_binning", "point_profile"],
        optional_analysis=["admin_aggregation"],
        primary_cartography="aggregate_grid",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=44,
        schema_version=2,
        workflow=wf(
            "density", "grid_density",
            zh=["h3", "六边形", "蜂窝格网"],
            en=["h3 hexbin", "hexagon density"],
            roles=[subject_role()],
            completion=standard_completion(),
            fallbacks=[fb("INSUFFICIENT_POINTS", frm="aggregate_grid", to="point_distribution",
                          downgrade="degraded",
                          disclosure="样本不足（<20），格网聚合降级为点分布。")],
        ),
    ),
    CartographyRecipe(
        id="density_grid_fishnet",
        name="渔网格网密度",
        description="规则渔网格网聚合密度：等面积单元计数 choropleth，适合与行政边界叠加。",
        intent_tasks=["distribution_overview", "analytical_density"],
        intent_cartography=["aggregate_grid", "administrative_choropleth"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("aggregate_grid", min_points=20)],
        preferred_analysis=["poi_query", "grid_binning", "admin_boundary_query", "point_profile"],
        primary_cartography="aggregate_grid",
        secondary_cartography=["administrative_aggregation"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "density", "grid_density",
            zh=["渔网", "网格密度", "方格统计"],
            en=["fishnet grid", "grid aggregation"],
            roles=[subject_role()],
            completion=standard_completion(),
            fallbacks=[fb("INSUFFICIENT_POINTS", frm="aggregate_grid", to="point_distribution",
                          downgrade="degraded",
                          disclosure="样本不足（<20），格网聚合降级为点分布。")],
        ),
    ),
    CartographyRecipe(
        id="density_kde_surface",
        name="KDE 核密度面",
        description="核密度估计连续表面：样本充足性前置（numeric 样本守卫），不足时降级视觉热力并披露。",
        intent_tasks=["concentration_analysis", "analytical_density"],
        intent_cartography=["density_overview", "raster_surface"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "kde_density", "density_surface", "point_profile"],
        primary_cartography="visual_heatmap",
        secondary_cartography=["raster_surface", "point_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=44,
        schema_version=2,
        workflow=wf(
            "density", "kde_density",
            zh=["核密度", "kde", "密度面"],
            en=["kde", "kernel density"],
            roles=[subject_role()],
            obligations=[obl(
                "kde_sample_sufficiency", "precondition",
                precondition="min_numeric_samples:8",
                code="KDE_INSUFFICIENT_SAMPLES",
                desc="KDE 需要足够样本；不足时降级并披露，不得渲染伪密度面。",
                action="degrade_with_disclosure",
            )],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("KDE_INSUFFICIENT_SAMPLES", frm="kde_surface", to="visual_heatmap",
                          downgrade="approximation",
                          disclosure="样本不足：KDE 密度面降级为视觉热力（描述性，非估计量）。")],
        ),
    ),
    CartographyRecipe(
        id="density_hotspot_screening",
        name="热点初筛",
        description="聚集初筛：先视觉热力/格网聚合锁定候选区，显著性检验交由统计分析工作流（不得越权宣称）。",
        intent_tasks=["concentration_analysis"],
        intent_cartography=["density_overview", "hotspot_overlay", "aggregate_grid"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "kde_density", "grid_binning", "point_profile"],
        optional_analysis=["hotspot"],
        primary_cartography="visual_heatmap",
        secondary_cartography=["hotspot_overlay", "aggregate_grid"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=45,
        schema_version=2,
        workflow=wf(
            "density", "hotspot_screening",
            zh=["热点初筛", "聚集筛查", "初步热点"],
            en=["hotspot screening", "clustering screening"],
            roles=[subject_role()],
            obligations=[obl(
                "hotspot_significance_requires_test", "disclosure",
                code="HOTSPOT_SCREENING_NOT_SIGNIFICANCE",
                desc="初筛结果不得表述为统计显著热点；显著性结论需检验工作流。",
            )],
            completion=standard_completion(),
            fallbacks=[fb("INSUFFICIENT_POINTS", frm="visual_heatmap", to="point_distribution",
                          downgrade="degraded",
                          disclosure="样本不足，热力图降级为点分布。")],
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
