"""领域包：Disaster（应急管理）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CHART,
    boundary_role,
    fb,
    obl,
    role,
    standard_completion,
    subject_role,
    wf,
    auto_fallback,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="geological_hazard_inventory",
        name="地质灾害点清单",
        description="地灾隐患点分布清单（密度 + 行政区归集）：点位台账语义。",
        intent_tasks=["distribution_overview", "risk_exposure", "administrative_statistic"],
        intent_cartography=["point_overlay", "administrative_choropleth", "density_overview"],
        preferred_analysis=["poi_query", "admin_boundary_query", "admin_aggregation", "point_profile",
                            "kde_density"],
        primary_cartography="point_overlay",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="point_count < threshold", reason_code="INSUFFICIENT_POINTS",
                                  use="point_distribution")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "disaster", "hazard_inventory",
            zh=["地灾点", "隐患点", "地质灾害清单", "隐患排查"],
            en=["geological hazard inventory"],
            roles=[subject_role(), boundary_role()],
            obligations=[
                obl("hazard_point_density_semantics", "disclosure",
                    code="HAZARD_DENSITY_IS_DESCRIPTIVE",
                    desc="隐患点密度为描述性表达；不等于易发性评价。"),
            ],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="flood_inundation_screen",
        name="内涝影响筛查",
        description="内涝点影响范围筛查（积水点缓冲 + 受体连接）：几何代理披露。",
        intent_tasks=["risk_exposure", "watershed_analysis", "proximity_analysis"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "geometry_buffer", "multi_ring_buffer", "spatial_join",
                            "category_breakdown"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        fallback_links=auto_fallback(),  # ADR-0151 P7：通用兜底链（auto_generated）
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=47,
        schema_version=2,
        workflow=wf(
            "disaster", "inundation_screen",
            zh=["内涝点", "积水点", "易涝点影响"],
            en=["waterlogging screen"],
            roles=[
                role("hazard", capability="geometry_buffer", artifacts=("proximity_zone",),
                     geometry=("polygon",), note="积水点影响缓冲（代理）"),
                subject_role(),
            ],
            obligations=[
                obl("inundation_buffer_proxy", "disclosure",
                    code="FLOOD_GEOMETRIC_APPROXIMATION",
                    desc="积水点缓冲是几何代理，非水力模型推演。"),
            ],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="disaster_shelter_accessibility",
        name="避难场所可达保障",
        description="避难场所可达性保障评价（响应圈 + 盲区 + 容量提示）：阈值口径披露。",
        intent_tasks=["accessibility_analysis", "risk_exposure", "spatial_equity"],
        intent_cartography=["proximity_overlay", "administrative_choropleth"],
        preferred_analysis=["poi_query", "service_area", "admin_boundary_query", "admin_aggregation",
                            "rate_aggregation"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        fallback_links=auto_fallback(),  # ADR-0151 P7：通用兜底链（auto_generated）
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "disaster", "shelter_accessibility",
            zh=["避难所可达", "疏散保障", "避难圈"],
            en=["shelter accessibility"],
            roles=[subject_role(), boundary_role(),
                   role("population", acquisition="data_fabric", required=False)],
            obligations=[
                obl("shelter_time_threshold", "disclosure",
                    code="SHELTER_TIME_THRESHOLD_DISCLOSURE",
                    desc="避难可达阈值（如 500m/10min）必须显式披露。"),
            ],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="emergency_resource_dispatch",
        name="应急资源调度分析",
        description="应急资源点到需求点分配（最近设施 + 服务区）：网络口径与降级披露。",
        intent_tasks=["network_route", "risk_exposure", "accessibility_analysis"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "closest_facility", "service_area", "point_profile"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="network unavailable", reason_code="NETWORK_DISCONNECTED",
                                  use="euclidean_proxy")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=47,
        schema_version=2,
        workflow=wf(
            "disaster", "resource_dispatch",
            zh=["应急调度", "救援分配", "物资调度", "应急资源"],
            en=["emergency dispatch analysis"],
            roles=[subject_role(),
                   role("network", capability="poi_query",
                        artifacts=("network_graph", "line_feature_set"),
                        geometry=("line", "network"), policy="degrade",
                        disclosure="缺少路网：按直线最近分配（代理）。")],
            completion=standard_completion(),
            fallbacks=[fb("NETWORK_DISCONNECTED", frm="network_dispatch", to="euclidean_assignment",
                          downgrade="proxy",
                          disclosure="路网不可用：调度距离按直线估计（代理）。")],
        ),
    ),
    CartographyRecipe(
        id="seismic_intensity_exposure_screen",
        name="震后影响快速筛查",
        description="震中缓冲/烈度代理 × 人口设施暴露快速筛查：近似语义强披露（非专业烈度场）。",
        intent_tasks=["risk_exposure"],
        intent_cartography=["proximity_overlay", "administrative_choropleth"],
        preferred_analysis=["geometry_buffer", "multi_ring_buffer", "geometry_overlay",
                            "admin_boundary_query", "admin_aggregation"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        fallback_links=auto_fallback(),  # ADR-0151 P7：通用兜底链（auto_generated）
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=48,
        schema_version=2,
        workflow=wf(
            "disaster", "seismic_quick_screen",
            zh=["地震影响", "震后筛查", "极重灾区估计"],
            en=["earthquake quick screening"],
            roles=[
                role("hazard", capability="multi_ring_buffer", artifacts=("proximity_zone",),
                     geometry=("polygon",), note="震中距离圈（烈度代理）"),
                role("receptor", acquisition="data_fabric", required=False),
                boundary_role(),
            ],
            obligations=[
                obl("seismic_quick_screen_proxy", "disclosure",
                    code="SEISMIC_PROXIMITY_PROXY",
                    desc="震中距离圈非专业烈度场，仅作应急快速筛查。"),
            ],
            completion=standard_completion(uncertainty=True),
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
