"""领域包：Distribution / Inventory（分布与要素清单）。

工作流族语义：把「XX 分布情况 / 要素清单」分化为可视化概览、行政清查、
单主体轻量查看与行业设施清单 —— 数量统计不得自动等价 density（C4 红线）。
"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_BASE,
    MAP_COMPONENTS_CHART,
    MAP_COMPONENTS_STATS,
    boundary_role,
    fb,
    min_points_rule,
    point_fallback,
    standard_completion,
    subject_role,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="edu_facility_distribution",
        name="教育设施分布概览",
        description="学校/幼儿园等教育设施的分布概览：视觉热力 + 点叠加 + 行政聚合；数量层面不宣称密度显著性。",
        intent_tasks=["distribution_overview", "simple_view"],
        intent_cartography=["density_overview", "point_overlay", "administrative_choropleth"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "admin_boundary_query", "point_profile", "admin_aggregation"],
        optional_analysis=["category_breakdown"],
        primary_cartography="visual_heatmap",
        secondary_cartography=["point_overlay", "administrative_aggregation"],
        default_components=MAP_COMPONENTS_STATS,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"], "chart": True},
        priority=42,
        schema_version=2,
        workflow=wf(
            "distribution", "facility_distribution",
            zh=["教育设施", "学校分布", "幼儿园", "中小学分布"],
            en=["school distribution", "education facility"],
            roles=[subject_role(), boundary_role()],
            completion=standard_completion(),
            fallbacks=[fb("INSUFFICIENT_POINTS", frm="visual_heatmap", to="point_distribution",
                          downgrade="degraded",
                          disclosure="样本不足，热力图降级为点分布（描述性展示，非密度分析）。")],
        ),
    ),
    CartographyRecipe(
        id="healthcare_facility_distribution",
        name="医疗设施分布概览",
        description="医院/诊所/药店等医疗设施的分布概览：热力 + 点图 + 行政聚合统计。",
        intent_tasks=["distribution_overview", "simple_view"],
        intent_cartography=["density_overview", "point_overlay", "administrative_choropleth"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "admin_boundary_query", "point_profile", "admin_aggregation"],
        optional_analysis=["category_breakdown"],
        primary_cartography="visual_heatmap",
        secondary_cartography=["point_overlay", "administrative_aggregation"],
        default_components=MAP_COMPONENTS_STATS,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"], "chart": True},
        priority=42,
        schema_version=2,
        workflow=wf(
            "distribution", "facility_distribution",
            zh=["医疗设施", "医院分布", "诊所分布", "药店分布"],
            en=["hospital distribution", "healthcare facility"],
            roles=[subject_role(), boundary_role()],
            completion=standard_completion(),
            fallbacks=[fb("INSUFFICIENT_POINTS", frm="visual_heatmap", to="point_distribution",
                          downgrade="degraded",
                          disclosure="样本不足，热力图降级为点分布（描述性展示，非密度分析）。")],
        ),
    ),
    CartographyRecipe(
        id="transit_station_distribution",
        name="公交地铁站点分布",
        description="轨道交通/公交站点分布：点叠加为主，格网聚合为辅（站点为线网离散采样，密度语义需谨慎）。",
        intent_tasks=["distribution_overview", "simple_view"],
        intent_cartography=["point_overlay", "aggregate_grid", "density_overview"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "admin_boundary_query", "point_profile", "grid_binning"],
        primary_cartography="point_overlay",
        secondary_cartography=["aggregate_grid"],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=44,
        schema_version=2,
        workflow=wf(
            "distribution", "facility_distribution",
            zh=["地铁站点", "公交站", "站点分布", "轨道站点"],
            en=["metro stations", "bus stops", "transit stops"],
            roles=[subject_role(), boundary_role()],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="green_space_distribution",
        name="公园绿地分布",
        description="公园/绿地分布：面+点混合主体，点入口热力 + 面状绿地的行政区清查。",
        intent_tasks=["distribution_overview"],
        intent_cartography=["point_overlay", "administrative_choropleth", "density_overview"],
        preferred_analysis=["poi_query", "admin_boundary_query", "admin_aggregation", "point_profile"],
        optional_analysis=["zonal_statistics"],
        primary_cartography="point_overlay",
        secondary_cartography=["administrative_aggregation"],
        default_components=MAP_COMPONENTS_STATS,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "distribution", "facility_distribution",
            zh=["公园", "绿地", "绿化分布", "绿地分布"],
            en=["park distribution", "green space"],
            roles=[subject_role(), boundary_role()],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="emergency_shelter_distribution",
        name="应急避难场所分布",
        description="避难场所/应急设施分布：点图 + 行政清查，供应急规划引用（覆盖评价另行可达性工作流）。",
        intent_tasks=["distribution_overview", "simple_view"],
        intent_cartography=["point_overlay", "administrative_choropleth"],
        required_geometry=["Point", "MultiPoint"],
        preferred_analysis=["poi_query", "admin_boundary_query", "admin_aggregation", "point_profile"],
        primary_cartography="point_overlay",
        secondary_cartography=["administrative_aggregation"],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png", "pdf"]},
        priority=44,
        schema_version=2,
        workflow=wf(
            "distribution", "facility_distribution",
            zh=["避难场所", "应急避难", "人防设施", "应急设施分布"],
            en=["emergency shelter", "evacuation site"],
            roles=[subject_role(), boundary_role()],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="cultural_facility_distribution",
        name="文体设施分布",
        description="图书馆/体育馆/博物馆等文体设施分布概览。",
        intent_tasks=["distribution_overview", "simple_view"],
        intent_cartography=["density_overview", "point_overlay"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "admin_boundary_query", "point_profile", "admin_aggregation"],
        primary_cartography="visual_heatmap",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "distribution", "facility_distribution",
            zh=["文体设施", "图书馆", "博物馆", "体育馆分布"],
            en=["library distribution", "museum distribution"],
            roles=[subject_role(), boundary_role()],
            completion=standard_completion(),
            fallbacks=[fb("INSUFFICIENT_POINTS", frm="visual_heatmap", to="point_distribution",
                          downgrade="degraded",
                          disclosure="样本不足，热力图降级为点分布（描述性展示）。")],
        ),
    ),
    CartographyRecipe(
        id="infrastructure_node_distribution",
        name="市政节点设施分布",
        description="加油站/充电站等市政节点设施分布：点图 + 类别细分。",
        intent_tasks=["distribution_overview", "categorical_distribution"],
        intent_cartography=["point_overlay", "categorical_thematic"],
        required_geometry=["Point", "MultiPoint"],
        preferred_analysis=["poi_query", "admin_boundary_query", "category_breakdown", "point_profile"],
        primary_cartography="categorical_thematic",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "distribution", "facility_distribution",
            zh=["加油站", "充电站", "市政设施", "充电桩分布"],
            en=["charging station", "gas station distribution"],
            roles=[subject_role(), boundary_role()],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="logistics_facility_distribution",
        name="物流网点分布",
        description="物流园区/快递网点等物流设施分布概览。",
        intent_tasks=["distribution_overview"],
        intent_cartography=["point_overlay", "density_overview"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "admin_boundary_query", "point_profile", "admin_aggregation"],
        primary_cartography="visual_heatmap",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=48,
        schema_version=2,
        workflow=wf(
            "distribution", "facility_distribution",
            zh=["物流园", "快递网点", "物流网点", "仓储分布"],
            en=["logistics facility", "warehouse distribution"],
            roles=[subject_role(), boundary_role()],
            completion=standard_completion(),
            fallbacks=[fb("INSUFFICIENT_POINTS", frm="visual_heatmap", to="point_distribution",
                          downgrade="degraded",
                          disclosure="样本不足，热力图降级为点分布（描述性展示）。")],
        ),
    ),
    CartographyRecipe(
        id="financial_branch_distribution",
        name="金融网点分布",
        description="银行/ATM 等金融网点分布概览。",
        intent_tasks=["distribution_overview", "simple_view"],
        intent_cartography=["density_overview", "point_overlay"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "admin_boundary_query", "point_profile", "admin_aggregation"],
        primary_cartography="visual_heatmap",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=48,
        schema_version=2,
        workflow=wf(
            "distribution", "facility_distribution",
            zh=["银行网点", "atm", "金融网点", "营业部分布"],
            en=["bank branch", "atm distribution"],
            roles=[subject_role(), boundary_role()],
            completion=standard_completion(),
            fallbacks=[fb("INSUFFICIENT_POINTS", frm="visual_heatmap", to="point_distribution",
                          downgrade="degraded",
                          disclosure="样本不足，热力图降级为点分布（描述性展示）。")],
        ),
    ),
    CartographyRecipe(
        id="poi_inventory_catalog",
        name="POI 要素清单",
        description="「XX 有哪些 / 要素清单 / 本底调查」：全量清查 + 类别构成 + 行政归属，强调清单完整性而非密度。",
        intent_tasks=["distribution_overview", "categorical_distribution"],
        intent_cartography=["point_overlay", "categorical_thematic"],
        required_geometry=["Point", "MultiPoint"],
        preferred_analysis=["poi_query", "category_breakdown", "admin_boundary_query", "admin_aggregation"],
        primary_cartography="categorical_thematic",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=45,
        schema_version=2,
        workflow=wf(
            "distribution", "inventory_catalog",
            zh=["要素清单", "本底调查", "有哪些", "清查", "台账"],
            en=["inventory", "catalog of", "asset list"],
            roles=[subject_role(), boundary_role()],
            completion=standard_completion(),
            recompute=["data", "parameter", "output"],
            evidence=["inventory_completeness_note"],
        ),
    ),
    CartographyRecipe(
        id="admin_feature_audit",
        name="行政区划要素清查",
        description="按行政区逐级清查要素数量（各乡镇/街道/村），产出计数台账 + 分级填色。",
        intent_tasks=["administrative_statistic", "distribution_overview"],
        intent_cartography=["administrative_choropleth", "point_overlay"],
        preferred_analysis=["poi_query", "admin_boundary_query", "admin_aggregation", "category_breakdown"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(
            when="admin boundaries unavailable",
            reason_code="NEEDS_ADMIN_UNITS",
            use="point_distribution",
        )],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=45,
        schema_version=2,
        workflow=wf(
            "distribution", "inventory_catalog",
            zh=["清查", "逐级统计", "各乡镇", "各街道", "各街道数量"],
            en=["feature audit by admin unit"],
            roles=[subject_role(), boundary_role()],
            completion=standard_completion(),
            fallbacks=[fb("NEEDS_ADMIN_UNITS", frm="administrative_choropleth", to="point_distribution",
                          downgrade="degraded",
                          disclosure="缺少行政区边界：仅出点分布与总数，不做分区统计。")],
        ),
    ),
    CartographyRecipe(
        id="landmark_simple_view",
        name="地标要素轻量查看",
        description="「给我看看 XX」的最小分析路径：主体点图 + 属性画像，禁止过度分析（anti-over-analysis）。",
        intent_tasks=["simple_view"],
        intent_cartography=["simple_point_map"],
        required_geometry=["Point", "MultiPoint"],
        preferred_analysis=["poi_query", "point_profile"],
        primary_cartography="simple_point_map",
        secondary_cartography=[],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=40,
        schema_version=2,
        workflow=wf(
            "distribution", "simple_view",
            zh=["看看", "看一下", "标出来"],
            en=["show me"],
            roles=[subject_role()],
            completion=standard_completion(),
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
