"""领域包：Environment（生态环境）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CHART,
    MAP_COMPONENTS_CONTINUOUS,
    boundary_role,
    obl,
    point_fallback,
    role,
    standard_completion,
    subject_role,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe

_MONITOR_SUBJECT = subject_role(capability="poi_query",
                                artifacts=("point_feature_set", "poi_feature_set"),
                                geometry=("point",))

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="monitoring_station_coverage",
        name="监测站点覆盖",
        description="环境监测站覆盖评价（站网密度 + 空白区）：站网密度语义（数量统计 ≠ 插值精度）。",
        intent_tasks=["distribution_overview", "administrative_statistic", "accessibility_analysis"],
        intent_cartography=["point_overlay", "administrative_choropleth"],
        preferred_analysis=["poi_query", "admin_boundary_query", "admin_aggregation", "point_profile"],
        optional_analysis=["service_area"],
        primary_cartography="point_overlay",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "environment", "station_coverage",
            zh=["监测站", "站点覆盖", "站网", "监测点位"],
            en=["monitoring station coverage"],
            roles=[_MONITOR_SUBJECT, boundary_role()],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="pollution_source_buffer_screen",
        name="污染源缓冲筛查",
        description="污染源周边敏感目标缓冲筛查（多环缓冲 + 受体连接）：距离口径披露。",
        intent_tasks=["proximity_analysis", "risk_exposure"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "multi_ring_buffer", "geometry_buffer", "spatial_join",
                            "category_breakdown"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "environment", "pollution_buffer_screen",
            zh=["污染源", "卫生防护距离", "周边敏感点", "环境防护"],
            en=["pollution source buffer"],
            roles=[
                role("hazard", capability="multi_ring_buffer", artifacts=("proximity_zone",),
                     geometry=("polygon",), note="污染源缓冲圈"),
                subject_role(),
            ],
            obligations=[
                obl("pollution_buffer_semantics", "disclosure",
                    code="BUFFER_DISTANCE_SEMANTICS",
                    desc="缓冲距离依据（规范/模拟/用户）必须披露；缓冲筛查不是扩散模拟。"),
            ],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="env_sensitivity_zoning",
        name="环境敏感区划",
        description="环境敏感性分区（水源/生态/敏感点约束叠加）：约束口径披露。",
        intent_tasks=["suitability_assessment", "risk_exposure"],
        intent_cartography=["raster_surface", "proximity_overlay"],
        preferred_analysis=["raster_source", "raster_reclassify", "geometry_overlay", "geometry_buffer",
                            "zonal_statistics"],
        primary_cartography="raster_surface",
        secondary_cartography=["proximity_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"]},
        priority=47,
        schema_version=2,
        workflow=wf(
            "environment", "sensitivity_zoning",
            zh=["环境敏感区", "生态敏感", "环境管控单元"],
            en=["environmental sensitivity zoning"],
            roles=[subject_role(capability="raster_source", artifacts=("raster_surface",),
                                geometry=("raster",)),
                   role("constraint", acquisition="user_upload", required=False)],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="air_quality_admin_stats",
        name="行政区空气质量统计",
        description="行政区空气质量站点读数聚合统计（读数 ≠ 空间面）：站点口径披露。",
        intent_tasks=["administrative_statistic", "temporal_trend"],
        intent_cartography=["administrative_choropleth", "point_overlay"],
        preferred_analysis=["poi_query", "admin_boundary_query", "admin_aggregation",
                            "temporal_profile", "temporal_aggregate"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "environment", "air_quality_admin",
            zh=["各区空气质量", "空气质量排名", "aqi统计"],
            en=["air quality by district"],
            roles=[_MONITOR_SUBJECT, boundary_role()],
            obligations=[
                obl("aqi_point_semantics", "disclosure",
                    code="AQI_POINT_SAMPLING_SEMANTICS",
                    desc="站点读数是点位采样值；行政区均值为站点聚合，不代表空间连续浓度场。"),
            ],
            completion=standard_completion(uncertainty=True),
        ),
    ),
    CartographyRecipe(
        id="noise_buffer_screen",
        name="噪声影响筛查",
        description="噪声源（交通/工业）缓冲筛查：几何缓冲代理语义（非声场模拟）。",
        intent_tasks=["proximity_analysis", "risk_exposure"],
        intent_cartography=["proximity_overlay", "categorical_thematic"],
        preferred_analysis=["poi_query", "geometry_buffer", "multi_ring_buffer", "spatial_join",
                            "category_breakdown"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["categorical_thematic"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=48,
        schema_version=2,
        workflow=wf(
            "environment", "noise_screen",
            zh=["噪声", "噪音影响", "声环境", "沿线噪声"],
            en=["noise exposure screening"],
            roles=[
                role("hazard", capability="geometry_buffer", artifacts=("proximity_zone",),
                     geometry=("polygon",), note="噪声源缓冲（代理）"),
                subject_role(),
            ],
            obligations=[
                obl("noise_proxy_disclosure", "disclosure",
                    code="NOISE_BUFFER_IS_PROXY",
                    desc="缓冲筛查是空间代理，不等于声传播模拟（分贝值需专业模型）。"),
            ],
            completion=standard_completion(),
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
