"""领域包：Equity（公平性评价）。

红线：没有人口分母时严禁宣称 per-capita equity（EQUITY_MISSING_DENOMINATOR）。
"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CHART,
    boundary_role,
    denominator_role,
    fb,
    obl,
    role,
    standard_completion,
    subject_role,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_EQUITY_OBLIGATIONS = [
    obl("equity_denominator_required", "denominator",
        code="EQUITY_MISSING_DENOMINATOR",
        desc="公平性评价需要人口/需求分母；缺失时只能评价数量与密度，不得宣称公平性。",
        action="degrade_with_disclosure"),
    obl("equity_measure_semantics", "disclosure",
        code="EQUITY_MEASURE_SEMANTICS",
        desc="公平性度量口径（人均/可达性比/基尼类）必须披露。"),
]
_EQUITY_FALLBACK = fb(
    "DATA_ROLE_MISSING_DENOMINATOR", frm="equity_ratio_map", to="count_density_view",
    downgrade="degraded",
    disclosure="缺少人口分母：仅呈现数量/密度分布，不构成公平性结论。",
)

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="education_equity_per_capita",
        name="教育资源人均公平性",
        description="教育设施人均配置公平性（行政区人均学位/学校数）：分母义务强制。",
        intent_tasks=["spatial_equity", "administrative_statistic"],
        intent_cartography=["administrative_choropleth", "point_overlay"],
        preferred_analysis=["poi_query", "admin_boundary_query", "admin_aggregation",
                            "rate_aggregation", "category_breakdown"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="denominator missing", reason_code="MISSING_DENOMINATOR",
                                  use="count_only")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=43,
        schema_version=2,
        workflow=wf(
            "equity", "education_equity",
            zh=["教育资源", "学位公平", "学校均衡", "教育公平"],
            en=["education equity", "school balance"],
            roles=[subject_role(), boundary_role(), denominator_role()],
            obligations=_EQUITY_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_EQUITY_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="healthcare_equity_access",
        name="医疗可达公平性",
        description="医疗服务可达性公平（行政区可达值离散度）：可达性口径与分母义务。",
        intent_tasks=["spatial_equity", "accessibility_analysis"],
        intent_cartography=["administrative_choropleth", "proximity_overlay"],
        preferred_analysis=["poi_query", "service_area", "admin_boundary_query", "admin_aggregation",
                            "rate_aggregation", "global_morans_i"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["proximity_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="denominator missing", reason_code="MISSING_DENOMINATOR",
                                  use="count_only")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "equity", "healthcare_equity",
            zh=["医疗公平", "就医公平", "医疗均衡", "医疗资源分布合理性"],
            en=["healthcare equity", "medical accessibility fairness"],
            roles=[subject_role(), boundary_role(), denominator_role()],
            obligations=_EQUITY_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_EQUITY_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="park_access_equity",
        name="公园绿地可达公平",
        description="公园绿地步行可达公平性（覆盖人口比例）：分母义务。",
        intent_tasks=["spatial_equity", "accessibility_analysis"],
        intent_cartography=["administrative_choropleth", "proximity_overlay"],
        preferred_analysis=["poi_query", "service_area", "admin_boundary_query", "admin_aggregation",
                            "rate_aggregation"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["proximity_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="denominator missing", reason_code="MISSING_DENOMINATOR",
                                  use="count_only")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=45,
        schema_version=2,
        workflow=wf(
            "equity", "park_equity",
            zh=["公园公平", "绿地公平", "公园可达均衡"],
            en=["park equity", "green space fairness"],
            roles=[subject_role(), boundary_role(), denominator_role()],
            obligations=_EQUITY_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_EQUITY_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="emergency_equity_coverage",
        name="应急服务均衡覆盖",
        description="应急设施响应覆盖均衡性（行政区覆盖比离散）：阈值口径 + 分母义务。",
        intent_tasks=["spatial_equity", "accessibility_analysis"],
        intent_cartography=["administrative_choropleth", "proximity_overlay"],
        preferred_analysis=["poi_query", "service_area", "admin_boundary_query", "admin_aggregation",
                            "rate_aggregation"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["proximity_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="denominator missing", reason_code="MISSING_DENOMINATOR",
                                  use="count_only")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "equity", "emergency_equity",
            zh=["应急均衡", "消防均衡", "避难公平"],
            en=["emergency equity"],
            roles=[subject_role(), boundary_role(), denominator_role()],
            obligations=_EQUITY_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_EQUITY_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="facility_per_capita_profile",
        name="设施人均画像",
        description="行政区设施人均拥有量画像（人均台账）：分母义务，无分母只报总量。",
        intent_tasks=["spatial_equity", "administrative_statistic", "analytical_density"],
        intent_cartography=["administrative_choropleth"],
        preferred_analysis=["poi_query", "admin_boundary_query", "admin_aggregation",
                            "rate_aggregation", "point_profile"],
        primary_cartography="administrative_choropleth",
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="denominator missing", reason_code="MISSING_DENOMINATOR",
                                  use="count_only")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=45,
        schema_version=2,
        workflow=wf(
            "equity", "per_capita_profile",
            zh=["人均拥有", "万人拥有", "千人指标", "人均配置"],
            en=["per capita facilities"],
            roles=[subject_role(), boundary_role(), denominator_role()],
            obligations=[
                obl("per_capita_denominator_required", "denominator",
                    code="PER_CAPITA_DENOMINATOR_REQUIRED",
                    desc="人均指标必须有人口分母；缺失时禁止 per-capita 表述。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(),
            fallbacks=[_EQUITY_FALLBACK],
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
