"""领域包：Hydrology（水文 / 流域）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CONTINUOUS,
    boundary_role,
    elevation_role,
    fb,
    obl,
    role,
    standard_completion,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

HYDRO_OBLIGATIONS = [
    obl("hydro_dem_conditioned", "transformation",
        code="HYDRO_DEM_CONDITIONING_REQUIRED",
        desc="流向计算前需要 DEM 填洼（conditioning）；未填洼结果不得用于流域划分。",
        action="degrade_with_disclosure"),
    obl("hydro_metric_crs", "precondition",
        precondition="local_metric_crs_required",
        code="HYDRO_METRIC_CRS_REQUIRED",
        desc="汇流累积/坡长需要米制 CRS。", action="degrade_with_disclosure"),
]
#: recipe 级回退表
HYDRO_FALLBACKS = [
    RecipeFallback(when="CRS not metric", reason_code="HYDRO_METRIC_CRS_REQUIRED", use="dem_view"),
    RecipeFallback(when="no valid DEM band", reason_code="TERRAIN_DEM_BAND_REQUIRED", use="summary"),
]
#: workflow 级语义回退策略
HYDRO_WF_POLICIES = [
    fb("HYDRO_METRIC_CRS_REQUIRED", frm="hydro_product", to="dem_view",
       downgrade="degraded",
       disclosure="坐标为角度单位：水文衍生不可靠，仅呈现 DEM。"),
    fb("TERRAIN_DEM_BAND_REQUIRED", frm="hydro_product", to="summary",
       downgrade="not_allowed", blocks=True,
       disclosure="无有效 DEM 输入：水文分析无法进行。"),
]

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="watershed_delineation_workflow",
        name="流域划分",
        description="DEM 流域划分：填洼 → 流向 → 汇流累积 → 出口点流域提取； Conditioning 义务强制。",
        intent_tasks=["watershed_analysis", "terrain_analysis"],
        intent_cartography=["raster_surface", "proximity_overlay"],
        preferred_analysis=["raster_source", "terrain_hydrology", "terrain_derivatives", "zonal_statistics"],
        optional_analysis=["admin_boundary_query"],
        primary_cartography="raster_surface",
        secondary_cartography=["proximity_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=HYDRO_FALLBACKS,
        export_profile={"formats": ["png"]},
        priority=44,
        schema_version=2,
        workflow=wf(
            "hydrology", "watershed_delineation",
            zh=["流域划分", "集水区", "分水岭", "汇水区"],
            en=["watershed delineation", "catchment"],
            roles=[elevation_role()],
            obligations=HYDRO_OBLIGATIONS,
            fallbacks=HYDRO_WF_POLICIES,
            completion=standard_completion(uncertainty=True),
            evidence=["pour_point_selection"],
            disclosures=["HYDRO_DEM_CONDITIONING_REQUIRED"],
        ),
    ),
    CartographyRecipe(
        id="flow_accumulation_mapping",
        name="汇流累积制图",
        description="汇流累积量面图：河道潜在路径刻画（单元数披露，非实测水系）。",
        intent_tasks=["watershed_analysis", "terrain_analysis"],
        intent_cartography=["raster_surface"],
        preferred_analysis=["raster_source", "terrain_hydrology", "terrain_derivatives"],
        primary_cartography="raster_surface",
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=HYDRO_FALLBACKS,
        export_profile={"formats": ["png"]},
        priority=45,
        schema_version=2,
        workflow=wf(
            "hydrology", "flow_accumulation",
            zh=["汇流累积", "流累积量", "径流路径"],
            en=["flow accumulation"],
            roles=[elevation_role()],
            obligations=HYDRO_OBLIGATIONS,
            fallbacks=HYDRO_WF_POLICIES,
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="stream_network_extraction",
        name="河网提取",
        description="由汇流累积阈值提取河网（栅格→矢量线）：阈值敏感性披露。",
        intent_tasks=["watershed_analysis"],
        intent_cartography=["proximity_overlay", "raster_surface"],
        preferred_analysis=["raster_source", "terrain_hydrology", "terrain_derivatives"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["raster_surface"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=HYDRO_FALLBACKS,
        export_profile={"formats": ["png"]},
        priority=45,
        schema_version=2,
        workflow=wf(
            "hydrology", "stream_extraction",
            zh=["河网提取", "水系提取", "河道提取"],
            en=["stream extraction", "river network"],
            roles=[elevation_role()],
            obligations=[
                *HYDRO_OBLIGATIONS,
                obl("stream_threshold_disclosure", "disclosure",
                    code="STREAM_THRESHOLD_SENSITIVITY",
                    desc="河网提取的汇流阈值影响密度，需披露阈值与敏感性。"),
            ],
            fallbacks=HYDRO_WF_POLICIES,
            completion=standard_completion(uncertainty=True),
        ),
    ),
    CartographyRecipe(
        id="drainage_density_stats",
        name="排水分区密度统计",
        description="分区排水密度（河网长度/面积）：面积分母义务，缺分母不得称密度。",
        intent_tasks=["watershed_analysis", "administrative_statistic"],
        intent_cartography=["administrative_choropleth", "proximity_overlay"],
        preferred_analysis=["raster_source", "terrain_hydrology", "admin_boundary_query",
                            "admin_aggregation", "rate_aggregation"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["proximity_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=HYDRO_FALLBACKS,
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=47,
        schema_version=2,
        workflow=wf(
            "hydrology", "drainage_density",
            zh=["排水密度", "河网密度", "水系密度"],
            en=["drainage density"],
            roles=[elevation_role(), boundary_role()],
            obligations=[
                *HYDRO_OBLIGATIONS,
                obl("drainage_density_denominator", "denominator",
                    code="DRAINAGE_DENSITY_MISSING_AREA",
                    desc="排水密度需要面积分母。", action="degrade_with_disclosure"),
            ],
            fallbacks=[
                *HYDRO_WF_POLICIES,
                fb("DATA_ROLE_MISSING_DENOMINATOR", frm="drainage_density", to="stream_length_stats",
                   downgrade="degraded",
                   disclosure="缺少面积分母：仅统计河网长度，不称密度。"),
            ],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="flood_extent_screening",
        name="淹没范围初筛",
        description="基于 DEM 的水位高程淹没初筛（平推法/盆地填充近似）：必须披露为几何近似，非水动力模拟。",
        intent_tasks=["watershed_analysis", "risk_exposure", "terrain_analysis"],
        intent_cartography=["raster_surface", "proximity_overlay"],
        preferred_analysis=["raster_source", "terrain_hydrology", "terrain_derivatives", "raster_reclassify"],
        optional_analysis=["poi_query", "admin_boundary_query"],
        primary_cartography="raster_surface",
        secondary_cartography=["proximity_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=HYDRO_FALLBACKS,
        export_profile={"formats": ["png"]},
        priority=45,
        schema_version=2,
        workflow=wf(
            "hydrology", "flood_extent_screening",
            zh=["淹没范围", "洪水淹没", "内涝初筛", "水位推演"],
            en=["flood extent", "inundation screening"],
            roles=[elevation_role()],
            obligations=[
                *HYDRO_OBLIGATIONS,
                obl("flood_not_hydrodynamic", "disclosure",
                    code="FLOOD_GEOMETRIC_APPROXIMATION",
                    desc="高程平推淹没为几何近似，不得表述为水动力模拟结果。"),
            ],
            fallbacks=HYDRO_WF_POLICIES,
            completion=standard_completion(uncertainty=True),
        ),
    ),
    CartographyRecipe(
        id="basin_pour_point_stats",
        name="出口断面流域统计",
        description="指定出口点（pour point）的流域圈定与属性统计（面积/坡度/土地利用构成）。",
        intent_tasks=["watershed_analysis", "administrative_statistic"],
        intent_cartography=["proximity_overlay", "administrative_choropleth"],
        preferred_analysis=["raster_source", "terrain_hydrology", "point_profile",
                            "zonal_statistics", "admin_boundary_query"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["administrative_aggregation"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=HYDRO_FALLBACKS,
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=47,
        schema_version=2,
        workflow=wf(
            "hydrology", "pour_point_basin",
            zh=["出口断面", "水文站流域", "控制断面", "pour point"],
            en=["pour point basin"],
            roles=[elevation_role(),
                   role("reference", capability="point_profile",
                        artifacts=("point_feature_set",), geometry=("point",),
                        note="出口/水文站点位")],
            obligations=HYDRO_OBLIGATIONS,
            fallbacks=HYDRO_WF_POLICIES,
            completion=standard_completion(),
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
