"""领域包：Interpolation（空间插值）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CONTINUOUS,
    fb,
    min_points_rule,
    obl,
    point_fallback,
    role,
    standard_completion,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe

_NUMERIC_SUBJECT = lambda note="": role(  # noqa: E731
    "subject", capability="poi_query",
    artifacts=("point_feature_set", "poi_feature_set"), geometry=("point",),
    note=note or "主体点集需携带数值字段",
)

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="kriging_interpolation_workflow",
        name="克里金插值面",
        description="克里金插值连续表面：数值字段 + 投影 CRS + 样本充足性前置，CV 不合格不得出面。",
        intent_tasks=["raster_distribution", "concentration_analysis"],
        intent_cartography=["raster_surface", "density_overview"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "spatial_interpolation", "point_profile"],
        optional_analysis=["admin_boundary_query", "zonal_statistics"],
        primary_cartography="raster_surface",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=43,
        schema_version=2,
        workflow=wf(
            "interpolation", "kriging_surface",
            zh=["克里金", "kriging", "金插值"],
            en=["kriging"],
            roles=[_NUMERIC_SUBJECT("插值数值字段必选")],
            obligations=[
                obl("kriging_numeric_field", "precondition",
                    precondition="numeric_field_required",
                    code="KRIGING_NUMERIC_FIELD_REQUIRED",
                    desc="克里金插值需要数值字段。", action="block_method"),
                obl("kriging_projected_crs", "precondition",
                    precondition="projected_crs_required",
                    code="KRIGING_PROJECTED_CRS_REQUIRED",
                    desc="半变异建模需要米制距离；经纬度角度坐标不得直接插值。",
                    action="block_method"),
                obl("kriging_min_samples", "precondition",
                    precondition="min_numeric_samples:8",
                    code="KRIGING_INSUFFICIENT_SAMPLES",
                    desc="样本过少时克里金不稳定；不足时降级点位展示。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            evidence=["interpolation_cv_metrics"],
            fallbacks=[
                fb("KRIGING_INSUFFICIENT_SAMPLES", frm="kriging_surface", to="point_map",
                   downgrade="degraded",
                   disclosure="样本不足：不出插值面，仅呈现采样点分布（禁止伪造表面）。"),
                fb("KRIGING_PROJECTED_CRS_REQUIRED", frm="kriging_surface", to="point_map",
                   downgrade="degraded",
                   disclosure="坐标为角度单位：先投影变换再做插值；未变换前不出面。"),
            ],
        ),
    ),
    CartographyRecipe(
        id="idw_interpolation_workflow",
        name="IDW 反距离加权插值",
        description="IDW 插值连续表面：方法简单透明，样本充足性义务 + 平滑参数披露。",
        intent_tasks=["raster_distribution"],
        intent_cartography=["raster_surface"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "spatial_interpolation", "point_profile"],
        primary_cartography="raster_surface",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=44,
        schema_version=2,
        workflow=wf(
            "interpolation", "idw_surface",
            zh=["idw", "反距离", "距离加权"],
            en=["idw", "inverse distance weighting"],
            roles=[_NUMERIC_SUBJECT()],
            obligations=[
                obl("idw_numeric_field", "precondition",
                    precondition="numeric_field_required",
                    code="IDW_NUMERIC_FIELD_REQUIRED",
                    desc="IDW 需要数值字段。", action="block_method"),
                obl("idw_min_samples", "precondition",
                    precondition="min_numeric_samples:8",
                    code="IDW_INSUFFICIENT_SAMPLES",
                    desc="样本过少时 IDW 面不可靠。", action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("IDW_INSUFFICIENT_SAMPLES", frm="idw_surface", to="point_map",
                          downgrade="degraded",
                          disclosure="样本不足：不出插值面，仅呈现采样点分布。")],
        ),
    ),
    CartographyRecipe(
        id="interpolation_cv_compare",
        name="插值方法交叉验证比较",
        description="多候选插值方法 CV 比较（克里金/IDW/样条）：以验证误差选方法，禁止静默换方法。",
        intent_tasks=["raster_distribution"],
        intent_cartography=["raster_surface"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "spatial_interpolation", "point_profile"],
        primary_cartography="raster_surface",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png", "csv"]},
        priority=45,
        schema_version=2,
        workflow=wf(
            "interpolation", "cv_comparison",
            zh=["插值比较", "交叉验证", "哪个插值方法", "cv"],
            en=["interpolation cross validation", "method comparison"],
            roles=[_NUMERIC_SUBJECT()],
            obligations=[
                obl("cv_numeric_field", "precondition",
                    precondition="numeric_field_required",
                    code="CV_NUMERIC_FIELD_REQUIRED",
                    desc="CV 比较需要数值字段。", action="block_method"),
                obl("cv_min_samples", "precondition",
                    precondition="min_numeric_samples:20",
                    code="CV_INSUFFICIENT_SAMPLES",
                    desc="样本不足以支撑稳定的 CV 比较。", action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            evidence=["interpolation_cv_metrics"],
            fallbacks=[fb("CV_INSUFFICIENT_SAMPLES", frm="cv_comparison", to="single_method_default",
                          downgrade="degraded",
                          disclosure="样本不足：不做 CV 比较，按默认方法并披露未验证。")],
        ),
    ),
    CartographyRecipe(
        id="interpolation_uncertainty_map",
        name="插值不确定性图",
        description="插值方差/不确定性伴随图层：克里金方差面 + 采样点置信标注，uncertainty 维强制。",
        intent_tasks=["raster_distribution"],
        intent_cartography=["raster_surface"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "spatial_interpolation", "point_profile"],
        primary_cartography="raster_surface",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "interpolation", "uncertainty_surface",
            zh=["插值不确定性", "方差面", "精度图"],
            en=["interpolation uncertainty", "variance surface"],
            roles=[_NUMERIC_SUBJECT()],
            obligations=[obl("uncertainty_requires_variance_output", "uncertainty",
                             code="INTERPOLATION_VARIANCE_UNAVAILABLE",
                             desc="所选方法无方差输出时，必须披露不确定性不可得。")],
            completion=standard_completion(uncertainty=True),
            disclosures=["INTERPOLATION_VARIANCE_UNAVAILABLE"],
        ),
    ),
    CartographyRecipe(
        id="station_field_interpolation",
        name="站点观测场插值",
        description="气象/环境站点观测插值成面（气温/降水/空气质量）：站点密度前置 + 时相对齐义务。",
        intent_tasks=["raster_distribution", "temporal_trend"],
        intent_cartography=["raster_surface", "point_overlay"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "spatial_interpolation", "temporal_profile", "point_profile"],
        primary_cartography="raster_surface",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=44,
        schema_version=2,
        workflow=wf(
            "interpolation", "station_field",
            zh=["站点插值", "气温分布", "降水分布", "监测站插值"],
            en=["station interpolation", "weather surface"],
            roles=[_NUMERIC_SUBJECT("站点观测值字段")],
            obligations=[
                obl("station_min_samples", "precondition",
                    precondition="min_numeric_samples:8",
                    code="STATION_INSUFFICIENT_SAMPLES",
                    desc="站点过少的插值面不可靠。", action="degrade_with_disclosure"),
                obl("station_timeslice_alignment", "disclosure",
                    code="STATION_TIMESLICE_UNALIGNED",
                    desc="不同时刻观测混插必须披露时相不一致风险。"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("STATION_INSUFFICIENT_SAMPLES", frm="station_surface", to="station_points",
                          downgrade="degraded",
                          disclosure="站点不足：不出插值面，仅呈现站点分布。")],
        ),
    ),
    CartographyRecipe(
        id="air_quality_surface",
        name="空气质量插值面",
        description="空气质量（PM2.5/PM10/AQI）站点插值：数值字段 + 时间切片义务，超标阈值分级。",
        intent_tasks=["raster_distribution"],
        intent_cartography=["raster_surface", "administrative_choropleth"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "spatial_interpolation", "point_profile", "zonal_statistics"],
        optional_analysis=["admin_boundary_query", "admin_aggregation"],
        primary_cartography="raster_surface",
        secondary_cartography=["administrative_aggregation"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=45,
        schema_version=2,
        workflow=wf(
            "environment", "air_quality_surface",
            zh=["空气质量", "pm2.5", "pm10", "aqi", "污染分布"],
            en=["air quality", "pm25 surface", "aqi map"],
            roles=[_NUMERIC_SUBJECT("污染物浓度字段")],
            obligations=[
                obl("aqi_min_samples", "precondition",
                    precondition="min_numeric_samples:8",
                    code="AQI_INSUFFICIENT_STATIONS",
                    desc="监测站点过少，插值面不可靠。", action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("AQI_INSUFFICIENT_STATIONS", frm="aqi_surface", to="station_points",
                          downgrade="degraded",
                          disclosure="站点不足：仅呈现监测点读数，不做面域插值。")],
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
