"""领域包：Natural Resources（自然资源 / 国土）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CHART,
    MAP_COMPONENTS_STATS,
    boundary_role,
    fb,
    obl,
    role,
    standard_completion,
    subject_role,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_RS_RASTER_SUBJECT = subject_role(capability="raster_source",
                                  artifacts=("raster_surface",), geometry=("raster",))

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="cultivated_land_distribution",
        name="耕地分布清查",
        description="耕地分布与面积清查（地类图斑/分类栅格 + 行政区台账）：地类口径披露。",
        intent_tasks=["distribution_overview", "administrative_statistic", "raster_distribution"],
        intent_cartography=["categorical_thematic", "administrative_choropleth", "raster_surface"],
        preferred_analysis=["raster_source", "raster_reclassify", "zonal_statistics",
                            "admin_boundary_query", "admin_aggregation", "category_breakdown"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["raster_surface"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="admin units unavailable", reason_code="NEEDS_ADMIN_UNITS",
                                  use="categorical_raster")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=45,
        schema_version=2,
        workflow=wf(
            "natural_resources", "cultivated_land",
            zh=["耕地", "基本农田", "耕地分布", "耕地面积"],
            en=["cultivated land", "farmland distribution"],
            roles=[_RS_RASTER_SUBJECT, boundary_role()],
            obligations=[
                obl("landclass_semantics", "disclosure",
                    code="LANDCLASS_SEMANTICS",
                    desc="地类口径（调查分类/自动分类）与数据年代必须披露。"),
            ],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="forest_orchard_inventory",
        name="林园地资源清查",
        description="林地/园地分布与面积清查（指数辅助 + 行政区台账）。",
        intent_tasks=["distribution_overview", "administrative_statistic", "vegetation_index"],
        intent_cartography=["categorical_thematic", "administrative_choropleth", "raster_surface"],
        preferred_analysis=["raster_source", "ndvi", "spectral_index", "raster_reclassify",
                            "zonal_statistics", "admin_boundary_query", "admin_aggregation"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["raster_surface"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "natural_resources", "forest_inventory",
            zh=["林地", "园地", "森林分布", "果园分布"],
            en=["forest inventory", "orchard distribution"],
            roles=[_RS_RASTER_SUBJECT, boundary_role()],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="landcover_area_accounting",
        name="地类面积台账",
        description="地类面积台账（行政区 × 地类面积/占比矩阵）：面积口径与分辨率披露。",
        intent_tasks=["administrative_statistic", "raster_distribution"],
        intent_cartography=["administrative_choropleth", "categorical_thematic"],
        preferred_analysis=["raster_source", "raster_reclassify", "zonal_statistics",
                            "admin_boundary_query", "admin_aggregation", "rate_aggregation"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["categorical_thematic"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=45,
        schema_version=2,
        workflow=wf(
            "natural_resources", "area_accounting",
            zh=["面积台账", "地类面积", "国土台账", "面积统计"],
            en=["area accounting", "land area stats"],
            roles=[_RS_RASTER_SUBJECT, boundary_role()],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="water_body_inventory",
        name="水域资源清查",
        description="河湖水域分布与面积清查（水体指数/地类）：时相水位语义披露。",
        intent_tasks=["distribution_overview", "vegetation_index", "administrative_statistic"],
        intent_cartography=["categorical_thematic", "administrative_choropleth", "raster_surface"],
        preferred_analysis=["raster_source", "spectral_index", "raster_reclassify", "zonal_statistics",
                            "admin_boundary_query", "admin_aggregation"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["raster_surface"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "natural_resources", "water_inventory",
            zh=["水域", "湖泊分布", "河流水面", "湿地分布"],
            en=["water body inventory", "lake distribution"],
            roles=[_RS_RASTER_SUBJECT, boundary_role()],
            obligations=[
                obl("water_season_semantics", "disclosure",
                    code="WATER_SEASON_SEMANTICS",
                    desc="水域面积受水位季节影响，影像时相必须披露。"),
            ],
            completion=standard_completion(uncertainty=True),
        ),
    ),
    CartographyRecipe(
        id="resource_change_detection",
        name="资源变化监测",
        description="自然资源两期变化监测（占用/恢复图斑 + 台账）：配准与口径义务。",
        intent_tasks=["change_detection", "administrative_statistic"],
        intent_cartography=["administrative_choropleth", "raster_surface"],
        preferred_analysis=["raster_source", "raster_change_detection", "zonal_statistics",
                            "admin_boundary_query", "admin_aggregation", "category_breakdown"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["raster_surface"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "natural_resources", "resource_change",
            zh=["耕地占用", "资源变化", "林地变化", "占补平衡"],
            en=["land resource change"],
            roles=[
                role("baseline", capability="raster_source", artifacts=("raster_surface",),
                     geometry=("raster",), policy="degrade",
                     disclosure="缺少基期影像：无法做变化监测。"),
                role("target_time", capability="raster_source", artifacts=("raster_surface",),
                     geometry=("raster",), policy="degrade",
                     disclosure="缺少目标期影像：无法做变化监测。"),
                boundary_role(),
            ],
            obligations=[
                obl("resource_change_dual_date", "temporal",
                    code="CHANGE_DUAL_DATE_REQUIRED",
                    desc="变化监测需要两期数据。", action="degrade_with_disclosure"),
                obl("resource_change_registration", "transformation",
                    code="CHANGE_REGISTRATION_REQUIRED",
                    desc="两期需配准与口径一致。", action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("CHANGE_DUAL_DATE_REQUIRED", frm="change_map", to="single_date_view",
                          downgrade="degraded",
                          disclosure="两期数据不全：仅呈现单期地类。")],
        ),
    ),
    CartographyRecipe(
        id="grassland_condition_index",
        name="草地状况评价",
        description="草地覆盖状况/退化趋势评价（植被指数代理）：指数代理语义披露。",
        intent_tasks=["vegetation_index", "temporal_trend"],
        intent_cartography=["raster_surface", "administrative_choropleth"],
        preferred_analysis=["raster_source", "ndvi", "spectral_index", "temporal_trend",
                            "zonal_statistics", "admin_boundary_query"],
        primary_cartography="raster_surface",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_STATS,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=48,
        schema_version=2,
        workflow=wf(
            "natural_resources", "grassland_condition",
            zh=["草地", "草场状况", "草原退化"],
            en=["grassland condition", "rangeland"],
            roles=[_RS_RASTER_SUBJECT, boundary_role(required=False)],
            obligations=[
                obl("grass_ndvi_proxy", "disclosure",
                    code="VEGETATION_INDEX_PROXY_SEMANTICS",
                    desc="植被指数是草地状况的遥感代理，非实地调查结论。"),
            ],
            completion=standard_completion(uncertainty=True),
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
