"""领域包：Network（网络路径 / OD）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_BASE,
    MAP_COMPONENTS_CHART,
    fb,
    obl,
    role,
    standard_completion,
    subject_role,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_NETWORK_ROLE = role(
    "network", capability="poi_query",
    artifacts=("network_graph", "line_feature_set"), geometry=("line", "network"),
    policy="degrade",
    disclosure="缺少路网数据：欧氏距离仅为代理，不得表述为路网路径。",
)

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="shortest_path_routing",
        name="最短路径规划",
        description="起终点最短路径（路网）：断网降级欧氏代理必须披露 unreachable 与 snap 质量。",
        intent_tasks=["network_route", "proximity_analysis"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "shortest_path", "point_profile"],
        optional_analysis=["external_route_planning"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=[RecipeFallback(when="network unavailable", reason_code="NETWORK_DISCONNECTED",
                                  use="euclidean_proxy")],
        export_profile={"formats": ["png"]},
        priority=44,
        schema_version=2,
        workflow=wf(
            "network", "shortest_path",
            zh=["最短路径", "最短路线", "路径规划", "路线规划", "怎么走", "导航"],
            en=["shortest path", "route planning"],
            roles=[subject_role(), _NETWORK_ROLE],
            obligations=[
                obl("route_snap_quality", "disclosure",
                    code="ROUTE_SNAP_QUALITY",
                    desc="起终点吸附（snap）质量影响路径结果，偏远点须披露。"),
            ],
            completion=standard_completion(),
            fallbacks=[fb("NETWORK_DISCONNECTED", frm="network_path", to="euclidean_line",
                          downgrade="proxy",
                          disclosure="路网不可用：欧氏直线仅为空间代理，非实际可行驶路线。")],
        ),
    ),
    CartographyRecipe(
        id="closest_facility_assignment",
        name="最近设施分配",
        description="需求点到最近设施的路网分配（医院/消防等）：断网降级欧氏最近并披露。",
        intent_tasks=["network_route", "accessibility_analysis"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "closest_facility", "point_profile"],
        optional_analysis=["admin_boundary_query", "admin_aggregation"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="network unavailable", reason_code="NETWORK_DISCONNECTED",
                                  use="euclidean_proxy")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "network", "closest_facility",
            zh=["最近的医院", "最近设施", "就近分配"],
            en=["closest facility", "nearest allocation"],
            roles=[subject_role(), _NETWORK_ROLE],
            completion=standard_completion(),
            fallbacks=[fb("NETWORK_DISCONNECTED", frm="network_assignment", to="euclidean_assignment",
                          downgrade="proxy",
                          disclosure="路网不可用：按直线最近分配（代理，非实际到达路径）。")],
        ),
    ),
    CartographyRecipe(
        id="od_matrix_analysis",
        name="OD 矩阵分析",
        description="起讫点（OD）矩阵计算与强度分级：网络角色 + 断网降级欧氏披露。",
        intent_tasks=["mobility_flow", "network_route"],
        intent_cartography=["flow_od_arc", "point_overlay"],
        preferred_analysis=["poi_query", "od_matrix", "point_profile"],
        optional_analysis=["od_flow_mapping"],
        primary_cartography="flow_od_arc",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "network", "od_matrix",
            zh=["od矩阵", "起讫点", "通勤成本矩阵"],
            en=["od matrix", "origin destination"],
            roles=[subject_role(), _NETWORK_ROLE],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("NETWORK_DISCONNECTED", frm="network_od_matrix", to="euclidean_od_matrix",
                          downgrade="proxy",
                          disclosure="路网不可用：OD 成本按欧氏距离估计（代理）。")],
        ),
    ),
    CartographyRecipe(
        id="od_corridor_mapping",
        name="OD 走廊图",
        description="OD 流向走廊可视化（弧线/线宽分级）：流量字段义务。",
        intent_tasks=["mobility_flow"],
        intent_cartography=["flow_od_arc", "point_overlay"],
        preferred_analysis=["poi_query", "od_flow_mapping", "od_matrix", "point_profile"],
        primary_cartography="flow_od_arc",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png"]},
        priority=45,
        schema_version=2,
        workflow=wf(
            "network", "od_corridor",
            zh=["通勤走廊", "流向图", "流量分布", "od线"],
            en=["od flows", "commuting corridors"],
            roles=[subject_role(),
                   role("measure", capability="od_flow_mapping",
                        artifacts=("od_table",), geometry=("table",), policy="degrade",
                        disclosure="缺少流量字段：仅呈现连线，不做强度分级。")],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="route_optimization_tour",
        name="多点配送路径优化",
        description="多点访问顺序优化（TSP 式配送/巡查路线）：站点数守卫与近似性披露。",
        intent_tasks=["network_route", "site_selection"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "route_optimization", "point_profile"],
        optional_analysis=["shortest_path"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=[],
        export_profile={"formats": ["png"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "network", "route_optimization",
            zh=["配送路线", "多点巡查", "拜访顺序", "tsp"],
            en=["route optimization", "delivery tour"],
            roles=[subject_role(), _NETWORK_ROLE],
            obligations=[
                obl("tour_approximation_disclosure", "disclosure",
                    code="TOUR_APPROXIMATION_DISCLOSURE",
                    desc="大规模多点优化为近似解，需披露求解策略。"),
            ],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="transit_accessibility_workflow",
        name="公交可达分析",
        description="公交/轨道线路可达性（站点覆盖+换乘）：时刻表口径披露。",
        intent_tasks=["accessibility_analysis", "network_route"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "transit_routing", "service_area", "point_profile"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=[],
        export_profile={"formats": ["png"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "network", "transit_accessibility",
            zh=["公交可达", "地铁通达", "换乘便利", "公共交通"],
            en=["transit accessibility", "public transport"],
            roles=[subject_role(), _NETWORK_ROLE],
            obligations=[
                obl("transit_schedule_semantics", "disclosure",
                    code="TRANSIT_SCHEDULE_SEMANTICS",
                    desc="公交可达性依赖时刻表/发车频率口径，需披露数据时点。"),
            ],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="traffic_status_overview",
        name="路况状态概览",
        description="实时/时段路况等级可视化：数据时点语义强披露（非通行能力分析）。",
        intent_tasks=["network_route", "simple_view", "mobility_flow"],
        intent_cartography=["categorical_thematic", "point_overlay"],
        preferred_analysis=["traffic_status", "poi_query", "point_profile"],
        primary_cartography="categorical_thematic",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=[],
        export_profile={"formats": ["png"]},
        priority=47,
        schema_version=2,
        workflow=wf(
            "network", "traffic_status",
            zh=["路况", "拥堵", "实时交通"],
            en=["traffic status", "congestion"],
            roles=[_NETWORK_ROLE],
            obligations=[
                obl("traffic_time_semantics", "disclosure",
                    code="TRAFFIC_TIME_SEMANTICS",
                    desc="路况为观测时点状态，不得推断为长期通行能力。"),
            ],
            completion=standard_completion(),
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
