"""领域包：Point Pattern（点格局 / 点位形态）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    fb,
    min_points_rule,
    obl,
    point_fallback,
    role,
    standard_completion,
    subject_role,
    wf,
    MAP_COMPONENTS_BASE,
    MAP_COMPONENTS_CHART,
    auto_fallback,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="point_pattern_quadrat",
        name="点格局检验（象限法）",
        description="象限计数点格局检验：均匀/随机/聚集的统计判断，样本量义务前置。",
        intent_tasks=["concentration_analysis", "spatial_autocorrelation"],
        intent_cartography=["point_overlay", "hotspot_overlay"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "point_pattern_analysis", "point_profile"],
        primary_cartography="hotspot_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"], "chart": True},
        priority=47,
        schema_version=2,
        workflow=wf(
            "point_pattern", "quadrat_analysis",
            zh=["点格局", "象限分析", "分布检验"],
            en=["point pattern", "quadrat analysis"],
            roles=[subject_role()],
            obligations=[obl("quadrat_min_points", "precondition",
                             precondition="point_support_required",
                             code="QUADRAT_INSUFFICIENT_POINTS",
                             desc="点格局检验需要足够点数。", action="degrade_with_disclosure")],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("QUADRAT_INSUFFICIENT_POINTS", frm="point_pattern_test", to="visual_density",
                          downgrade="degraded",
                          disclosure="点数不足：不做出格局检验结论，仅描述性展示。")],
        ),
    ),
    CartographyRecipe(
        id="point_pattern_distance",
        name="最近邻距离格局",
        description="最近邻指数（NNI）式点格局刻画：平均最近邻距离与随机模式对比。",
        intent_tasks=["concentration_analysis"],
        intent_cartography=["point_overlay", "hotspot_overlay"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap")],
        preferred_analysis=["poi_query", "point_pattern_analysis", "point_profile"],
        primary_cartography="point_overlay",
        secondary_cartography=["hotspot_overlay"],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png"]},
        priority=48,
        schema_version=2,
        workflow=wf(
            "point_pattern", "distance_analysis",
            zh=["最近邻", "点间距离", "nni"],
            en=["nearest neighbor index", "point distance"],
            roles=[subject_role()],
            obligations=[obl("nni_projected_crs", "precondition",
                             precondition="projected_crs_required",
                             code="NNI_PROJECTED_CRS_REQUIRED",
                             desc="距离度量需要投影坐标系（米制）。",
                             action="degrade_with_disclosure")],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("NNI_PROJECTED_CRS_REQUIRED", frm="nni_distance_stats", to="visual_density",
                          downgrade="degraded",
                          disclosure="坐标为经纬度角度单位：距离级格局分析不可靠，降级描述性展示。")],
        ),
    ),
    CartographyRecipe(
        id="voronoi_service_coverage",
        name="Voronoi 服务域划分",
        description="以设施点为种子的 Voronoi 服务域划分：最近设施假设下的覆盖形态（非路网可达）。",
        intent_tasks=["accessibility_analysis", "proximity_analysis"],
        intent_cartography=["proximity_overlay", "categorical_thematic"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap", min_points=3, code="VORONOI_INSUFFICIENT_SEEDS")],
        preferred_analysis=["poi_query", "voronoi_tessellation", "point_profile"],
        optional_analysis=["admin_boundary_query", "admin_aggregation"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["categorical_thematic"],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=[RecipeFallback(when="seeds < 3", reason_code="VORONOI_INSUFFICIENT_SEEDS", use="point_distribution")],
        export_profile={"formats": ["png"]},
        priority=47,
        schema_version=2,
        workflow=wf(
            "point_pattern", "voronoi_coverage",
            zh=["voronoi", "泰森多边形", "服务域", "势力范围"],
            en=["voronoi", "thiessen polygon"],
            roles=[subject_role()],
            obligations=[obl("voronoi_euclidean_disclosure", "disclosure",
                             code="VORONOI_EUCLIDIAN_PROXY",
                             desc="Voronoi 是欧氏最近设施代理，不得表述为路网可达性。")],
            completion=standard_completion(),
            fallbacks=[fb("VORONOI_INSUFFICIENT_SEEDS", frm="voronoi_zones", to="point_distribution",
                          downgrade="degraded",
                          disclosure="设施点过少：无法划分服务域，仅出点图。")],
        ),
    ),
    CartographyRecipe(
        id="spatiotemporal_emergence_tracking",
        name="事件时空涌现追踪",
        description="带时序的事件点时空聚类追踪（如投诉/案件涌现）：时间字段义务。",
        intent_tasks=["concentration_analysis", "temporal_trend"],
        intent_cartography=["hotspot_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "spatiotemporal_clustering", "temporal_profile", "point_profile"],
        primary_cartography="hotspot_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        fallback_links=auto_fallback(),  # ADR-0151 P7：通用兜底链（auto_generated）
        export_profile={"formats": ["png"], "chart": True},
        priority=48,
        schema_version=2,
        workflow=wf(
            "point_pattern", "emergence_tracking",
            zh=["事件涌现", "投诉聚集", "案件时空", "涌现追踪"],
            en=["event emergence", "spatiotemporal events"],
            roles=[subject_role(),
                   role("target_time", capability="temporal_profile",
                        artifacts=("stats_table",), policy="degrade",
                        disclosure="缺少时间字段：退化为纯空间聚集展示。")],
            obligations=[obl("emergence_temporal_field", "temporal",
                             code="EMERGENCE_TEMPORAL_FIELD_REQUIRED",
                             desc="涌现追踪需要时间字段。", action="degrade_with_disclosure")],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("DATA_ROLE_MISSING_TARGET_TIME", frm="emergence_tracking", to="visual_density",
                          downgrade="degraded",
                          disclosure="缺少时间维度：仅呈现空间聚集，不称演化。")],
        ),
    ),
    CartographyRecipe(
        id="convex_hull_extent",
        name="分布范围圈定",
        description="凸包圈定主体分布范围（活动范围/服务足迹的描述性边界）。",
        intent_tasks=["distribution_overview", "proximity_analysis"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap", min_points=3, code="HULL_INSUFFICIENT_POINTS")],
        preferred_analysis=["poi_query", "convex_hull", "point_profile"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_BASE,
        fallbacks=[RecipeFallback(when="points < 3", reason_code="HULL_INSUFFICIENT_POINTS", use="point_distribution")],
        export_profile={"formats": ["png"]},
        priority=49,
        schema_version=2,
        workflow=wf(
            "point_pattern", "extent_delimitation",
            zh=["分布范围", "活动范围", "覆盖圈", "足迹"],
            en=["convex hull", "activity range"],
            roles=[subject_role()],
            completion=standard_completion(),
            fallbacks=[fb("HULL_INSUFFICIENT_POINTS", frm="convex_hull_zone", to="point_distribution",
                          downgrade="degraded",
                          disclosure="点数过少：无法圈定范围，仅出点图。")],
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
