"""领域包：Public Health（公共卫生）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CHART,
    boundary_role,
    denominator_role,
    fb,
    min_points_rule,
    obl,
    point_fallback,
    role,
    standard_completion,
    subject_role,
    wf,
    auto_fallback,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="clinic_coverage_analysis",
        name="基层医疗覆盖分析",
        description="基层医疗机构（社区卫生服务中心/诊所）服务覆盖分析：服务圈口径披露。",
        intent_tasks=["accessibility_analysis", "distribution_overview"],
        intent_cartography=["proximity_overlay", "point_overlay", "administrative_choropleth"],
        preferred_analysis=["poi_query", "service_area", "admin_boundary_query", "admin_aggregation",
                            "rate_aggregation"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=point_fallback(),
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "public_health", "clinic_coverage",
            zh=["社区卫生服务", "诊所覆盖", "基层医疗", "卫生站覆盖"],
            en=["clinic coverage", "primary care access"],
            roles=[subject_role(), boundary_role(),
                   role("population", acquisition="data_fabric", required=False)],
            obligations=[
                obl("clinic_service_radius_semantics", "disclosure",
                    code="CLINIC_RADIUS_SEMANTICS",
                    desc="基层医疗服务圈半径/时长依据必须披露（规范 15 分钟圈等）。"),
            ],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="epidemic_density_monitor",
        name="疫情密度监测",
        description="病例/事件点位密度监测（描述性 + 时序）：隐私聚合与显著性守卫。",
        intent_tasks=["concentration_analysis", "temporal_trend"],
        intent_cartography=["density_overview", "hotspot_overlay", "point_overlay"],
        required_geometry=["Point", "MultiPoint"],
        eligibility=[min_points_rule("visual_heatmap", min_points=20,
                                     code="PRIVACY_AGGREGATION_MIN_POINTS")],
        preferred_analysis=["poi_query", "kde_density", "grid_binning", "temporal_profile",
                            "point_profile"],
        primary_cartography="visual_heatmap",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="point_count < 20", reason_code="PRIVACY_AGGREGATION_MIN_POINTS",
                                  use="aggregate_grid")],
        export_profile={"formats": ["png"], "chart": True},
        priority=47,
        schema_version=2,
        workflow=wf(
            "public_health", "epidemic_monitor",
            zh=["病例分布", "疫情监测", "传染病密度"],
            en=["epidemic monitoring", "case density"],
            roles=[subject_role(),
                   role("target_time", capability="temporal_profile",
                        artifacts=("stats_table",), required=False)],
            obligations=[
                obl("epidemic_privacy_aggregation", "disclosure",
                    code="EPIDEMIC_PRIVACY_AGGREGATION",
                    desc="病例点位必须聚合展示（格网/行政区），禁止个体级定位披露。"),
                obl("epidemic_density_not_significance", "disclosure",
                    code="DENSITY_VISUAL_NOT_SIGNIFICANCE",
                    desc="密度图为描述性监测，不构成统计学聚集结论。"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("PRIVACY_AGGREGATION_MIN_POINTS", frm="point_level_map", to="aggregate_grid",
                          downgrade="degraded",
                          disclosure="点位过少：切换到聚合网格展示（隐私保护），不展示个体点位。")],
        ),
    ),
    CartographyRecipe(
        id="health_resource_per_capita",
        name="医疗资源人均画像",
        description="行政区医疗资源人均配置（床位/人员/机构 per 万人）：分母义务。",
        intent_tasks=["spatial_equity", "administrative_statistic"],
        intent_cartography=["administrative_choropleth"],
        preferred_analysis=["poi_query", "admin_boundary_query", "admin_aggregation",
                            "rate_aggregation", "category_breakdown"],
        primary_cartography="administrative_choropleth",
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="denominator missing", reason_code="MISSING_DENOMINATOR",
                                  use="count_only")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "public_health", "per_capita_profile",
            zh=["每万人", "千人均", "医疗资源人均", "床位人均"],
            en=["health resources per capita"],
            roles=[subject_role(), boundary_role(), denominator_role()],
            obligations=[
                obl("health_per_capita_denominator", "denominator",
                    code="PER_CAPITA_DENOMINATOR_REQUIRED",
                    desc="人均资源指标必须有人口分母；缺失禁止 per-capita 表述。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(),
            fallbacks=[fb("DATA_ROLE_MISSING_DENOMINATOR", frm="per_capita_map", to="count_map",
                          downgrade="degraded",
                          disclosure="缺少人口分母：仅呈现资源总量分布，不称人均。")],
        ),
    ),
    CartographyRecipe(
        id="hospital_service_area_stats",
        name="医院服务区统计",
        description="医院服务区（车程圈）覆盖与重叠统计：圈层口径与重叠语义披露。",
        intent_tasks=["accessibility_analysis", "administrative_statistic"],
        intent_cartography=["proximity_overlay", "administrative_choropleth"],
        preferred_analysis=["poi_query", "service_area", "admin_boundary_query", "admin_aggregation",
                            "geometry_overlay", "point_profile"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        fallback_links=auto_fallback(),  # ADR-0151 P7：通用兜底链（auto_generated）
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=47,
        schema_version=2,
        workflow=wf(
            "public_health", "hospital_service_area",
            zh=["医院服务范围", "服务圈统计", "就医圈"],
            en=["hospital service area"],
            roles=[subject_role(), boundary_role()],
            completion=standard_completion(),
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
