"""领域包：Remote Sensing（光学遥感 / 指数 / 时序）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CONTINUOUS,
    MAP_COMPONENTS_STATS,
    boundary_role,
    fb,
    obl,
    role,
    standard_completion,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_RS_SUBJECT = lambda note="": role(  # noqa: E731
    "subject", capability="raster_source",
    artifacts=("raster_surface", "remote_sensing_index"), geometry=("raster",),
    note=note,
)
_BAND_SEMANTICS = obl(
    "rs_band_semantics_required", "precondition",
    precondition="band_semantics_required",
    code="RS_BAND_SEMANTICS_REQUIRED",
    desc="光谱指数计算需要波段语义（红/近红外等）可确认；不可确认时禁止指数结论。",
    action="degrade_with_disclosure",
)
#: recipe 级回退表
_BAND_RF = RecipeFallback(when="band semantics unconfirmed",
                          reason_code="RS_BAND_SEMANTICS_REQUIRED", use="raster_view")
#: workflow 级语义回退策略
_BAND_FALLBACK = fb(
    "RS_BAND_SEMANTICS_REQUIRED", frm="spectral_index", to="raster_view",
    downgrade="degraded",
    disclosure="波段语义不可确认：仅呈现原始波段合成，不计算光谱指数。",
)

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="ndvi_vegetation_monitor",
        name="NDVI 植被监测",
        description="NDVI 植被指数计算与分级制图：波段语义义务 + 取值范围校验披露。",
        intent_tasks=["vegetation_index", "raster_distribution"],
        intent_cartography=["raster_surface", "administrative_choropleth"],
        preferred_analysis=["raster_source", "ndvi", "spectral_index", "zonal_statistics"],
        optional_analysis=["admin_boundary_query", "admin_aggregation"],
        primary_cartography="raster_surface",
        secondary_cartography=["administrative_aggregation"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=[_BAND_RF],
        export_profile={"formats": ["png"]},
        priority=43,
        schema_version=2,
        workflow=wf(
            "remote_sensing", "ndvi_monitor",
            zh=["ndvi", "植被覆盖", "绿度", "植被指数"],
            en=["ndvi", "vegetation index"],
            roles=[_RS_SUBJECT("多波段光学影像")],
            obligations=[_BAND_SEMANTICS],
            fallbacks=[_BAND_FALLBACK],
            completion=standard_completion(uncertainty=True),
            recompute=["data", "algorithm", "parameter", "output"],
        ),
    ),
    CartographyRecipe(
        id="ndwi_water_index",
        name="NDWI 水体指数",
        description="NDWI 水体提取与面积统计：波段语义义务 + 阈值敏感性披露。",
        intent_tasks=["vegetation_index", "raster_distribution"],
        intent_cartography=["raster_surface"],
        preferred_analysis=["raster_source", "spectral_index", "band_math", "zonal_statistics"],
        primary_cartography="raster_surface",
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=[_BAND_RF],
        export_profile={"formats": ["png"]},
        priority=45,
        schema_version=2,
        workflow=wf(
            "remote_sensing", "water_index",
            zh=["ndwi", "水体提取", "水面识别"],
            en=["ndwi", "water index"],
            roles=[_RS_SUBJECT()],
            obligations=[
                _BAND_SEMANTICS,
                obl("water_index_threshold", "disclosure",
                    code="WATER_INDEX_THRESHOLD_SENSITIVITY",
                    desc="水体/非水体分割阈值影响面积，需披露阈值依据。"),
            ],
            fallbacks=[_BAND_FALLBACK],
            completion=standard_completion(uncertainty=True),
        ),
    ),
    CartographyRecipe(
        id="nbr_burn_severity",
        name="NBR 火烧迹地指数",
        description="NBR/dNBR 火烧严重度评价：基期+目标期双景义务，波段语义必须。",
        intent_tasks=["vegetation_index", "change_detection"],
        intent_cartography=["raster_surface"],
        preferred_analysis=["raster_source", "spectral_index", "band_math", "raster_change_detection"],
        primary_cartography="raster_surface",
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=[_BAND_RF],
        export_profile={"formats": ["png"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "remote_sensing", "burn_severity",
            zh=["nbr", "火烧迹地", "过火面积", "燃烧严重度"],
            en=["nbr", "burn severity", "dnbr"],
            roles=[_RS_SUBJECT("过火前后双景")],
            obligations=[
                _BAND_SEMANTICS,
                obl("burn_baseline_required", "temporal",
                    code="BURN_BASELINE_SCENE_REQUIRED",
                    desc="dNBR 需要火前基期影像；缺失时仅能出单期 NBR。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("BURN_BASELINE_SCENE_REQUIRED", frm="dnbr_change", to="nbr_single_date",
                          downgrade="degraded",
                          disclosure="缺少火前基期：仅呈现单期 NBR，不做严重度变化。")],
        ),
    ),
    CartographyRecipe(
        id="landcover_categorical_map",
        name="地表覆盖分类图",
        description="土地利用/地表覆盖分类专题：类别语义与图例义务，类别面积台账。",
        intent_tasks=["raster_distribution", "categorical_distribution"],
        intent_cartography=["raster_surface", "categorical_thematic", "administrative_choropleth"],
        preferred_analysis=["raster_source", "raster_reclassify", "zonal_statistics",
                            "admin_boundary_query", "admin_aggregation"],
        primary_cartography="raster_surface",
        secondary_cartography=["administrative_aggregation"],
        default_components=MAP_COMPONENTS_STATS,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "remote_sensing", "landcover_map",
            zh=["土地利用", "地表覆盖", "地类图", "land cover"],
            en=["land cover", "land use map"],
            roles=[_RS_SUBJECT("分类结果栅格或可分类影像")],
            completion=standard_completion(),
            evidence=["classification_legend_semantics"],
        ),
    ),
    CartographyRecipe(
        id="optical_bitemporal_change",
        name="双时相光学变化检测",
        description="两期影像变化检测（差值/变化向量）：配准与辐射一致性义务。",
        intent_tasks=["change_detection"],
        intent_cartography=["raster_surface", "administrative_choropleth"],
        preferred_analysis=["raster_source", "raster_change_detection", "zonal_statistics"],
        optional_analysis=["admin_boundary_query", "admin_aggregation"],
        primary_cartography="raster_surface",
        secondary_cartography=["administrative_aggregation"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=[],
        export_profile={"formats": ["png"]},
        priority=43,
        schema_version=2,
        workflow=wf(
            "remote_sensing", "bitemporal_change",
            zh=["影像对比", "两期影像", "变化图斑"],
            en=["image change detection", "bitemporal"],
            roles=[
                role("baseline", capability="raster_source", artifacts=("raster_surface",),
                     geometry=("raster",)),
                role("target_time", capability="raster_source", artifacts=("raster_surface",),
                     geometry=("raster",)),
            ],
            obligations=[
                obl("change_registration_required", "transformation",
                    code="CHANGE_REGISTRATION_REQUIRED",
                    desc="双时相比较前需要几何配准与辐射一致性确认。", action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            disclosures=["CHANGE_REGISTRATION_REQUIRED"],
        ),
    ),
    CartographyRecipe(
        id="index_time_series_trend",
        name="指数时序趋势",
        description="光谱指数多期时序趋势（如 NDVI 年际趋势）：观测期数义务（≥4 期）。",
        intent_tasks=["temporal_trend", "vegetation_index"],
        intent_cartography=["raster_surface", "point_overlay"],
        preferred_analysis=["raster_source", "spectral_index", "temporal_trend", "temporal_profile"],
        primary_cartography="raster_surface",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=45,
        schema_version=2,
        workflow=wf(
            "remote_sensing", "index_timeseries",
            zh=["指数趋势", "植被变化趋势", "年际指数"],
            en=["index time series", "ndvi trend"],
            roles=[_RS_SUBJECT("多期影像栈")],
            obligations=[
                obl("trend_min_observations", "precondition",
                    precondition="min_temporal_observations:4",
                    code="TREND_INSUFFICIENT_OBSERVATIONS",
                    desc="趋势分析需要多期观测；两期不得称趋势。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("TREND_INSUFFICIENT_OBSERVATIONS", frm="trend_surface", to="bitemporal_difference",
                          downgrade="degraded",
                          disclosure="期数不足：仅做两期差值，不称长期趋势。")],
        ),
    ),
    CartographyRecipe(
        id="rs_scene_inventory",
        name="影像数据清单",
        description="区域影像/栅格数据资产清单（覆盖范围、时相、波段）：数据画像义务。",
        intent_tasks=["raster_distribution", "distribution_overview"],
        intent_cartography=["raster_surface", "point_overlay"],
        preferred_analysis=["raster_source", "point_profile"],
        primary_cartography="raster_surface",
        default_components=MAP_COMPONENTS_STATS,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"]},
        priority=48,
        schema_version=2,
        workflow=wf(
            "remote_sensing", "scene_inventory",
            zh=["影像清单", "数据资产", "影像覆盖"],
            en=["imagery inventory", "scene catalog"],
            roles=[_RS_SUBJECT()],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="builtup_index_screening",
        name="不透水面/建成区指数筛查",
        description="建成区/不透水面指数（NDBI 类）筛查：波段语义义务 + 与绿度指数交叉验证建议。",
        intent_tasks=["vegetation_index", "raster_distribution", "suitability_assessment"],
        intent_cartography=["raster_surface"],
        preferred_analysis=["raster_source", "band_math", "spectral_index", "raster_reclassify"],
        primary_cartography="raster_surface",
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=[_BAND_RF],
        export_profile={"formats": ["png"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "remote_sensing", "builtup_index",
            zh=["不透水面", "建成区", "ndbi", "硬化地面"],
            en=["built-up index", "impervious surface"],
            roles=[_RS_SUBJECT()],
            obligations=[_BAND_SEMANTICS],
            fallbacks=[_BAND_FALLBACK],
            completion=standard_completion(uncertainty=True),
        ),
    ),
    CartographyRecipe(
        id="zonal_rs_index_report",
        name="分区遥感指数报表",
        description="行政区/格网尺度的遥感指数统计报表（均值/极值 + 排名）。",
        intent_tasks=["vegetation_index", "administrative_statistic"],
        intent_cartography=["administrative_choropleth", "raster_surface"],
        preferred_analysis=["raster_source", "ndvi", "spectral_index", "zonal_statistics",
                            "admin_boundary_query", "admin_aggregation"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["raster_surface"],
        default_components=MAP_COMPONENTS_STATS,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "remote_sensing", "zonal_index_report",
            zh=["各区植被指数", "分区均值", "指数报表"],
            en=["zonal index report"],
            roles=[_RS_SUBJECT(), boundary_role()],
            completion=standard_completion(),
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
