"""领域包：Risk（风险评估）。

红线：hazard ≠ risk。只有 hazard 没有受体时，产品必须自称 hazard map，
不得称 risk map（RISK_RECEPTORS_UNCONFIRMED）。
"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CHART,
    boundary_role,
    fb,
    obl,
    role,
    standard_completion,
    subject_role,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_HAZARD_ONLY_FALLBACK = fb(
    "RISK_RECEPTORS_UNCONFIRMED", frm="risk_map", to="hazard_map",
    downgrade="degraded",
    disclosure="缺少承灾体数据：产品为危险性（hazard）图而非风险（risk）图。",
    blocks=False,
)

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="landslide_risk_assessment",
        name="滑坡风险评估",
        description="滑坡易发性 × 承灾体暴露：地形因子 + 危险分区 + 受体叠加；缺受体降级易发性图。",
        intent_tasks=["risk_exposure", "terrain_analysis", "suitability_assessment"],
        intent_cartography=["raster_surface", "proximity_overlay"],
        preferred_analysis=["raster_source", "terrain_slope", "raster_reclassify", "geometry_overlay",
                            "zonal_statistics", "poi_query"],
        optional_analysis=["admin_boundary_query", "admin_aggregation"],
        primary_cartography="raster_surface",
        secondary_cartography=["proximity_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="receptors unconfirmed", reason_code="RISK_RECEPTORS_UNCONFIRMED",
                                  use="hazard_map")],
        export_profile={"formats": ["png"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "risk", "landslide_risk",
            zh=["滑坡", "地质灾害", "崩塌", "滑坡风险"],
            en=["landslide risk", "geological hazard"],
            roles=[
                role("hazard", capability="raster_source", artifacts=("raster_surface",),
                     geometry=("raster",), note="致灾因子（坡度/岩性/降雨代理）"),
                role("receptor", required=False, acquisition="data_fabric",
                     note="承灾体（居民点/道路/设施）"),
                boundary_role(),
            ],
            obligations=[
                obl("risk_receptors_confirmed", "disclosure",
                    code="RISK_RECEPTORS_UNCONFIRMED",
                    desc="缺受体时只能称易发性/危险性，不得称风险。",
                    action="degrade_with_disclosure"),
                obl("landslide_factor_disclosure", "disclosure",
                    code="LANDSLIDE_FACTOR_SEMANTICS",
                    desc="滑坡易发性因子体系（静态/动态触发）必须披露。"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[_HAZARD_ONLY_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="flood_risk_assessment",
        name="洪水风险评估",
        description="洪水淹没范围 × 受体暴露：几何淹没近似披露 + 受体义务。",
        intent_tasks=["risk_exposure", "watershed_analysis"],
        intent_cartography=["raster_surface", "proximity_overlay"],
        preferred_analysis=["raster_source", "terrain_hydrology", "raster_reclassify",
                            "geometry_overlay", "zonal_statistics", "poi_query"],
        optional_analysis=["admin_boundary_query", "admin_aggregation"],
        primary_cartography="raster_surface",
        secondary_cartography=["proximity_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="receptors unconfirmed", reason_code="RISK_RECEPTORS_UNCONFIRMED",
                                  use="hazard_map")],
        export_profile={"formats": ["png"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "risk", "flood_risk",
            zh=["洪水风险", "洪涝", "淹没风险", "内涝风险"],
            en=["flood risk"],
            roles=[
                role("hazard", capability="raster_source", artifacts=("raster_surface",),
                     geometry=("raster",)),
                role("receptor", required=False, acquisition="data_fabric"),
                boundary_role(),
            ],
            obligations=[
                obl("flood_geometric_approximation", "disclosure",
                    code="FLOOD_GEOMETRIC_APPROXIMATION",
                    desc="高程平推淹没为几何近似，非水动力模拟。"),
                obl("risk_receptors_confirmed", "disclosure",
                    code="RISK_RECEPTORS_UNCONFIRMED",
                    desc="缺受体时只能称淹没范围，不得称风险。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[_HAZARD_ONLY_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="earthquake_exposure_screening",
        name="地震暴露筛查",
        description="地震影响（烈度/断层缓冲）× 人口/建筑暴露筛查：数据可得性诚实降级。",
        intent_tasks=["risk_exposure"],
        intent_cartography=["proximity_overlay", "administrative_choropleth"],
        preferred_analysis=["geometry_buffer", "multi_ring_buffer", "geometry_overlay",
                            "admin_boundary_query", "admin_aggregation"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="receptors unconfirmed", reason_code="RISK_RECEPTORS_UNCONFIRMED",
                                  use="hazard_map")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=47,
        schema_version=2,
        workflow=wf(
            "risk", "earthquake_exposure",
            zh=["地震", "断层", "烈度", "地震暴露"],
            en=["earthquake exposure", "seismic hazard"],
            roles=[
                role("hazard", capability="geometry_buffer",
                     artifacts=("proximity_zone",), geometry=("polygon",),
                     note="断层/震中缓冲圈（烈度代理）"),
                role("receptor", required=False, acquisition="data_fabric"),
                boundary_role(),
            ],
            obligations=[
                obl("seismic_proxy_disclosure", "disclosure",
                    code="SEISMIC_PROXIMITY_PROXY",
                    desc="断层缓冲不是烈度场，仅作空间筛查代理。"),
                obl("risk_receptors_confirmed", "disclosure",
                    code="RISK_RECEPTORS_UNCONFIRMED",
                    desc="缺受体时只做危险源空间筛查。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[_HAZARD_ONLY_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="urban_fire_risk_hotspot",
        name="火险热点分析",
        description="建筑/绿地火险因子叠加与热点筛选（历史火点密度代理）。",
        intent_tasks=["risk_exposure", "concentration_analysis"],
        intent_cartography=["hotspot_overlay", "raster_surface"],
        preferred_analysis=["poi_query", "kde_density", "raster_reclassify", "geometry_overlay",
                            "getis_ord_gi_star"],
        primary_cartography="hotspot_overlay",
        secondary_cartography=["raster_surface"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png"], "chart": True},
        priority=47,
        schema_version=2,
        workflow=wf(
            "risk", "fire_risk",
            zh=["火险", "火灾风险", "消防风险", "高火险区"],
            en=["fire risk", "wildfire hotspot"],
            roles=[
                role("hazard", capability="kde_density", artifacts=("density_surface", "hotspot_result"),
                     geometry=("raster", "point"), note="历史火点密度（危险性代理）"),
                role("receptor", required=False, acquisition="data_fabric"),
            ],
            obligations=[
                obl("fire_density_is_hazard_proxy", "disclosure",
                    code="FIRE_DENSITY_IS_HAZARD_PROXY",
                    desc="历史火点密度是危险性代理，不等于未来风险概率。"),
            ],
            completion=standard_completion(uncertainty=True),
        ),
    ),
    CartographyRecipe(
        id="hazard_exposure_overlay",
        name="通用危险-暴露叠加",
        description="通用 hazard × receptor 叠加暴露评价：受体义务与降级语义显式。",
        intent_tasks=["risk_exposure"],
        intent_cartography=["proximity_overlay", "administrative_choropleth"],
        preferred_analysis=["geometry_buffer", "geometry_overlay", "spatial_join",
                            "admin_boundary_query", "admin_aggregation"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="receptors unconfirmed", reason_code="RISK_RECEPTORS_UNCONFIRMED",
                                  use="hazard_map")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=43,
        schema_version=2,
        workflow=wf(
            "risk", "hazard_exposure_overlay",
            zh=["暴露评价", "影响范围叠加", "危险源影响"],
            en=["hazard exposure", "exposure overlay"],
            roles=[
                role("hazard", capability="geometry_buffer", artifacts=("proximity_zone",),
                     geometry=("polygon",)),
                role("receptor", required=False, acquisition="data_fabric",
                     policy="degrade", disclosure="缺少受体：仅呈现危险影响区。"),
                boundary_role(),
            ],
            obligations=[
                obl("risk_receptors_confirmed", "disclosure",
                    code="RISK_RECEPTORS_UNCONFIRMED",
                    desc="无受体的叠加只是影响区刻画，不得称风险。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[_HAZARD_ONLY_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="multi_hazard_composite",
        name="多灾种复合筛查",
        description="多灾种危险区复合（取大/加权合成）：合成语义必须披露（复合≠概率相加）。",
        intent_tasks=["risk_exposure"],
        intent_cartography=["raster_surface"],
        preferred_analysis=["raster_source", "raster_reclassify", "band_math", "geometry_overlay",
                            "zonal_statistics"],
        primary_cartography="raster_surface",
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png"]},
        priority=48,
        schema_version=2,
        workflow=wf(
            "risk", "multi_hazard",
            zh=["多灾种", "复合灾害", "综合风险区"],
            en=["multi hazard", "composite hazard"],
            roles=[
                role("hazard", required=True, capability="raster_source",
                     artifacts=("raster_surface",), geometry=("raster",),
                     note="多灾种危险图层"),
                role("receptor", required=False, acquisition="data_fabric"),
            ],
            obligations=[
                obl("multi_hazard_composition_semantics", "disclosure",
                    code="MULTI_HAZARD_COMPOSITION_SEMANTICS",
                    desc="多灾种合成规则（取大/加权）必须披露，禁止概率直接相加。"),
            ],
            completion=standard_completion(uncertainty=True),
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
