"""领域包：Site Selection（选址决策）。

红线：没有显式 criteria 不得静默编造权重（SITE_SELECTION_CRITERIA_UNDECLARED）。
"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CHART,
    boundary_role,
    fb,
    obl,
    role,
    standard_completion,
    subject_role,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_CRITERIA_OBLIGATIONS = [
    obl("site_criteria_declared", "disclosure",
        code="SITE_SELECTION_CRITERIA_UNDECLARED",
        desc="选址准则未声明时不得静默编造权重；必须先向用户确认准则。",
        action="degrade_with_disclosure"),
    obl("site_weight_provenance", "disclosure",
        code="SITE_WEIGHT_PROVENANCE",
        desc="权重来源（用户指定/规范/等权默认）必须披露。"),
]
_CRITERIA_FALLBACK = fb(
    "SITE_SELECTION_CRITERIA_UNDECLARED", frm="mcda_ranking", to="constraint_screening",
    downgrade="degraded",
    disclosure="未声明准则：仅做约束排除筛选（可行区），不做加权排序结论。",
)

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="school_site_selection",
        name="学校选址评价",
        description="新学校选址：服务盲区约束 + 人口可达 + MCDA 排序；准则未声明不排序。",
        intent_tasks=["site_selection", "accessibility_analysis"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "service_area", "geometry_buffer", "mcda_evaluation",
                            "admin_boundary_query"],
        optional_analysis=["admin_aggregation"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="criteria undeclared", reason_code="SITE_SELECTION_CRITERIA_UNDECLARED",
                                  use="constraint_screening")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "site_selection", "school_site",
            zh=["学校选址", "新校址", "建学校"],
            en=["school site selection"],
            roles=[subject_role(), boundary_role(),
                   role("criteria", acquisition="user_upload", required=False,
                        note="准则因子（可达性/用地/环境）"),
                   role("constraint", acquisition="user_upload", required=False,
                        note="约束（坡度/避让/噪声）"),
                   role("population", acquisition="data_fabric", required=False,
                        note="学龄人口分布（需求侧）")],
            obligations=_CRITERIA_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_CRITERIA_FALLBACK],
            evidence=["criteria_weights_provenance"],
        ),
    ),
    CartographyRecipe(
        id="hospital_site_selection",
        name="医院选址评价",
        description="新医院选址：急救响应覆盖 + 人口需求 + MCDA；缺分母只做空间准则排序。",
        intent_tasks=["site_selection", "accessibility_analysis"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "service_area", "closest_facility", "mcda_evaluation",
                            "admin_boundary_query"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="criteria undeclared", reason_code="SITE_SELECTION_CRITERIA_UNDECLARED",
                                  use="constraint_screening")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "site_selection", "hospital_site",
            zh=["医院选址", "新院区", "建医院"],
            en=["hospital site selection"],
            roles=[subject_role(), boundary_role(),
                   role("criteria", acquisition="user_upload", required=False),
                   role("constraint", acquisition="user_upload", required=False),
                   role("population", acquisition="data_fabric", required=False)],
            obligations=_CRITERIA_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_CRITERIA_FALLBACK],
            evidence=["criteria_weights_provenance"],
        ),
    ),
    CartographyRecipe(
        id="shelter_site_selection",
        name="避难场所选址",
        description="应急避难场所选址：覆盖盲区 + 安全约束（避让灾害源）+ MCDA。",
        intent_tasks=["site_selection", "risk_exposure", "accessibility_analysis"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "geometry_buffer", "service_area", "mcda_evaluation",
                            "admin_boundary_query"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="criteria undeclared", reason_code="SITE_SELECTION_CRITERIA_UNDECLARED",
                                  use="constraint_screening")],
        export_profile={"formats": ["png", "csv"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "site_selection", "shelter_site",
            zh=["避难场所选址", "避难所布局", "应急场所选址"],
            en=["shelter site selection"],
            roles=[subject_role(), boundary_role(),
                   role("criteria", acquisition="user_upload", required=False),
                   role("constraint", acquisition="user_upload", required=False,
                        note="应避让灾害源/危险设施")],
            obligations=_CRITERIA_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_CRITERIA_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="ev_charger_site_selection",
        name="充电站选址评价",
        description="充电站/桩选址：交通流量 + 电网/用地代理准则 + MCDA。",
        intent_tasks=["site_selection"],
        intent_cartography=["proximity_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "traffic_status", "geometry_buffer", "mcda_evaluation"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="criteria undeclared", reason_code="SITE_SELECTION_CRITERIA_UNDECLARED",
                                  use="constraint_screening")],
        export_profile={"formats": ["png", "csv"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "site_selection", "ev_charger_site",
            zh=["充电站选址", "充电桩布局"],
            en=["ev charging site selection"],
            roles=[subject_role(), boundary_role(),
                   role("criteria", acquisition="user_upload", required=False),
                   role("constraint", acquisition="user_upload", required=False)],
            obligations=_CRITERIA_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_CRITERIA_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="generic_mcda_site_ranking",
        name="通用多准则选址",
        description="通用 MCDA 选址排序（WSM/TOPSIS）：准则+权重来源义务，缺准则不排序。",
        intent_tasks=["site_selection"],
        intent_cartography=["proximity_overlay"],
        preferred_analysis=["mcda_evaluation", "geometry_buffer", "proximity_buffer", "admin_boundary_query"],
        optional_analysis=["zonal_statistics", "raster_reclassify"],
        primary_cartography="proximity_overlay",
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="criteria undeclared", reason_code="SITE_SELECTION_CRITERIA_UNDECLARED",
                                  use="constraint_screening")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=43,
        schema_version=2,
        workflow=wf(
            "site_selection", "mcda_ranking",
            zh=["多准则", "加权评分", "候选排序", "方案比选"],
            en=["mcda", "weighted ranking", "topsis"],
            roles=[subject_role(),
                   role("criteria", acquisition="user_upload", required=False,
                        note="准则因子层"),
                   role("constraint", acquisition="user_upload", required=False)],
            obligations=_CRITERIA_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_CRITERIA_FALLBACK],
            evidence=["criteria_weights_provenance", "sensitivity_note"],
        ),
    ),
    CartographyRecipe(
        id="landfill_site_screening",
        name="填埋场选址筛查",
        description="固废/填埋场选址筛查：强约束（避让水源/居民区）+ 准则排序。",
        intent_tasks=["site_selection", "suitability_assessment"],
        intent_cartography=["proximity_overlay", "raster_surface"],
        preferred_analysis=["geometry_buffer", "multi_ring_buffer", "geometry_overlay",
                            "mcda_evaluation", "admin_boundary_query"],
        primary_cartography="proximity_overlay",
        secondary_cartography=["raster_surface"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="criteria undeclared", reason_code="SITE_SELECTION_CRITERIA_UNDECLARED",
                                  use="constraint_screening")],
        export_profile={"formats": ["png", "csv"]},
        priority=47,
        schema_version=2,
        workflow=wf(
            "site_selection", "landfill_screening",
            zh=["填埋场选址", "垃圾站选址", "固废设施选址"],
            en=["landfill site", "waste facility siting"],
            roles=[subject_role(), boundary_role(),
                   role("constraint", acquisition="user_upload", required=False,
                        note="避让水源保护区/居民区等硬约束")],
            obligations=_CRITERIA_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_CRITERIA_FALLBACK],
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
