"""领域包：Statistics / Spatial Autocorrelation（空间统计）。

覆盖 global/local 自相关、Geary、Getis-Ord、比率归一化与行政排名。
多重比较、权重选择、最小样本量等科学义务由 obligations 显式声明，
最终资格仍由算法层 preconditions 裁决（C4：联动不重复）。
"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CHART,
    MAP_COMPONENTS_STATS,
    boundary_role,
    denominator_role,
    fb,
    obl,
    role,
    standard_completion,
    subject_role,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_NUM_FIELD_ROLE = lambda name, note="": role(  # noqa: E731
    "measure", capability="admin_aggregation",
    artifacts=("admin_aggregate_table", "stats_table"), geometry=("polygon", "table"),
    note=note,
)

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="global_moran_autocorrelation",
        name="全局空间自相关（Moran's I）",
        description="全局 Moran's I 检验：数值字段 + 空间权重选择 + 显著性披露；"
                    "权重方案与距离度量（含地理坐标下的投影/反距离处理）必须披露。",
        intent_tasks=["spatial_autocorrelation", "administrative_statistic"],
        intent_cartography=["administrative_choropleth"],
        required_geometry=["Polygon", "MultiPolygon"],
        eligibility=[],
        preferred_analysis=["admin_boundary_query", "admin_aggregation", "global_morans_i"],
        optional_analysis=["local_morans_i"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["hotspot_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="admin units unavailable", reason_code="NEEDS_ADMIN_UNITS", use="point_overlay")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "statistics", "global_autocorrelation",
            zh=["全局自相关", "莫兰指数", "moran", "空间自相关"],
            en=["global moran", "spatial autocorrelation"],
            roles=[
                subject_role(),
                boundary_role(),
                _NUM_FIELD_ROLE("被检验的数值字段（率/比值需先归一化）"),
            ],
            obligations=[
                obl("autocorr_numeric_field", "precondition",
                    precondition="numeric_field_required",
                    code="AUTOCORR_NUMERIC_FIELD_REQUIRED",
                    desc="自相关检验需要数值字段。", action="block_method"),
                obl("autocorr_min_units", "precondition",
                    precondition="min_numeric_samples:8",
                    code="AUTOCORR_INSUFFICIENT_UNITS",
                    desc="空间单元过少时检验不稳定；不足时不得宣称显著。",
                    action="degrade_with_disclosure"),
                obl("autocorr_multiple_testing_note", "disclosure",
                    code="AUTOCORR_MULTIPLE_TESTING",
                    desc="局部指标存在多重比较问题，需 FDR/Bonferroni 校正说明。"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("AUTOCORR_INSUFFICIENT_UNITS", frm="global_morans_i", to="descriptive_summary",
                          downgrade="degraded",
                          disclosure="空间单元不足：仅做描述统计，不做自相关显著性声明。")],
            evidence=["weights_matrix_selection"],
        ),
    ),
    CartographyRecipe(
        id="local_moran_lisa",
        name="局部自相关聚类图（LISA）",
        description="Local Moran's I 聚类图（HH/LL/HL/LH 四象限）：多重比较校正与聚类显著性披露为强制义务。",
        intent_tasks=["spatial_autocorrelation", "concentration_analysis"],
        intent_cartography=["hotspot_overlay", "administrative_choropleth"],
        required_geometry=["Polygon", "MultiPolygon"],
        preferred_analysis=["admin_boundary_query", "admin_aggregation", "local_morans_i"],
        optional_analysis=["global_morans_i"],
        primary_cartography="hotspot_overlay",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="admin units unavailable", reason_code="NEEDS_ADMIN_UNITS", use="point_overlay")],
        export_profile={"formats": ["png"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "statistics", "local_autocorrelation",
            zh=["局部自相关", "lisa", "聚集图", "冷点热点区"],
            en=["lisa", "local moran", "cluster map"],
            roles=[subject_role(), boundary_role(),
                   _NUM_FIELD_ROLE("被检验的数值字段")],
            obligations=[
                obl("lisa_numeric_field", "precondition",
                    precondition="numeric_field_required",
                    code="LISA_NUMERIC_FIELD_REQUIRED",
                    desc="LISA 需要数值字段。", action="block_method"),
                obl("lisa_min_units", "precondition",
                    precondition="min_numeric_samples:8",
                    code="LISA_INSUFFICIENT_UNITS",
                    desc="空间单元不足时局部聚类不可靠。", action="degrade_with_disclosure"),
                obl("lisa_multiple_testing", "disclosure",
                    code="LISA_MULTIPLE_TESTING",
                    desc="LISA 必须披露多重比较校正方式与显著性水平。"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("LISA_INSUFFICIENT_UNITS", frm="lisa_cluster_map", to="descriptive_summary",
                          downgrade="degraded",
                          disclosure="空间单元不足：仅做描述统计，不产聚类显著图。")],
        ),
    ),
    CartographyRecipe(
        id="geary_global_autocorrelation",
        name="全局 Geary's C 检验",
        description="Geary's C 全局自相关（对局部差异更敏感），与 Moran's I 互为佐证。",
        intent_tasks=["spatial_autocorrelation"],
        intent_cartography=["administrative_choropleth"],
        required_geometry=["Polygon", "MultiPolygon"],
        preferred_analysis=["admin_boundary_query", "admin_aggregation", "global_gearys_c"],
        optional_analysis=["global_morans_i"],
        primary_cartography="administrative_choropleth",
        default_components=MAP_COMPONENTS_STATS,
        fallbacks=[RecipeFallback(when="admin units unavailable", reason_code="NEEDS_ADMIN_UNITS", use="point_overlay")],
        export_profile={"formats": ["png", "csv"]},
        priority=48,
        schema_version=2,
        workflow=wf(
            "statistics", "global_autocorrelation",
            zh=["geary", "geary c", "geary检验"],
            en=["geary"],
            roles=[subject_role(), boundary_role(),
                   _NUM_FIELD_ROLE("被检验的数值字段")],
            obligations=[
                obl("geary_numeric_field", "precondition",
                    precondition="numeric_field_required",
                    code="GEARY_NUMERIC_FIELD_REQUIRED",
                    desc="Geary's C 需要数值字段。", action="block_method"),
            ],
            completion=standard_completion(uncertainty=True),
        ),
    ),
    CartographyRecipe(
        id="getis_ord_hotspot_significance",
        name="Getis-Ord Gi* 显著性热点",
        description="Gi* 统计显著性热点/冷点图：只有检验条件满足才出显著结论，否则降级描述性密度。",
        intent_tasks=["concentration_analysis", "spatial_autocorrelation"],
        intent_cartography=["hotspot_overlay", "administrative_choropleth"],
        required_geometry=["Polygon", "MultiPolygon"],
        preferred_analysis=["admin_boundary_query", "admin_aggregation", "getis_ord_gi_star"],
        optional_analysis=["hotspot", "kde_density"],
        primary_cartography="hotspot_overlay",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="admin units unavailable", reason_code="NEEDS_ADMIN_UNITS", use="point_overlay")],
        export_profile={"formats": ["png"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "statistics", "hotspot_significance",
            zh=["显著性热点", "gi星", "getis", "热点检验", "统计热点"],
            en=["getis-ord", "gi star", "statistically significant hotspot"],
            roles=[subject_role(), boundary_role(),
                   _NUM_FIELD_ROLE("被检验的数值字段")],
            obligations=[
                obl("gi_star_numeric_field", "precondition",
                    precondition="numeric_field_required",
                    code="GI_STAR_NUMERIC_FIELD_REQUIRED",
                    desc="Gi* 需要数值字段。", action="block_method"),
                obl("gi_star_min_units", "precondition",
                    precondition="min_numeric_samples:8",
                    code="GI_STAR_INSUFFICIENT_UNITS",
                    desc="空间单元不足，Gi* 检验不成立。", action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[
                fb("GI_STAR_INSUFFICIENT_UNITS", frm="hotspot_significance_map", to="visual_density",
                   downgrade="degraded",
                   disclosure="条件不足：显著性热点降级为视觉密度（描述性，非统计显著）。"),
                fb("HOTSPOT_SIGNIFICANCE_UNAVAILABLE", frm="hotspot_significance_map", to="visual_density",
                   downgrade="degraded",
                   disclosure="显著性检验不可用：仅呈现视觉密度，不得称统计热点。"),
            ],
        ),
    ),
    CartographyRecipe(
        id="general_g_cluster_analysis",
        name="General G 聚集度分析",
        description="General G 全局聚集度检验：高值聚集 vs 低值聚集的全局判断。",
        intent_tasks=["spatial_autocorrelation"],
        intent_cartography=["administrative_choropleth"],
        required_geometry=["Polygon", "MultiPolygon"],
        preferred_analysis=["admin_boundary_query", "admin_aggregation", "general_g"],
        primary_cartography="administrative_choropleth",
        default_components=MAP_COMPONENTS_STATS,
        fallbacks=[RecipeFallback(when="admin units unavailable", reason_code="NEEDS_ADMIN_UNITS", use="point_overlay")],
        export_profile={"formats": ["png", "csv"]},
        priority=48,
        schema_version=2,
        workflow=wf(
            "statistics", "global_autocorrelation",
            zh=["general g", "聚集度检验", "高低值聚集"],
            en=["general g"],
            roles=[subject_role(), boundary_role(), _NUM_FIELD_ROLE("被检验的数值字段")],
            obligations=[obl("general_g_numeric_field", "precondition",
                             precondition="numeric_field_required",
                             code="GENERAL_G_NUMERIC_FIELD_REQUIRED",
                             desc="General G 需要数值字段。", action="block_method")],
            completion=standard_completion(uncertainty=True),
        ),
    ),
    CartographyRecipe(
        id="rate_aggregation_choropleth",
        name="比率归一化专题图",
        description="率/比值专题（人均/地均/占比）：分母必选，缺分母时确定性降级为计数并披露。",
        intent_tasks=["administrative_statistic", "analytical_density", "spatial_equity"],
        intent_cartography=["administrative_choropleth"],
        required_geometry=["Polygon", "MultiPolygon"],
        preferred_analysis=["admin_boundary_query", "admin_aggregation", "rate_aggregation"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="admin units unavailable", reason_code="NEEDS_ADMIN_UNITS", use="point_overlay")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=45,
        schema_version=2,
        workflow=wf(
            "statistics", "normalized_rate",
            zh=["人均", "地均", "占比统计", "率图"],
            en=["per capita", "rate map", "normalized ratio"],
            roles=[subject_role(), boundary_role(), denominator_role()],
            obligations=[obl(
                "rate_requires_denominator", "denominator",
                code="RATE_MISSING_DENOMINATOR",
                desc="率/比值图需要分母；缺失时不得称人均/地均/占比。",
                action="degrade_with_disclosure",
            )],
            completion=standard_completion(),
            fallbacks=[fb("DATA_ROLE_MISSING_DENOMINATOR", frm="rate_choropleth", to="raw_counts",
                          downgrade="degraded",
                          disclosure="缺少分母数据：仅呈现原始计数，不称人均/率。")],
        ),
    ),
    CartographyRecipe(
        id="admin_ranking_stats",
        name="行政区排名统计",
        description="行政区指标排名（Top-N/排序表 + 分级填色），数值字段语义显式声明。",
        intent_tasks=["administrative_statistic"],
        intent_cartography=["administrative_choropleth"],
        required_geometry=["Polygon", "MultiPolygon"],
        preferred_analysis=["admin_boundary_query", "admin_aggregation", "category_breakdown"],
        primary_cartography="administrative_choropleth",
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="admin units unavailable", reason_code="NEEDS_ADMIN_UNITS", use="point_overlay")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=45,
        schema_version=2,
        workflow=wf(
            "statistics", "admin_ranking",
            zh=["排名", "top", "最多最少", "统计排名"],
            en=["ranking by district", "top n"],
            roles=[subject_role(), boundary_role(), _NUM_FIELD_ROLE("排名度量字段")],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="categorical_composition_stats",
        name="类别构成统计",
        description="类别构成/占比结构（图表 + 分类专题），构成语义与密度语义分离。",
        intent_tasks=["categorical_distribution"],
        intent_cartography=["categorical_thematic"],
        required_geometry=["Point", "MultiPoint"],
        preferred_analysis=["poi_query", "category_breakdown", "admin_boundary_query", "admin_aggregation"],
        primary_cartography="categorical_thematic",
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=45,
        schema_version=2,
        workflow=wf(
            "statistics", "categorical_composition",
            zh=["构成比", "结构统计", "类型占比"],
            en=["composition", "category share"],
            roles=[subject_role()],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="zonal_profile_statistics",
        name="分区统计画像",
        description="以行政区/格网为单元的 zonal 统计画像（栅格均值/总量落表）。",
        intent_tasks=["administrative_statistic", "raster_distribution"],
        intent_cartography=["administrative_choropleth", "raster_surface"],
        preferred_analysis=["admin_boundary_query", "raster_source", "zonal_statistics", "admin_aggregation"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["raster_surface"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="admin units unavailable", reason_code="NEEDS_ADMIN_UNITS", use="raster_surface")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "statistics", "zonal_statistics",
            zh=["分区统计", "各区的均值", "栅格统计"],
            en=["zonal statistics"],
            roles=[subject_role(capability="raster_source",
                                artifacts=("raster_surface",), geometry=("raster",)),
                   boundary_role()],
            completion=standard_completion(uncertainty=True),
        ),
    ),
    CartographyRecipe(
        id="spatiotemporal_cluster_detection",
        name="时空聚类检测",
        description="带时间戳的时空聚类（spatiotemporal clustering）：时间字段义务 + 聚类参数披露。",
        intent_tasks=["concentration_analysis", "temporal_trend"],
        intent_cartography=["hotspot_overlay", "point_overlay"],
        preferred_analysis=["poi_query", "spatiotemporal_clustering", "temporal_profile", "point_profile"],
        primary_cartography="hotspot_overlay",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png"]},
        priority=47,
        schema_version=2,
        workflow=wf(
            "statistics", "spatiotemporal_clustering",
            zh=["时空聚类", "时空聚集", "聚集演化"],
            en=["spatiotemporal clustering"],
            roles=[subject_role(),
                   role("target_time", capability="temporal_profile",
                        artifacts=("stats_table",), policy="degrade",
                        disclosure="缺少时间字段：退化为纯空间聚类。")],
            obligations=[obl("st_clustering_temporal_field", "temporal",
                             code="ST_CLUSTERING_TEMPORAL_FIELD_REQUIRED",
                             desc="时空聚类需要时间字段；缺失只能做纯空间聚类。",
                             action="degrade_with_disclosure")],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("DATA_ROLE_MISSING_TARGET_TIME", frm="spatiotemporal_clusters", to="spatial_clusters",
                          downgrade="approximation",
                          disclosure="缺少时间维度：退化为纯空间聚类，不称时空演化。")],
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
