"""领域包：Suitability（适宜性评价）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CONTINUOUS,
    boundary_role,
    fb,
    obl,
    role,
    standard_completion,
    subject_role,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_SUIT_OBLIGATIONS = [
    obl("suitability_factors_declared", "disclosure",
        code="SUITABILITY_FACTORS_UNDECLARED",
        desc="适宜性因子未声明时不得静默编造；必须先确认因子体系。",
        action="degrade_with_disclosure"),
    obl("suitability_weight_provenance", "disclosure",
        code="SUITABILITY_WEIGHT_PROVENANCE",
        desc="因子权重来源必须披露（用户/规范/AHP/等权）。"),
    obl("suitability_normalization_semantics", "disclosure",
        code="SUITABILITY_NORMALIZATION_SEMANTICS",
        desc="因子标准化方法（min-max/分级）影响量纲一致性，必须披露。"),
]
_SUIT_FALLBACK = fb(
    "SUITABILITY_FACTORS_UNDECLARED", frm="suitability_surface", to="constraint_screening",
    downgrade="degraded",
    disclosure="因子体系未声明：仅做硬约束排除，不做加权适宜性面。",
)

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="construction_suitability",
        name="建设适宜性评价",
        description="城镇建设适宜性（地形/地质/交通/用地因子加权）：因子与权重来源义务。",
        intent_tasks=["suitability_assessment", "site_selection"],
        intent_cartography=["raster_surface", "administrative_choropleth"],
        preferred_analysis=["raster_source", "terrain_slope", "raster_reclassify", "geometry_overlay",
                            "mcda_evaluation", "zonal_statistics"],
        optional_analysis=["admin_boundary_query", "admin_aggregation"],
        primary_cartography="raster_surface",
        secondary_cartography=["administrative_aggregation"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=[RecipeFallback(when="factors undeclared", reason_code="SUITABILITY_FACTORS_UNDECLARED",
                                  use="constraint_screening")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "suitability", "construction_suitability",
            zh=["建设适宜性", "适建区", "开发适宜", "宜建区"],
            en=["construction suitability"],
            roles=[subject_role(capability="raster_source",
                                artifacts=("raster_surface",), geometry=("raster",)),
                   boundary_role(),
                   role("criteria", acquisition="user_upload", required=False),
                   role("constraint", acquisition="user_upload", required=False)],
            obligations=_SUIT_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_SUIT_FALLBACK],
            evidence=["criteria_weights_provenance"],
        ),
    ),
    CartographyRecipe(
        id="agriculture_suitability",
        name="农业适宜性评价",
        description="耕作/种植适宜性（土壤/坡度/水热代理因子）：因子语义与数据年代披露。",
        intent_tasks=["suitability_assessment"],
        intent_cartography=["raster_surface", "administrative_choropleth"],
        preferred_analysis=["raster_source", "terrain_slope", "ndvi", "raster_reclassify",
                            "geometry_overlay", "mcda_evaluation", "zonal_statistics"],
        primary_cartography="raster_surface",
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=[RecipeFallback(when="factors undeclared", reason_code="SUITABILITY_FACTORS_UNDECLARED",
                                  use="constraint_screening")],
        export_profile={"formats": ["png", "csv"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "suitability", "agriculture_suitability",
            zh=["农业适宜", "耕作适宜", "种植适宜区"],
            en=["agricultural suitability"],
            roles=[subject_role(capability="raster_source",
                                artifacts=("raster_surface",), geometry=("raster",)),
                   role("criteria", acquisition="user_upload", required=False),
                   role("constraint", acquisition="user_upload", required=False)],
            obligations=_SUIT_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_SUIT_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="ecological_suitability",
        name="生态保护适宜性",
        description="生态重要性/保护适宜性分区（水源涵养/植被覆盖代理因子）。",
        intent_tasks=["suitability_assessment"],
        intent_cartography=["raster_surface", "administrative_choropleth"],
        preferred_analysis=["raster_source", "ndvi", "terrain_slope", "raster_reclassify",
                            "geometry_overlay", "mcda_evaluation", "zonal_statistics"],
        primary_cartography="raster_surface",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=[RecipeFallback(when="factors undeclared", reason_code="SUITABILITY_FACTORS_UNDECLARED",
                                  use="constraint_screening")],
        export_profile={"formats": ["png", "csv"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "suitability", "ecological_suitability",
            zh=["生态适宜", "生态保护区", "重要生态空间"],
            en=["ecological suitability"],
            roles=[subject_role(capability="raster_source",
                                artifacts=("raster_surface",), geometry=("raster",)),
                   boundary_role(),
                   role("criteria", acquisition="user_upload", required=False),
                   role("constraint", acquisition="user_upload", required=False)],
            obligations=_SUIT_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_SUIT_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="urban_expansion_suitability",
        name="城镇扩张适宜性",
        description="城镇开发边界/扩张适宜性评价（双评价思路）。",
        intent_tasks=["suitability_assessment"],
        intent_cartography=["raster_surface", "administrative_choropleth"],
        preferred_analysis=["raster_source", "terrain_slope", "band_math", "raster_reclassify",
                            "geometry_overlay", "mcda_evaluation", "zonal_statistics"],
        primary_cartography="raster_surface",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=[RecipeFallback(when="factors undeclared", reason_code="SUITABILITY_FACTORS_UNDECLARED",
                                  use="constraint_screening")],
        export_profile={"formats": ["png", "csv"]},
        priority=47,
        schema_version=2,
        workflow=wf(
            "suitability", "expansion_suitability",
            zh=["开发边界", "扩张适宜", "城镇开发适宜性", "双评价"],
            en=["urban expansion suitability", "double evaluation"],
            roles=[subject_role(capability="raster_source",
                                artifacts=("raster_surface",), geometry=("raster",)),
                   boundary_role(),
                   role("criteria", acquisition="user_upload", required=False),
                   role("constraint", acquisition="user_upload", required=False)],
            obligations=_SUIT_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_SUIT_FALLBACK],
        ),
    ),
    CartographyRecipe(
        id="tourism_suitability",
        name="旅游开发适宜性",
        description="旅游资源开发适宜性（景观可达/设施配套代理因子）。",
        intent_tasks=["suitability_assessment"],
        intent_cartography=["raster_surface", "proximity_overlay"],
        preferred_analysis=["raster_source", "service_area", "raster_reclassify", "geometry_overlay",
                            "mcda_evaluation", "zonal_statistics"],
        primary_cartography="raster_surface",
        secondary_cartography=["proximity_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=[RecipeFallback(when="factors undeclared", reason_code="SUITABILITY_FACTORS_UNDECLARED",
                                  use="constraint_screening")],
        export_profile={"formats": ["png", "csv"]},
        priority=48,
        schema_version=2,
        workflow=wf(
            "suitability", "tourism_suitability",
            zh=["旅游适宜", "景区开发", "文旅适宜性"],
            en=["tourism suitability"],
            roles=[subject_role(), boundary_role(),
                   role("criteria", acquisition="user_upload", required=False),
                   role("constraint", acquisition="user_upload", required=False)],
            obligations=_SUIT_OBLIGATIONS,
            completion=standard_completion(uncertainty=True),
            fallbacks=[_SUIT_FALLBACK],
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
