"""领域包：Temporal（时序分析）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CHART,
    fb,
    obl,
    role,
    standard_completion,
    subject_role,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe

_TIME_ROLE = lambda policy="degrade": role(  # noqa: E731
    "target_time", capability="temporal_profile",
    artifacts=("stats_table",), policy=policy,
    disclosure="缺少时间字段/多期观测：无法做时序分析，退化为单期快照。",
)

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="temporal_profile_station",
        name="站点时序画像",
        description="单站/多站观测时序画像（折线+点位标注）：时间字段义务，趋势声明守卫。",
        intent_tasks=["temporal_trend", "simple_view"],
        intent_cartography=["point_overlay"],
        preferred_analysis=["poi_query", "temporal_profile", "point_profile"],
        optional_analysis=["temporal_trend"],
        primary_cartography="point_overlay",
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=45,
        schema_version=2,
        workflow=wf(
            "temporal", "station_profile",
            zh=["时序曲线", "时间变化", "监测时序"],
            en=["time profile", "temporal curve"],
            roles=[subject_role(), _TIME_ROLE()],
            obligations=[
                obl("profile_temporal_field", "temporal",
                    code="PROFILE_TEMPORAL_FIELD_REQUIRED",
                    desc="时序画像需要时间字段。", action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("DATA_ROLE_MISSING_TARGET_TIME", frm="temporal_profile", to="snapshot_view",
                          downgrade="degraded",
                          disclosure="缺少时间维度：仅呈现当前快照。")],
        ),
    ),
    CartographyRecipe(
        id="linear_trend_analysis",
        name="线性趋势分析",
        description="多期观测线性趋势（斜率+显著性）：观测期数义务（≥4），两期不得称趋势。",
        intent_tasks=["temporal_trend"],
        intent_cartography=["administrative_choropleth", "point_overlay"],
        preferred_analysis=["temporal_profile", "temporal_trend", "admin_aggregation", "admin_boundary_query"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=44,
        schema_version=2,
        workflow=wf(
            "temporal", "linear_trend",
            zh=["变化趋势", "趋势分析", "逐年变化", "年际趋势"],
            en=["trend analysis", "temporal trend"],
            roles=[subject_role(), _TIME_ROLE()],
            obligations=[
                obl("trend_min_observations", "precondition",
                    precondition="min_temporal_observations:4",
                    code="TREND_INSUFFICIENT_OBSERVATIONS",
                    desc="趋势需要多期观测；两期只是差值。",
                    action="degrade_with_disclosure"),
                obl("trend_temporal_field", "temporal",
                    precondition="temporal_field_required",
                    code="TREND_TEMPORAL_FIELD_REQUIRED",
                    desc="趋势分析需要时间字段。", action="block_method"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("TREND_INSUFFICIENT_OBSERVATIONS", frm="trend_map", to="bitemporal_difference",
                          downgrade="degraded",
                          disclosure="观测期不足：仅做两期对比，不称长期趋势。")],
        ),
    ),
    CartographyRecipe(
        id="changepoint_detection_workflow",
        name="突变点检测",
        description="时序突变点（changepoint）检测：需要长序列；短序列降级两期对比并披露。",
        intent_tasks=["temporal_trend", "change_detection"],
        intent_cartography=["point_overlay", "administrative_choropleth"],
        preferred_analysis=["temporal_profile", "temporal_change_point", "temporal_trend"],
        primary_cartography="point_overlay",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "temporal", "changepoint_detection",
            zh=["突变点", "拐点", "转折点", "变化节点"],
            en=["changepoint", "breakpoint detection"],
            roles=[subject_role(), _TIME_ROLE()],
            obligations=[
                obl("changepoint_min_observations", "precondition",
                    precondition="min_temporal_observations:8",
                    code="CHANGEPOINT_INSUFFICIENT_SERIES",
                    desc="突变点检测需要较长序列；不足时降级。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("CHANGEPOINT_INSUFFICIENT_SERIES", frm="changepoint_map", to="bitemporal_difference",
                          downgrade="degraded",
                          disclosure="序列过短：不做突变点检测，仅两期对比。")],
        ),
    ),
    CartographyRecipe(
        id="seasonal_pattern_analysis",
        name="季节性模式分析",
        description="周期/季节性模式识别（月度/季度聚合）：至少一个完整周期的观测义务。",
        intent_tasks=["temporal_trend"],
        intent_cartography=["point_overlay", "administrative_choropleth"],
        preferred_analysis=["temporal_profile", "temporal_aggregate", "temporal_trend"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=47,
        schema_version=2,
        workflow=wf(
            "temporal", "seasonal_pattern",
            zh=["季节性", "月度模式", "周期分析", "旺季淡季"],
            en=["seasonality", "seasonal pattern"],
            roles=[subject_role(), _TIME_ROLE()],
            obligations=[
                obl("seasonal_full_cycle", "temporal",
                    code="SEASONAL_CYCLE_INCOMPLETE",
                    desc="季节性分析需要至少一个完整周期观测。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("SEASONAL_CYCLE_INCOMPLETE", frm="seasonal_pattern", to="descriptive_summary",
                          downgrade="degraded",
                          disclosure="观测周期不完整：不宣称季节性规律。")],
        ),
    ),
    CartographyRecipe(
        id="temporal_aggregate_stats",
        name="时段聚合统计",
        description="按日/月/年聚合的时段统计（总量/均值）+ 空间分布联动。",
        intent_tasks=["temporal_trend", "administrative_statistic"],
        intent_cartography=["administrative_choropleth", "point_overlay"],
        preferred_analysis=["temporal_aggregate", "admin_aggregation", "admin_boundary_query", "point_profile"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "temporal", "aggregate_stats",
            zh=["按月统计", "按年汇总", "时段统计"],
            en=["temporal aggregation", "monthly stats"],
            roles=[subject_role(), _TIME_ROLE()],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="interannual_comparison_workflow",
        name="年际对比分析",
        description="多年同期对比（去年 vs 今年等）：对比期角色显式声明，差异语义守卫。",
        intent_tasks=["temporal_trend", "change_detection"],
        intent_cartography=["administrative_choropleth", "point_overlay"],
        preferred_analysis=["temporal_profile", "temporal_aggregate", "admin_aggregation",
                            "admin_boundary_query"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["point_overlay"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=45,
        schema_version=2,
        workflow=wf(
            "temporal", "interannual_comparison",
            zh=["同比", "去年对比", "年际对比", "和去年比"],
            en=["year over year", "interannual comparison"],
            roles=[
                subject_role(),
                role("baseline", capability="temporal_profile", artifacts=("stats_table",),
                     policy="degrade", disclosure="缺少基期数据：无法做同比。"),
                role("comparison_time", capability="temporal_profile", artifacts=("stats_table",),
                     policy="degrade", disclosure="缺少对比期数据：无法做同比。"),
            ],
            obligations=[
                obl("interannual_baseline_required", "temporal",
                    code="INTERANNUAL_BASELINE_REQUIRED",
                    desc="年际对比需要基期与对比期两套数据。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(uncertainty=True),
            fallbacks=[fb("DATA_ROLE_MISSING_BASELINE", frm="yoy_comparison", to="current_snapshot",
                          downgrade="degraded",
                          disclosure="缺少基期数据：仅呈现本期，不做同比。")],
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
