"""领域包：Terrain（地形衍生）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    boundary_role,
    elevation_role,
    fb,
    obl,
    role,
    standard_completion,
    wf,
    MAP_COMPONENTS_CONTINUOUS,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

DEM_OBLIGATIONS = [
    obl("terrain_dem_required", "precondition",
        precondition="raster_band_required:1",
        code="TERRAIN_DEM_BAND_REQUIRED",
        desc="地形衍生需要单波段 DEM 输入。", action="block_method"),
    obl("terrain_crs_metric", "precondition",
        precondition="local_metric_crs_required",
        code="TERRAIN_METRIC_CRS_REQUIRED",
        desc="坡度/汇算需要投影（米制）CRS；角度坐标必须先变换。",
        action="degrade_with_disclosure"),
]
#: recipe 级回退表（reason_code 匹配 DisabledElement）
DEM_FALLBACKS = [
    RecipeFallback(when="CRS not metric", reason_code="TERRAIN_METRIC_CRS_REQUIRED", use="dem_view"),
    RecipeFallback(when="no valid DEM band", reason_code="TERRAIN_DEM_BAND_REQUIRED", use="summary"),
]
#: workflow 级语义回退策略（C6：降级分类 + 披露）
DEM_WF_POLICIES = [
    fb("TERRAIN_METRIC_CRS_REQUIRED", frm="terrain_derivative", to="dem_view",
       downgrade="degraded",
       disclosure="坐标为角度单位：坡度等衍生不可靠，仅呈现 DEM 原始面。"),
    fb("TERRAIN_DEM_BAND_REQUIRED", frm="terrain_derivative", to="summary",
       downgrade="not_allowed", blocks=True,
       disclosure="无有效 DEM 输入：地形衍生无法进行。"),
]

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="slope_analysis_workflow",
        name="坡度分析",
        description="DEM 坡度衍生 + 分级制图：米制 CRS 义务 + 单位（度/百分比）披露。",
        intent_tasks=["terrain_analysis"],
        intent_cartography=["raster_surface", "isoline_contour"],
        preferred_analysis=["raster_source", "terrain_slope", "terrain_derivatives", "zonal_statistics"],
        optional_analysis=["admin_boundary_query", "admin_aggregation"],
        primary_cartography="raster_surface",
        secondary_cartography=["isoline_contour"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=DEM_FALLBACKS,
        export_profile={"formats": ["png"]},
        priority=44,
        schema_version=2,
        workflow=wf(
            "terrain", "slope_analysis",
            zh=["坡度", "坡度分析", "陡坡"],
            en=["slope analysis", "steepness"],
            roles=[elevation_role()],
            obligations=DEM_OBLIGATIONS,
            fallbacks=DEM_WF_POLICIES,
            completion=standard_completion(uncertainty=True),
            disclosures=["TERRAIN_SLOPE_UNITS"],
            recompute=["data", "parameter", "output"],
        ),
    ),
    CartographyRecipe(
        id="aspect_analysis_workflow",
        name="坡向分析",
        description="DEM 坡向衍生（方位分类）：阳坡/阴坡等向别分类制图。",
        intent_tasks=["terrain_analysis"],
        intent_cartography=["raster_surface"],
        preferred_analysis=["raster_source", "terrain_aspect", "terrain_derivatives"],
        primary_cartography="raster_surface",
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=DEM_FALLBACKS,
        export_profile={"formats": ["png"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "terrain", "aspect_analysis",
            zh=["坡向", "阴阳坡", "朝向分析"],
            en=["aspect analysis"],
            roles=[elevation_role()],
            obligations=DEM_OBLIGATIONS,
            fallbacks=DEM_WF_POLICIES,
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="hillshade_cartography",
        name="山体阴影渲染",
        description="山体阴影（hillshade）地形渲染：光源方位/高度角参数披露。",
        intent_tasks=["terrain_analysis", "simple_view", "raster_distribution"],
        intent_cartography=["raster_surface"],
        preferred_analysis=["raster_source", "terrain_hillshade", "terrain_derivatives"],
        primary_cartography="raster_surface",
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=DEM_FALLBACKS,
        export_profile={"formats": ["png"]},
        priority=44,
        schema_version=2,
        workflow=wf(
            "terrain", "hillshade_cartography",
            zh=["山体阴影", "hillshade", "晕渲图", "地形渲染"],
            en=["hillshade", "shaded relief"],
            roles=[elevation_role()],
            obligations=DEM_OBLIGATIONS,
            fallbacks=DEM_WF_POLICIES,
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="terrain_relief_overview",
        name="地势起伏概览",
        description="区域地势起伏度概览（相对高程 + 分区起伏统计）。",
        intent_tasks=["terrain_analysis", "raster_distribution"],
        intent_cartography=["raster_surface", "administrative_choropleth"],
        preferred_analysis=["raster_source", "terrain_derivatives", "zonal_statistics", "admin_boundary_query"],
        optional_analysis=["admin_aggregation"],
        primary_cartography="raster_surface",
        secondary_cartography=["administrative_aggregation"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=DEM_FALLBACKS,
        export_profile={"formats": ["png"]},
        priority=45,
        schema_version=2,
        workflow=wf(
            "terrain", "relief_overview",
            zh=["地势", "起伏度", "高程分布", "地形概览"],
            en=["terrain relief", "elevation overview"],
            roles=[elevation_role(), boundary_role(required=False)],
            obligations=DEM_OBLIGATIONS,
            fallbacks=DEM_WF_POLICIES,
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="viewshed_analysis_workflow",
        name="视域/通视分析",
        description="观察点视域分析：DEM 质量 + 观察点高度参数披露；结果为可见/不可见分区。",
        intent_tasks=["terrain_analysis", "site_selection"],
        intent_cartography=["raster_surface", "proximity_overlay"],
        preferred_analysis=["raster_source", "terrain_viewshed", "terrain_derivatives", "point_profile"],
        primary_cartography="raster_surface",
        secondary_cartography=["proximity_overlay"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=DEM_FALLBACKS,
        export_profile={"formats": ["png"]},
        priority=46,
        schema_version=2,
        workflow=wf(
            "terrain", "viewshed_analysis",
            zh=["视域", "通视", "可视域", "瞭望覆盖"],
            en=["viewshed", "visibility analysis"],
            roles=[elevation_role(),
                   role("reference", required=True, capability="point_profile",
                        artifacts=("point_feature_set",), geometry=("point",),
                        note="观察点（如信号塔/观景台）")],
            obligations=DEM_OBLIGATIONS,
            fallbacks=DEM_WF_POLICIES,
            completion=standard_completion(uncertainty=True),
        ),
    ),
    CartographyRecipe(
        id="contour_map_product",
        name="等高线产品",
        description="等高线（isoline）地形产品：等距参数披露 + 与 DEM 面图层联动。",
        intent_tasks=["terrain_analysis", "simple_view", "raster_distribution"],
        intent_cartography=["isoline_contour", "raster_surface"],
        preferred_analysis=["raster_source", "terrain_contours", "terrain_derivatives"],
        primary_cartography="isoline_contour",
        secondary_cartography=["raster_surface"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=DEM_FALLBACKS,
        export_profile={"formats": ["png", "pdf"]},
        priority=45,
        schema_version=2,
        workflow=wf(
            "terrain", "contour_product",
            zh=["等高线", "等值线", "contour"],
            en=["contour map", "isoline"],
            roles=[elevation_role()],
            obligations=DEM_OBLIGATIONS,
            fallbacks=DEM_WF_POLICIES,
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="terrain_morphometry_suite",
        name="地形形态计量套件",
        description="坡度/坡向/起伏/曲率综合地形计量（多衍生对比面板）。",
        intent_tasks=["terrain_analysis"],
        intent_cartography=["raster_surface"],
        preferred_analysis=["raster_source", "terrain_derivatives", "terrain_slope", "terrain_aspect", "terrain_hillshade"],
        primary_cartography="raster_surface",
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=DEM_FALLBACKS,
        export_profile={"formats": ["png", "pdf"]},
        priority=47,
        schema_version=2,
        workflow=wf(
            "terrain", "morphometry_suite",
            zh=["地形因子", "形态计量", "地形综合分析"],
            en=["terrain morphometry", "terrain derivatives suite"],
            roles=[elevation_role()],
            obligations=DEM_OBLIGATIONS,
            fallbacks=DEM_WF_POLICIES,
            completion=standard_completion(uncertainty=True),
        ),
    ),
    CartographyRecipe(
        id="slope_zoning_constraint",
        name="坡度分区约束",
        description="坡度分级约束区提取（如 >25° 禁建）：分级阈值披露 + 面积台账。",
        intent_tasks=["terrain_analysis", "suitability_assessment"],
        intent_cartography=["raster_surface", "administrative_choropleth"],
        preferred_analysis=["raster_source", "terrain_slope", "raster_reclassify", "zonal_statistics"],
        optional_analysis=["admin_boundary_query", "admin_aggregation"],
        primary_cartography="raster_surface",
        secondary_cartography=["administrative_aggregation"],
        default_components=MAP_COMPONENTS_CONTINUOUS,
        fallbacks=DEM_FALLBACKS,
        export_profile={"formats": ["png", "csv"]},
        priority=45,
        schema_version=2,
        workflow=wf(
            "terrain", "slope_zoning",
            zh=["坡度分区", "禁建区", "陡坡约束", "开垦限制"],
            en=["slope zoning", "steep slope constraint"],
            roles=[elevation_role()],
            obligations=[
                *DEM_OBLIGATIONS,
                obl("slope_threshold_disclosure", "disclosure",
                    code="SLOPE_THRESHOLD_DECLARED",
                    desc="坡度分区阈值必须显式披露（来源：规范/用户指定）。"),
            ],
            fallbacks=DEM_WF_POLICIES,
            completion=standard_completion(),
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
