"""领域包：Urban（城市研究）。"""
from __future__ import annotations

from typing import List

from app.services.gis_harness.recipe_packs._kit import (
    MAP_COMPONENTS_CHART,
    MAP_COMPONENTS_STATS,
    boundary_role,
    denominator_role,
    fb,
    obl,
    role,
    standard_completion,
    subject_role,
    wf,
)
from app.services.gis_harness.recipes import CartographyRecipe, RecipeFallback

_RECIPES: List[CartographyRecipe] = [
    CartographyRecipe(
        id="landuse_structure_admin",
        name="用地结构统计",
        description="行政区用地/功能区结构统计（各类面积占比）：口径与年代披露。",
        intent_tasks=["administrative_statistic", "categorical_distribution", "raster_distribution"],
        intent_cartography=["administrative_choropleth", "categorical_thematic"],
        preferred_analysis=["raster_source", "raster_reclassify", "zonal_statistics",
                            "admin_boundary_query", "admin_aggregation", "category_breakdown"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["categorical_thematic"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="admin units unavailable", reason_code="NEEDS_ADMIN_UNITS",
                                  use="categorical_raster")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=46,
        schema_version=2,
        workflow=wf(
            "urban", "landuse_structure",
            zh=["用地结构", "用地构成", "功能区统计"],
            en=["land use structure"],
            roles=[subject_role(capability="raster_source", artifacts=("raster_surface",),
                                geometry=("raster",)),
                   boundary_role()],
            completion=standard_completion(),
        ),
    ),
    CartographyRecipe(
        id="poi_function_mix",
        name="POI 功能混合度",
        description="街区 POI 功能混合度画像（类别熵代理）：代理语义披露。",
        intent_tasks=["categorical_distribution", "administrative_statistic"],
        intent_cartography=["administrative_choropleth", "aggregate_grid"],
        preferred_analysis=["poi_query", "category_breakdown", "grid_binning",
                            "admin_boundary_query", "admin_aggregation"],
        primary_cartography="administrative_choropleth",
        secondary_cartography=["aggregate_grid"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=47,
        schema_version=2,
        workflow=wf(
            "urban", "function_mix",
            zh=["功能混合", "业态混合", "职住混合", "活力多样性"],
            en=["function mix", "poi diversity"],
            roles=[subject_role(), boundary_role()],
            obligations=[
                obl("mix_proxy_semantics", "disclosure",
                    code="FUNCTION_MIX_PROXY_SEMANTICS",
                    desc="POI 类别混合度是功能多样性的代理指标，非用地审批口径。"),
            ],
            completion=standard_completion(uncertainty=True),
        ),
    ),
    CartographyRecipe(
        id="greening_rate_admin",
        name="绿化率统计",
        description="行政区绿化率/绿地率统计（绿地面积/行政区面积）：面积分母义务。",
        intent_tasks=["administrative_statistic", "vegetation_index", "spatial_equity"],
        intent_cartography=["administrative_choropleth"],
        preferred_analysis=["raster_source", "ndvi", "zonal_statistics", "admin_boundary_query",
                            "admin_aggregation", "rate_aggregation"],
        primary_cartography="administrative_choropleth",
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[RecipeFallback(when="admin units unavailable", reason_code="NEEDS_ADMIN_UNITS",
                                  use="ndvi_raster")],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=47,
        schema_version=2,
        workflow=wf(
            "urban", "greening_rate",
            zh=["绿化率", "绿地率", "人均绿地"],
            en=["greening rate"],
            roles=[subject_role(capability="raster_source", artifacts=("raster_surface",),
                                geometry=("raster",)),
                   boundary_role(), denominator_role()],
            obligations=[
                obl("greening_rate_denominator", "denominator",
                    code="GREENING_RATE_MISSING_AREA",
                    desc="绿化率需要行政区面积分母；人均绿地需要人口分母。",
                    action="degrade_with_disclosure"),
            ],
            completion=standard_completion(),
            fallbacks=[fb("DATA_ROLE_MISSING_DENOMINATOR", frm="greening_rate", to="green_area_stats",
                          downgrade="degraded",
                          disclosure="缺少分母数据：仅统计绿地面积，不称绿化率/人均绿地。")],
        ),
    ),
    CartographyRecipe(
        id="nightlight_vitality_profile",
        name="夜间灯光活力画像",
        description="夜间灯光/亮度栅格的城市活力画像（代理指标）：影像时相强披露。",
        intent_tasks=["raster_distribution", "temporal_trend"],
        intent_cartography=["raster_surface", "administrative_choropleth"],
        preferred_analysis=["raster_source", "zonal_statistics", "admin_boundary_query",
                            "admin_aggregation", "temporal_profile"],
        primary_cartography="raster_surface",
        secondary_cartography=["administrative_aggregation"],
        default_components=MAP_COMPONENTS_STATS,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"]},
        priority=48,
        schema_version=2,
        workflow=wf(
            "urban", "nightlight_vitality",
            zh=["夜间灯光", "城市活力", "灯光强度"],
            en=["nighttime lights", "urban vitality"],
            roles=[subject_role(capability="raster_source", artifacts=("raster_surface",),
                                geometry=("raster",)),
                   boundary_role(required=False)],
            obligations=[
                obl("nightlight_proxy_semantics", "disclosure",
                    code="NIGHTLIGHT_PROXY_SEMANTICS",
                    desc="夜间灯光是经济/活力代理指标，且受影像时相影响，必须披露。"),
            ],
            completion=standard_completion(uncertainty=True),
        ),
    ),
    CartographyRecipe(
        id="urban_service_density_profile",
        name="城区服务密度画像",
        description="城区各类服务设施密度分级画像（格网/行政区双尺度）。",
        intent_tasks=["analytical_density", "administrative_statistic", "distribution_overview"],
        intent_cartography=["aggregate_grid", "administrative_choropleth"],
        preferred_analysis=["poi_query", "grid_binning", "admin_boundary_query", "admin_aggregation",
                            "rate_aggregation"],
        primary_cartography="aggregate_grid",
        secondary_cartography=["administrative_choropleth"],
        default_components=MAP_COMPONENTS_CHART,
        fallbacks=[],
        export_profile={"formats": ["png", "csv"], "chart": True},
        priority=47,
        schema_version=2,
        workflow=wf(
            "urban", "service_density_profile",
            zh=["服务密度", "设施密度画像", "城区密度"],
            en=["urban service density"],
            roles=[subject_role(), boundary_role()],
            completion=standard_completion(),
        ),
    ),
]

RECIPES: List[CartographyRecipe] = _RECIPES
