"""
地图导出路由 — 智能制图工作流

导出接口由 Agent 指令 `export_thematic_map` 触发，
接收前端 Canvas 合成结果并持久化。支持 PNG 和标准 PDF 制图输出。
"""

from fastapi import APIRouter, HTTPException, UploadFile, File, Form
from typing import Optional
import io
import os
import uuid
import time
from fastapi.responses import FileResponse
from app.core.config import settings

router = APIRouter()

EXPORT_DIR = os.path.join(settings.DATA_DIR, "exports")
os.makedirs(EXPORT_DIR, exist_ok=True)

MAX_EXPORT_SIZE = 50 * 1024 * 1024  # 50 MB

_MEDIA_TYPES = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".pdf": "application/pdf",
}


@router.post("/export", tags=["地图制图"])
async def upload_map_export(
    file: UploadFile = File(...),
    title: Optional[str] = Form(default=None),
):
    """接收来自前端的 Canvas 合成结果并持久化，返回可供下载访问的链接。"""
    if not file.filename:
        raise HTTPException(status_code=400, detail="未提供文件名")

    ext = os.path.splitext(file.filename)[1].lower()
    if ext not in [".png", ".jpg", ".jpeg"]:
        ext = ".png"

    filename = f"map_export_{int(time.time())}_{uuid.uuid4().hex[:6]}{ext}"
    filepath = os.path.join(EXPORT_DIR, filename)

    try:
        content = await file.read(MAX_EXPORT_SIZE + 1)
        if len(content) > MAX_EXPORT_SIZE:
            raise HTTPException(status_code=413, detail="文件过大，上限 50MB")
        with open(filepath, "wb") as f:
            f.write(content)
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"保存导出图失败: {str(e)}")

    download_url = f"/api/v1/export/download/{filename}"
    return {
        "success": True,
        "filename": filename,
        "url": download_url,
        "message": "地图制品已成功保存",
    }


@router.post("/export/pdf", tags=["地图制图"])
async def export_map_as_pdf(
    file: UploadFile = File(...),
    title: Optional[str] = Form(default=None),
    subtitle: Optional[str] = Form(default=None),
    author: Optional[str] = Form(default="WebGIS AI Agent"),
    scale_text: Optional[str] = Form(default=None),
):
    """
    将前端合成的地图图片嵌入标准 A4 横向专题底图 PDF。

    PDF 布局包含：
    - 标题 / 副标题区
    - 地图影像主体（保留原 Canvas 分辨率）
    - 页脚（时间戳、制图者、比例说明）
    """
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import matplotlib.font_manager as fm
        import numpy as np
        from PIL import Image

        content = await file.read(MAX_EXPORT_SIZE + 1)
        if len(content) > MAX_EXPORT_SIZE:
            raise HTTPException(status_code=413, detail="文件过大，上限 50MB")

        img = Image.open(io.BytesIO(content)).convert("RGB")
        img_arr = np.array(img)

        # ── 选择支持 CJK 的字体（如存在） ──
        cjk_keywords = ["cjk", "noto", "source han", "wqy", "simhei",
                        "simsun", "microsoft yahei", "pingfang", "heiti"]
        cjk_font = next(
            (f.name for f in fm.fontManager.ttflist
             if any(kw in f.name.lower() for kw in cjk_keywords)),
            None,
        )
        if cjk_font:
            plt.rcParams["font.family"] = cjk_font

        # ── A4 横向 (297×210 mm ≈ 11.69×8.27 in) ──
        fig = plt.figure(figsize=(11.69, 8.27), facecolor="white")

        map_top = 0.88
        map_bottom = 0.10
        ax_map = fig.add_axes([0.04, map_bottom, 0.92, map_top - map_bottom])
        ax_map.imshow(img_arr, aspect="auto")
        ax_map.axis("off")

        # 边框
        for spine in ax_map.spines.values():
            spine.set_visible(True)
            spine.set_linewidth(0.8)
            spine.set_edgecolor("#cccccc")

        # ── 标题区 ──
        map_title = title or "专题地图"
        fig.text(
            0.5, 0.955, map_title,
            ha="center", va="top",
            fontsize=15, fontweight="bold", color="#1e293b",
        )
        if subtitle:
            fig.text(
                0.5, 0.925, subtitle,
                ha="center", va="top",
                fontsize=10, color="#64748b",
            )

        # ── 页脚 ──
        date_str = time.strftime("%Y-%m-%d")
        footer_parts = [f"制图日期: {date_str}"]
        if author:
            footer_parts.append(f"制图者: {author}")
        if scale_text:
            footer_parts.append(f"比例尺: {scale_text}")
        footer_parts.append("Generated by WebGIS AI Agent")

        fig.text(
            0.5, 0.025, "  |  ".join(footer_parts),
            ha="center", va="bottom",
            fontsize=7, color="#94a3b8", style="italic",
        )

        # ── 保存 PDF ──
        pdf_filename = f"map_export_{int(time.time())}_{uuid.uuid4().hex[:6]}.pdf"
        pdf_path = os.path.join(EXPORT_DIR, pdf_filename)
        fig.savefig(pdf_path, format="pdf", dpi=150, bbox_inches="tight",
                    metadata={
                        "Title": map_title,
                        "Author": author or "WebGIS AI Agent",
                        "Subject": subtitle or "",
                        "Creator": "WebGIS AI Agent",
                    })
        plt.close(fig)

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"PDF 生成失败: {str(e)}")

    return {
        "success": True,
        "filename": pdf_filename,
        "url": f"/api/v1/export/download/{pdf_filename}",
        "format": "pdf",
        "message": "专题底图 PDF 已成功生成",
    }


@router.get("/export/download/{filename}", tags=["地图制图"])
def download_map_export(filename: str):
    """下载生成的专题地图成果（PNG / PDF）"""
    safe_filename = os.path.basename(filename)
    filepath = os.path.join(EXPORT_DIR, safe_filename)
    if not os.path.exists(filepath):
        raise HTTPException(status_code=404, detail="地图文件不存在或已过期失效")

    ext = os.path.splitext(safe_filename)[1].lower()
    media_type = _MEDIA_TYPES.get(ext, "application/octet-stream")
    disposition = "inline" if ext in (".png", ".jpg", ".jpeg") else "attachment"

    return FileResponse(
        filepath,
        media_type=media_type,
        headers={"Content-Disposition": f'{disposition}; filename="{safe_filename}"'},
    )
