"""Standards fixture matrix — 200+ deterministic cases, engine vs expectation.

Each fixture case pins: which rule ids must fire, overall report status, and
the pre-compile gate verdict, for one (mapspec, profile) pair. The matrix is
generated by ``fixtures/standards_cases/_generate.py`` from a hand-authored
expectation table; this test is the drift gate in both directions (engine
regression AND silent table edits).
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.lib.cartography.standards.profile import resolve_profile
from app.lib.cartography.standards.qa import standards_precompile_gate
from tests.cartography.fixtures.standards_cases import _generate

CASES_DIR = Path(__file__).parent / "fixtures" / "standards_cases"
CASE_DIRS = sorted(
    p for p in CASES_DIR.iterdir()
    if p.is_dir() and p.name != "__pycache__" and (p / "expected.json").exists()
)


def test_matrix_has_at_least_200_cases():
    assert len(CASE_DIRS) >= 200, len(CASE_DIRS)


@pytest.mark.cartography
@pytest.mark.parametrize("case_dir", CASE_DIRS, ids=[p.name for p in CASE_DIRS])
def test_fixture_case(case_dir: Path):
    mapspec = json.loads((case_dir / "mapspec.json").read_text(encoding="utf-8"))
    profile_axes = json.loads(
        (case_dir / "profile.json").read_text(encoding="utf-8"))["profile"]
    expected = json.loads((case_dir / "expected.json").read_text(encoding="utf-8"))

    if profile_axes is None:
        gate = standards_precompile_gate(mapspec)
    else:
        profile = resolve_profile(**profile_axes)
        gate = standards_precompile_gate(mapspec, profile=profile)

    report = gate["report"]
    got_rule_ids = sorted({v["rule_id"] for v in report["violations"]})
    assert got_rule_ids == expected["violations"], (
        f"{case_dir.name}: rule-id set drift")
    assert gate["verdict"] == expected["gate"], (
        f"{case_dir.name}: gate verdict drift")
    assert report["status"] == expected["status"], (
        f"{case_dir.name}: status drift")


def test_generator_is_byte_idempotent(tmp_path: Path):
    """Regenerating the matrix must reproduce the committed bytes exactly."""
    _generate.generate(tmp_path)
    for case_dir in CASE_DIRS:
        for name in ("mapspec.json", "profile.json", "expected.json"):
            committed = (case_dir / name).read_bytes()
            regenerated = (tmp_path / case_dir.name / name).read_bytes()
            assert committed == regenerated, f"{case_dir.name}/{name} drift"
