"""MapSpec Package (app/services/mapspec).

暴露深层 MapSpec 生命周期引擎 `MapSpecLifecycleEngine` 与意图值对象。
"""
from app.services.mapspec.lifecycle_engine import (
    MapSpecLifecycleEngine,
    mapspec_lifecycle_engine,
    MapSpecResult,
    InitProjectIntent,
    SetViewIntent,
    UpsertSourceIntent,
    UpsertLayerIntent,
    PatchComponentIntent,
    RemoveComponentIntent,
    DuplicateComponentIntent,
    RebindComponentIntent,
    PatchLayerPresentationIntent,
    RemoveLayerIntent,
    SetLayoutIntent,
    CheckpointIntent,
    RollbackIntent,
    # W15：统一锁 guard + 状态三分类 + override 分类（锁下沉唯一事实源）。
    LockGuardResult,
    guard_locked_partitions,
    guard_intent_locks,
    intent_lock_targets,
    is_entity_locked,
    locked_layer_ids_of,
    locked_component_ids_of,
    classify_override,
    strip_transient_state,
    LOCK_CONFLICT_CODE,
    COMPONENT_LOCK_CONFLICT_CODE,
    STATE_SEMANTIC,
    STATE_PRESENTATION,
    STATE_TRANSIENT,
    OVERRIDE_SEMANTIC,
    OVERRIDE_PRESENTATION,
    OVERRIDE_TEMPORARY_UI,
)
from app.services.mapspec.store import MapSpecStore, mapspec_store_instance

__all__ = [
    "MapSpecLifecycleEngine",
    "mapspec_lifecycle_engine",
    "MapSpecResult",
    "InitProjectIntent",
    "SetViewIntent",
    "UpsertSourceIntent",
    "UpsertLayerIntent",
    "PatchComponentIntent",
    "RemoveComponentIntent",
    "DuplicateComponentIntent",
    "RebindComponentIntent",
    "PatchLayerPresentationIntent",
    "RemoveLayerIntent",
    "SetLayoutIntent",
    "CheckpointIntent",
    "RollbackIntent",
    "LockGuardResult",
    "guard_locked_partitions",
    "guard_intent_locks",
    "intent_lock_targets",
    "is_entity_locked",
    "locked_layer_ids_of",
    "locked_component_ids_of",
    "classify_override",
    "strip_transient_state",
    "LOCK_CONFLICT_CODE",
    "COMPONENT_LOCK_CONFLICT_CODE",
    "STATE_SEMANTIC",
    "STATE_PRESENTATION",
    "STATE_TRANSIENT",
    "OVERRIDE_SEMANTIC",
    "OVERRIDE_PRESENTATION",
    "OVERRIDE_TEMPORARY_UI",
    "MapSpecStore",
    "mapspec_store_instance",
]
