"""initial schema

Revision ID: 85e4939d7e07
Revises: 
Create Date: 2026-07-20 00:10:11.235289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e4939d7e07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index('idx_document_status', ['status'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('share_code', sa.String(length=32), nullable=True),
    sa.Column('share_expires_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('idx_report_session', ['session_id'], unique=False)
        batch_op.create_index('idx_report_share', ['share_code'], unique=False)
        batch_op.create_index('idx_report_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_share_code'), ['share_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)

    op.create_table('uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('crs', sa.String(length=100), nullable=True),
    sa.Column('geometry_type', sa.String(length=50), nullable=True),
    sa.Column('feature_count', sa.BigInteger(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index('idx_chunk_document', ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('layers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('layer_type', sa.String(length=20), nullable=False),
    sa.Column('geometry_type', sa.String(length=50), nullable=True),
    sa.Column('source_format', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('crs', sa.String(length=100), nullable=True),
    sa.Column('bounds', sa.JSON(), nullable=True),
    sa.Column('feature_count', sa.BigInteger(), nullable=True),
    sa.Column('properties_def', sa.JSON(), nullable=True),
    sa.Column('style_config', sa.JSON(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('is_basemap', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_progress', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_layer_org_name')
    )
    with op.batch_alter_table('layers', schema=None) as batch_op:
        batch_op.create_index('idx_layer_created', ['created_at'], unique=False)
        batch_op.create_index('idx_layer_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_layers_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_layers_name'), ['name'], unique=False)

    op.create_table('analysis_tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.String(length=255), nullable=False),
    sa.Column('layer_id', sa.BigInteger(), nullable=True),
    sa.Column('result_layer_id', sa.BigInteger(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('progress_message', sa.String(length=255), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('error_trace', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['layer_id'], ['layers.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['result_layer_id'], ['layers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_task_celery', ['celery_task_id'], unique=False)
        batch_op.create_index('idx_task_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_tasks_celery_task_id'), ['celery_task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_analysis_tasks_status'), ['status'], unique=False)

    op.create_table('layer_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('granted_by', sa.String(length=255), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['layer_id'], ['layers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('layer_id', 'user_id', name='uq_permission')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('reasoning_content', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=255), nullable=True),
    sa.Column('tool_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('layer_permissions')
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_tasks_celery_task_id'))
        batch_op.drop_index('idx_task_status')
        batch_op.drop_index('idx_task_celery')

    op.drop_table('analysis_tasks')
    with op.batch_alter_table('layers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_layers_name'))
        batch_op.drop_index(batch_op.f('ix_layers_category'))
        batch_op.drop_index('idx_layer_status')
        batch_op.drop_index('idx_layer_created')

    op.drop_table('layers')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))

    op.drop_table('conversations')
    op.drop_table('users')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_document_id'))
        batch_op.drop_index('idx_chunk_document')

    op.drop_table('knowledge_chunks')
    op.drop_table('uploads')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_share_code'))
        batch_op.drop_index(batch_op.f('ix_reports_session_id'))
        batch_op.drop_index('idx_report_status')
        batch_op.drop_index('idx_report_share')
        batch_op.drop_index('idx_report_session')

    op.drop_table('reports')
    op.drop_table('organizations')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index('idx_document_status')

    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
