/**
 * W6（ADR-0118）：PDF 纠正 —— 单一标题事实源 + 文本层诚实化。
 *
 * 契约：
 * 1. ASCII（WinAnsi 可编码）title/subtitle → composeLayout 不在画布画标题
 *   （skipTitle），exportToPDF 以 doc.text 画一次（真矢量文本层保留）；
 * 2. 含非 WinAnsi 字符（code point > U+00FF，如 CJK）→ 反向：画布栅格化
 *   标题（composeLayout 正常画），doc.text 跳过 + `pdf_text_rasterized_cjk`
 *   诊断 —— 两处都不再出现双重标题；
 * 3. 系统消息如实描述：地图为位图画布 + 文本层矢量/栅格化状态（不再宣称
 *   "jsPDF 向量版"）。
 */
import { describe, it, expect, vi, beforeEach, type Mock } from 'vitest';
import {
  runExport,
  exportToPDF,
  MapExporterEngine,
  type ExportDeps,
  type ExportRequest,
} from './exporter';

vi.mock('@/lib/api/config', () => ({
  API_BASE: 'http://localhost:8001',
}));

vi.mock('@/lib/utils/logger', () => ({
  devOnly: { error: vi.fn(), warn: vi.fn(), info: vi.fn() },
}));

// jsPDF 假体：只记录调用面（text/addImage/output…），不触真实字体度量。
const jsdocCalls = { text: [] as string[] };
vi.mock('jspdf', () => ({
  default: class {
    internal = { pageSize: { getWidth: () => 297, getHeight: () => 210 } };
    addImage = vi.fn();
    setDrawColor = vi.fn();
    setLineWidth = vi.fn();
    rect = vi.fn();
    setFontSize = vi.fn();
    setTextColor = vi.fn();
    text = vi.fn((s: string) => jsdocCalls.text.push(String(s)));
    setProperties = vi.fn();
    output = vi.fn(() => new Blob(['pdf-data'], { type: 'application/pdf' }));
  },
}));

beforeEach(() => {
  vi.restoreAllMocks();
  jsdocCalls.text = [];
});

function mockFetchUpload(url = '/exports/map.pdf', filename = 'map.pdf') {
  const mockFetch = vi.fn((reqUrl: string) => {
    if (typeof reqUrl === 'string' && reqUrl.includes('/api/v1/export')) {
      return Promise.resolve({
        ok: true,
        json: async () => ({ url, filename }),
      } as any);
    }
    return Promise.resolve({
      ok: true,
      blob: async () => new Blob(['img-data'], { type: 'image/png' }),
    } as any);
  }) as Mock;
  vi.stubGlobal('fetch', mockFetch);
  return mockFetch;
}

function createDeps(): ExportDeps {
  const hudState = {
    theme: 'light' as const,
    layers: [],
    addExport: vi.fn(),
    setPendingSystemMessage: vi.fn(),
  };
  return {
    map: {
      getPixelRatio: vi.fn(() => 1),
      setPixelRatio: vi.fn(),
      getCanvas: vi.fn(() => {
        const canvas = document.createElement('canvas');
        canvas.width = 800;
        canvas.height = 600;
        return canvas;
      }),
      getCenter: vi.fn(() => ({ lat: 39.9, lng: 116.4 })),
      getZoom: vi.fn(() => 10),
      getBearing: vi.fn(() => 0),
      once: vi.fn((_event: string, cb: () => void) => cb()),
    } as any,
    getHudState: () => hudState,
  };
}

const fakeCanvas = {
  width: 800,
  height: 600,
  toDataURL: vi.fn(() => 'data:image/png;base64,xyz'),
} as any;

describe('exportToPDF text layer', () => {
  it('draws ASCII title/subtitle once via vector doc.text (default)', async () => {
    await exportToPDF(fakeCanvas, 'ASCII Title', 'sub', {});

    expect(jsdocCalls.text).toContain('ASCII Title');
    expect(jsdocCalls.text.filter((s) => s === 'ASCII Title')).toHaveLength(1);
    expect(jsdocCalls.text).toContain('sub');
  });

  it('skips title/subtitle doc.text in skip mode but keeps the footer', async () => {
    await exportToPDF(fakeCanvas, 'ASCII Title', 'sub', { textLayer: 'skip' });

    expect(jsdocCalls.text).not.toContain('ASCII Title');
    expect(jsdocCalls.text).not.toContain('sub');
    // 页脚保留（ASCII 标签 —— 不再使用 jsPDF 标准字体无法编码的中文前缀）
    expect(jsdocCalls.text.some((s) => s.startsWith('Date:'))).toBe(true);
  });

  it('footer labels are ASCII and drops non-WinAnsi values (metadata keeps them)', async () => {
    await exportToPDF(fakeCanvas, 'T', undefined, { author: '甲', dataSource: 'ok-src' });

    const footer = jsdocCalls.text.find((s) => s.includes('Generated by'))!;
    // ASCII 值保留、非 WinAnsi 值剔除（乱码比缺席更糟）
    expect(footer).toContain('Data: ok-src');
    expect(footer).not.toContain('甲');
    expect(footer).not.toContain('日期');
  });
});

describe('runExport PDF single title source', () => {
  it('CJK title: rasterized on canvas (no skipTitle) + pdf_text_rasterized_cjk + honest message', async () => {
    const deps = createDeps();
    mockFetchUpload('/exports/map.pdf', 'map.pdf');
    const composeSpy = vi.spyOn(MapExporterEngine, 'composeLayout');
    const pdfSpy = vi
      .spyOn(MapExporterEngine, 'exportToPDF')
      .mockResolvedValue(new Blob(['pdf-data'], { type: 'application/pdf' }));

    const req: ExportRequest = { title: '中文标题', format: 'pdf' };
    const outcome = await runExport(deps, req);

    expect(outcome.ok).toBe(true);
    // 画布路径照常画标题（skipTitle 不置位）
    expect(composeSpy).toHaveBeenCalledTimes(1);
    const composeArgs = composeSpy.mock.calls[0];
    expect(composeArgs[1]).toBe('中文标题');
    expect((composeArgs[3] as { skipTitle?: boolean }).skipTitle).toBeFalsy();
    // PDF 文本层跳过 title/subtitle
    expect(pdfSpy).toHaveBeenCalledTimes(1);
    const pdfArgs = pdfSpy.mock.calls[0];
    expect(pdfArgs[1]).toBe('中文标题');
    expect((pdfArgs[3] as { textLayer?: string }).textLayer).toBe('skip');
    // 系统消息如实描述 + 显式诊断
    const hudState = deps.getHudState();
    const finalMsg = hudState.setPendingSystemMessage.mock.calls.at(-1)[0] as string;
    expect(finalMsg).toContain('pdf_text_rasterized_cjk');
    expect(finalMsg).toContain('栅格化');
    expect(finalMsg).not.toContain('jsPDF 向量版');
  });

  it('ASCII title: canvas suppressed (skipTitle) + vector doc.text path + honest message', async () => {
    const deps = createDeps();
    mockFetchUpload('/exports/map.pdf', 'map.pdf');
    const composeSpy = vi.spyOn(MapExporterEngine, 'composeLayout');
    const pdfSpy = vi
      .spyOn(MapExporterEngine, 'exportToPDF')
      .mockResolvedValue(new Blob(['pdf-data'], { type: 'application/pdf' }));

    const req: ExportRequest = { title: 'ASCII Title', format: 'pdf' };
    const outcome = await runExport(deps, req);

    expect(outcome.ok).toBe(true);
    // 画布不再画标题（单一事实源：PDF 头部 doc.text 一次）
    const composeArgs = composeSpy.mock.calls[0];
    expect((composeArgs[3] as { skipTitle?: boolean }).skipTitle).toBe(true);
    const pdfArgs = pdfSpy.mock.calls[0];
    expect((pdfArgs[3] as { textLayer?: string }).textLayer).toBe('vector');
    const hudState = deps.getHudState();
    const finalMsg = hudState.setPendingSystemMessage.mock.calls.at(-1)[0] as string;
    expect(finalMsg).toContain('矢量');
    expect(finalMsg).not.toContain('jsPDF 向量版');
    expect(finalMsg).not.toContain('pdf_text_rasterized_cjk');
  });
});
