import { describe, it, expect } from "vitest";
import { resolveStyle, LayoutStyle } from "./layout-style";

describe("resolveStyle reducer", () => {
  it("light theme defaults", () => {
    const res = resolveStyle("light");
    expect(res.titleColor).toBe("#1e293b");
    expect(res.marginPx).toBe(56);
    expect(res.fontFamily).toBe("sans-serif");
    expect(res.watermarkText).toBe("Generated by WebGIS AI Agent");
  });

  it("dark theme defaults", () => {
    const res = resolveStyle("dark");
    expect(res.titleColor).toBe("#00f2ff");
    expect(res.accentColor).toBe("#38bdf8");
  });

  it("preset: 学术论文 serif/black style overrides", () => {
    const styleOverride: LayoutStyle = {
      fontFamily: "Georgia, serif",
      titleColor: "#0f172a",
      accentColor: "#334155",
      graticuleColor: "#cbd5e1",
    };
    const res = resolveStyle("light", styleOverride);
    expect(res.fontFamily).toBe("Georgia, serif");
    expect(res.titleColor).toBe("#0f172a");
    expect(res.accentColor).toBe("#334155");
    expect(res.graticuleColor).toBe("#cbd5e1");
    // Non-overridden fallback
    expect(res.watermarkText).toBe("Generated by WebGIS AI Agent");
  });

  it("preset: 汇报演示 dark style overrides", () => {
    const styleOverride: LayoutStyle = {
      fontFamily: "Inter, sans-serif",
      titleColor: "#38bdf8",
      accentColor: "#0ea5e9",
      marginPx: 16,
    };
    const res = resolveStyle("dark", styleOverride);
    expect(res.fontFamily).toBe("Inter, sans-serif");
    expect(res.titleColor).toBe("#38bdf8");
    expect(res.marginPx).toBe(16);
  });

  it("preset: 极简 export style overrides", () => {
    const styleOverride: LayoutStyle = {
      marginPx: 8,
    };
    const res = resolveStyle("light", styleOverride);
    expect(res.marginPx).toBe(8);
    expect(res.titleColor).toBe("#1e293b");
  });
});
