export interface LayoutStyle {
  titleColor?: string;
  titleFont?: string;
  accentColor?: string;
  marginPx?: number;
  fontFamily?: string;
  graticuleColor?: string;
  watermarkText?: string;
}

export type ResolvedLayoutStyle = Required<LayoutStyle>;

export function resolveStyle(
  theme: "light" | "dark" = "light",
  style?: LayoutStyle
): ResolvedLayoutStyle {
  const isDark = theme === "dark";

  const defaults: ResolvedLayoutStyle = {
    titleColor: isDark ? "#00f2ff" : "#1e293b",
    titleFont: "bold 32px sans-serif",
    accentColor: isDark ? "#38bdf8" : "#2563eb",
    marginPx: 56,
    fontFamily: "sans-serif",
    graticuleColor: isDark ? "rgba(255,255,255,0.15)" : "rgba(0,0,0,0.12)",
    watermarkText: "Generated by WebGIS AI Agent",
  };

  if (!style) {
    return defaults;
  }

  return {
    titleColor: style.titleColor ?? defaults.titleColor,
    titleFont: style.titleFont ?? defaults.titleFont,
    accentColor: style.accentColor ?? defaults.accentColor,
    marginPx: style.marginPx ?? defaults.marginPx,
    fontFamily: style.fontFamily ?? defaults.fontFamily,
    graticuleColor: style.graticuleColor ?? defaults.graticuleColor,
    watermarkText: style.watermarkText ?? defaults.watermarkText,
  };
}
