"""扩展平台测试的全局状态隔离（fixture 自动生效）。

扩展激活把 cartography 组件投进进程级 ComponentRegistry；runtime
manifest（§5 组件表投影）与 harness 组件组合测试都假设「干净的内置
注册表」。本包测试会激活各种演示扩展（acme.* / extdemo.*），不恢复
就会泄漏到同进程后续测试 —— CI 全量顺序下已实录两例：

- test_component_composition::test_component_registry 的 validate()
  因泄漏的扩展组件缺 renderer 支持矩阵而红；
- test_scientific_contracts_vnext::test_fingerprint_stable_and_sensitive
  的 manifest 指纹因组件表混入扩展组件而失稳。

每个测试后：unregister 全部本测试新增的组件（公开 API，代次单调递增
自动失效派生缓存），并 refresh runtime manifest 单例。
"""
from __future__ import annotations

from types import SimpleNamespace
from typing import Any, Optional

import pytest


@pytest.fixture(autouse=True)
def _restore_global_component_registry():
    from app.lib.cartography.component_registry import get_component_registry

    reg = get_component_registry()
    baseline_ids = set(reg.all_ids)
    yield
    leaked = set(reg.all_ids) - baseline_ids
    for cid in leaked:
        reg.unregister(cid)
    if leaked:
        from app.lib.gis.runtime_manifest import get_runtime_manifest

        get_runtime_manifest(refresh=True)


# ── V4（ADR-0199）认证测试 pack 工厂 ─────────────────────────────────────
# 在 tmp_path 下程序化生成最小 v4 pack（manifest + main.py），参数注入
# 缺陷（幽灵声明 / 非确定性 / latency 谎报 / 坏 skill 契约）。命名空间
# 固定 certv4：算法 registry 是进程级单例，fixture finally 幂等清理。

V4_NAMESPACE = "certv4"
V4_EXTENSION_ID = f"{V4_NAMESPACE}.pack"
V4_PROJECTED_TOOL = f"{V4_NAMESPACE}_rect_area"
V4_PROJECTED_ALGORITHM = f"{V4_NAMESPACE}.rect_area_algo"

_V4_PROBE_ARGS = {"xmin": 0, "ymin": 0, "xmax": 3, "ymax": 2}

_V4_MAIN_TEMPLATE = '''"""certv4 test pack entry (generated by the v4 conftest factory)."""
from __future__ import annotations

from app.extensions_platform.sdk import (
    AlgorithmExtensionSpec,
    NumericalSmokeCase,
    ToolExtensionSpec,
)


async def _rect_area_run_async(xmin: float, ymin: float, xmax: float, ymax: float) -> dict:
    if xmax <= xmin or ymax <= ymin:
        raise ValueError("degenerate bbox")
    return {{"area": (xmax - xmin) * (ymax - ymin)}}


def _rect_area_run(xmin: float, ymin: float, xmax: float, ymax: float) -> dict:
    if xmax <= xmin or ymax <= ymin:
        raise ValueError("degenerate bbox")
{extra_body}
    return {{"area": (xmax - xmin) * (ymax - ymin){result_suffix}}}


_RECT_AREA_IMPL = _rect_area_run_async if {async_flag} else _rect_area_run


TOOLS = [
    ToolExtensionSpec(
        name="rect_area",
        description="Axis-aligned bbox planar area (test pack).",
        func=_RECT_AREA_IMPL,
        side_effect="pure",
{tool_kwargs}
    ),
]

ALGORITHMS = [
    AlgorithmExtensionSpec(
        id="rect_area_algo",
        name="rect_area_algo",
        description="Bbox area algorithm (test pack).",
        tool_candidates=["{projected_tool}"],
        smoke_cases=[
            NumericalSmokeCase(
                arguments={{"xmin": 0, "ymin": 0, "xmax": 2, "ymax": 2}},
                expect_key="area",
                expect_value=4.0,
            )
        ],
    ),
]


def activate(ctx) -> None:
    for spec in TOOLS:
        ctx.register_tool(spec)
    for spec in ALGORITHMS:
        ctx.register_algorithm(spec)
'''


def _v4_cleanup_singletons() -> None:
    from app.lib.gis.algorithm_registry import get_algorithm_registry
    from app.services.data_fabric.registry import get_registry

    get_algorithm_registry().unregister(V4_PROJECTED_ALGORITHM)
    get_registry().unregister(f"{V4_NAMESPACE}_demo_source")


def _build_v4_pack(
    root,
    *,
    api_version: str = "1.3.0",
    extension_id: str = V4_EXTENSION_ID,
    ghost_tool: bool = False,
    nondeterministic: bool = False,
    latency_class: Optional[str] = None,
    result_size_policy: Optional[str] = None,
    async_tool: bool = False,
    oversized_result: bool = False,
    skill_contract: Optional[dict[str, Any]] = None,
    skill_id: str = "area_skill",
    probe_expect_value: Any = 6.0,
    certification_section: bool = True,
    pack_dirname: str = "certv4-pack",
):
    import json

    namespace, name = extension_id.split(".")
    pack = root / pack_dirname
    pack.mkdir(parents=True, exist_ok=True)

    tools_declared = [
        {
            "name": "rect_area",
            "description": "Axis-aligned bbox planar area.",
            "tier": 1,
            "side_effect": "pure",
        }
    ]
    if ghost_tool:
        tools_declared.append(
            {
                "name": "ghost_tool",
                "description": "Declared but never implemented.",
                "tier": 1,
                "side_effect": "pure",
            }
        )

    manifest = {
        "schema_version": 1,
        "id": extension_id,
        "name": name,
        "namespace": namespace,
        "version": "1.0.0",
        "api_version": api_version,
        "minimum_core_version": "0.1.0",
        "title": "CertV4 Test Pack",
        "description": "Programmatic v4 certification fixture.",
        "trust": "local_untrusted",
        "extension_types": ["tools", "algorithms"],
        "entry_point": "main",
        "tools": tools_declared,
        "algorithms": [
            {
                "id": "rect_area_algo",
                "description": "Bbox area algorithm.",
                "scientific_status": "EXPERIMENTAL",
            }
        ],
    }
    if certification_section:
        manifest["certification"] = {
            "tools": {
                "rect_area": {
                    "args": dict(_V4_PROBE_ARGS),
                    "replay": True,
                    "expect_key": "area",
                    "expect_value": probe_expect_value,
                    "tolerance": 1e-9,
                }
            },
            "algorithms": {
                "rect_area_algo": {
                    "args": dict(_V4_PROBE_ARGS),
                    "replay": True,
                    "expect_key": "area",
                    "expect_value": probe_expect_value,
                    "tolerance": 1e-9,
                }
            },
        }
    if skill_contract is not None:
        manifest["skills"] = [{"skill_id": skill_id, "contract": skill_contract}]

    (pack / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    extra_body = ""
    tool_kwargs = ""
    result_suffix = ""
    if nondeterministic:
        extra_body = "    import uuid\n    nonce = uuid.uuid4().hex\n"
        result_suffix = ', "nonce": nonce'
    if oversized_result:
        extra_body += "    blob = 'x' * 40000\n"
        result_suffix += ', "blob": blob'
    if latency_class:
        tool_kwargs += f'        latency_class="{latency_class}",\n'
        extra_body += "    import time\n    time.sleep(0.05)\n"
    if result_size_policy:
        tool_kwargs += f'        result_size_policy="{result_size_policy}",\n'
    (pack / "main.py").write_text(
        _V4_MAIN_TEMPLATE.format(
            extra_body=extra_body,
            tool_kwargs=tool_kwargs,
            result_suffix=result_suffix,
            async_flag=async_tool,
            projected_tool=f"{namespace}_rect_area",
        ),
        encoding="utf-8",
    )
    return pack


V4_VALID_SKILL_CONTRACT: dict[str, Any] = {
    "name": "Area Skill",
    "description": "Test skill for area workflows.",
    "domain": "general",
    "version": "1.0.0",
    "procedure": {
        "steps": [
            {"step_id": "s1", "title": "Compute area", "kind": "analyze"},
        ]
    },
}

# 缺 procedure（SkillContract 必填）→ schema 阶段 fail。
V4_INVALID_SKILL_CONTRACT: dict[str, Any] = {
    "name": "Broken Skill",
    "domain": "general",
}


@pytest.fixture()
def v4_env(tmp_path):
    """认证测试环境：build() 生成 pack，make_host() 发现并返回 host。

    无论断言成败，finally 幂等清理进程级单例 registry 中的投影。
    """
    from app.extensions_platform.host import ExtensionHost, HostPolicy
    from app.tools.registry import ToolRegistry

    _v4_cleanup_singletons()

    def make_host(roots=None, **policy_kwargs):
        tool_registry = ToolRegistry()
        host = ExtensionHost(
            tool_registry=tool_registry,
            policy=HostPolicy(
                roots=tuple(roots) if roots else (tmp_path,),
                builtin_ids=frozenset(policy_kwargs.pop("builtin_ids", {V4_EXTENSION_ID})),
                **policy_kwargs,
            ),
        )
        host.discover()
        return host, tool_registry

    def build(**kwargs):
        return _build_v4_pack(tmp_path, **kwargs)

    yield SimpleNamespace(tmp_path=tmp_path, build=build, make_host=make_host)
    _v4_cleanup_singletons()
