"""决策 / 交付物域组合包（ADR-0101 §B2）。

- site_selection_decision / mcda_score_report：决策场景（决策面板可选、
  方法论披露可选）；
- government_report_map / executive_summary_map / public_health_report /
  natural_resource_inventory：面向具体交付形态的版式。
"""
from __future__ import annotations

from typing import List

from app.lib.cartography.composition_packs._base import (
    attribution_slot,
    charts_slot,
    composition,
    export_slot,
    legend_slot,
    map_border_slot,
    north_arrow_slot,
    scale_bar_slot,
    stats_slot,
    subtitle_slot,
    title_slot,
)
from app.lib.cartography.composition_templates import ComponentSlot, MapCompositionTemplate

DECISION_PACK: List[MapCompositionTemplate] = [
    composition(
        cid="composition.site_selection_decision",
        name="Site Selection Decision Map",
        description="选址决策版式：适宜性分级 + 决策面板（候选排名）可选 + "
                    "统计 + 图表 + A4 横版。",
        models=["site_selection_result", "suitability_classes", "mcda_score_map"],
        outputs=["interactive", "png", "pdf"],
        profile="report",
        fallback="composition.statistical_report",
        priority=52,
        tags=["decision", "site-selection", "report"],
        slots=[
            title_slot(preferred_templates=["title/report"]),
            subtitle_slot(),
            legend_slot(["legend"],
                        cardinality="required", required=True,
                        preferred_templates=["legend/report"]),
            north_arrow_slot(),
            scale_bar_slot(),
            attribution_slot(),
            ComponentSlot(id="decision_panel", category="disclosure.decision_panel",
                          allowed_component_types=["decision_panel"],
                          cardinality="optional", position_zone="top-left",
                          fallback_zones=["top-right"]),
            ComponentSlot(id="methodology_note", category="disclosure.methodology_note",
                          allowed_component_types=["methodology_note"],
                          # 模型 pitfalls 声明『必须随图披露』→ 组合层给
                          # recommended（context 缺席才合法缺席，缺席即告警）
                          cardinality="recommended", position_zone="bottom-left"),
            stats_slot(cardinality="recommended"),
            charts_slot(max_count=2),
            export_slot(cardinality="required", required=True,
                        preferred_templates=["export-layout/A4-landscape"]),
        ],
    ),
    composition(
        cid="composition.mcda_score_report",
        name="MCDA Score Report",
        description="MCDA 评分报告版式：评分分级面 + 方法论披露（权重来源）+ "
                    "统计 + 图表。",
        models=["mcda_score_map", "suitability_classes", "vulnerability_index"],
        outputs=["interactive", "png", "pdf"],
        profile="report",
        fallback="composition.statistical_report",
        priority=53,
        tags=["decision", "mcda", "disclosure"],
        slots=[
            title_slot(preferred_templates=["title/report"]),
            subtitle_slot(),
            legend_slot(["legend"],
                        cardinality="required", required=True,
                        preferred_templates=["legend/report"]),
            north_arrow_slot(),
            scale_bar_slot(),
            attribution_slot(),
            ComponentSlot(id="methodology_note", category="disclosure.methodology_note",
                          allowed_component_types=["methodology_note"],
                          # weightSource 必须显式（模型 pitfalls）→ recommended
                          cardinality="recommended", position_zone="bottom-left"),
            stats_slot(cardinality="recommended"),
            charts_slot(max_count=3),
            map_border_slot(cardinality="required", required=True,
                            preferred_templates=["frame/report"]),
            export_slot(cardinality="required", required=True,
                        preferred_templates=["export-layout/A4-portrait"]),
        ],
    ),
]

DELIVERABLES_PACK: List[MapCompositionTemplate] = [
    composition(
        cid="composition.government_report_map",
        name="Government Report Map",
        description="政府成果图版式：公文标题（加宽字距）+ neatline 图框 + "
                    "双单位比例尺 + A4 竖版，正式汇报产物。",
        models=["administrative_choropleth", "normalized_choropleth",
                "diverging_choropleth", "zoning_planning", "risk_exposure_classes",
                "equity_assessment"],
        outputs=["png", "pdf"],
        profile="report",
        fallback="composition.report_map",
        priority=54,
        tags=["government", "formal", "report"],
        slots=[
            title_slot(preferred_templates=["title/government"]),
            subtitle_slot(preferred_templates=["subtitle/report"]),
            legend_slot(["legend", "categorical_legend"],
                        cardinality="required", required=True,
                        preferred_templates=["legend/report"]),
            north_arrow_slot(preferred_templates=["north-arrow/monochrome"]),
            scale_bar_slot(preferred_templates=["scale-bar/dual-unit"]),
            attribution_slot(preferred_templates=["attribution/compact"]),
            map_border_slot(cardinality="required", required=True,
                            preferred_templates=["frame/neatline"]),
            stats_slot(),
            export_slot(cardinality="required", required=True,
                        preferred_templates=["export-layout/A4-portrait"]),
        ],
    ),
    composition(
        cid="composition.executive_summary_map",
        name="Executive Summary Map",
        description="执行摘要版式：演示标题 + KPI 指标卡 + 紧凑图例，"
                    "一图一页的决策摘要。",
        models=["administrative_choropleth", "aggregate_grid", "visual_heatmap",
                "proportional_symbol", "site_selection_result"],
        outputs=["interactive", "png"],
        profile="presentation",
        fallback="composition.presentation_map",
        priority=55,
        tags=["executive", "kpi", "presentation"],
        slots=[
            title_slot(preferred_templates=["title/presentation"]),
            subtitle_slot(),
            legend_slot(["legend", "categorical_legend", "continuous_colorbar"],
                        preferred_templates=["legend/compact"]),
            north_arrow_slot(required=False),
            scale_bar_slot(),
            attribution_slot(preferred_templates=["attribution/compact"]),
            ComponentSlot(id="statistics_panel", category="analysis.statistics_panel",
                          allowed_component_types=["statistics_panel"],
                          cardinality="recommended",
                          position_zone="top-left",
                          preferred_templates=["statistics-panel/kpi"]),
        ],
    ),
    composition(
        cid="composition.public_health_report",
        name="Public Health Report Map",
        description="公共卫生报告版式：分级面 + 统计 + 图表 + 方法论披露可选 + "
                    "A4 竖版。",
        models=["administrative_choropleth", "normalized_choropleth",
                "vulnerability_index", "equity_assessment", "hotspot_overlay"],
        outputs=["interactive", "png", "pdf"],
        profile="report",
        fallback="composition.statistical_report",
        priority=56,
        tags=["public-health", "report"],
        slots=[
            title_slot(preferred_templates=["title/report"]),
            subtitle_slot(),
            legend_slot(["legend"],
                        cardinality="required", required=True,
                        preferred_templates=["legend/report"]),
            north_arrow_slot(),
            scale_bar_slot(),
            attribution_slot(),
            ComponentSlot(id="methodology_note", category="disclosure.methodology_note",
                          allowed_component_types=["methodology_note"],
                          cardinality="optional", position_zone="bottom-left"),
            stats_slot(cardinality="recommended"),
            charts_slot(max_count=2),
            map_border_slot(cardinality="required", required=True,
                            preferred_templates=["frame/report"]),
            export_slot(cardinality="required", required=True,
                        preferred_templates=["export-layout/A4-portrait"]),
        ],
    ),
    composition(
        cid="composition.natural_resource_inventory",
        name="Natural Resource Inventory Map",
        description="自然资源本底版式：分类面（地类/林相/权属）+ 横向图例 + "
                    "表格面板可选（interactive）+ A4 横版。",
        models=["zoning_planning", "categorical_thematic"],
        outputs=["interactive", "png", "pdf"],
        profile="report",
        fallback="composition.report_map",
        priority=57,
        tags=["inventory", "natural-resources", "categorical"],
        slots=[
            title_slot(preferred_templates=["title/report"]),
            legend_slot(["categorical_legend"],
                        cardinality="required", required=True, max_count=2,
                        preferred_templates=["categorical-legend/horizontal"]),
            north_arrow_slot(),
            scale_bar_slot(),
            attribution_slot(),
            ComponentSlot(id="table_panel", category="analysis.table_panel",
                          allowed_component_types=["table_panel"],
                          cardinality="optional", max_count=1,
                          position_zone="bottom-right"),
            map_border_slot(cardinality="required", required=True,
                            preferred_templates=["frame/report"]),
            export_slot(cardinality="required", required=True,
                        preferred_templates=["export-layout/A4-landscape"]),
        ],
    ),
]
