"""时序 / 风险环境 / 规划公平域组合包（ADR-0101 §B2）。"""
from __future__ import annotations

from typing import List

from app.lib.cartography.composition_packs._base import (
    attribution_slot,
    charts_slot,
    composition,
    export_slot,
    legend_slot,
    map_border_slot,
    north_arrow_slot,
    scale_bar_slot,
    stats_slot,
    subtitle_slot,
    title_slot,
)
from app.lib.cartography.composition_templates import ComponentSlot, MapCompositionTemplate

TEMPORAL_CHANGE_PACK: List[MapCompositionTemplate] = [
    composition(
        cid="composition.temporal_change_report",
        name="Temporal Change Report",
        description="时序变化报告版式：发散变化面（中点=无变化）+ 统计面板 + "
                    "图表 + A4 版式。",
        models=["change_comparison_map", "diverging_choropleth"],
        outputs=["interactive", "png", "pdf"],
        profile="report",
        fallback="composition.statistical_report",
        priority=47,
        tags=["temporal", "change", "report"],
        slots=[
            title_slot(preferred_templates=["title/report"]),
            subtitle_slot(),
            legend_slot(["legend", "continuous_colorbar"],
                        cardinality="required", required=True,
                        preferred_templates=["legend/report"]),
            north_arrow_slot(),
            scale_bar_slot(),
            attribution_slot(),
            stats_slot(cardinality="recommended"),
            charts_slot(max_count=2),
            map_border_slot(cardinality="required", required=True,
                            preferred_templates=["frame/report"]),
            export_slot(cardinality="required", required=True,
                        preferred_templates=["export-layout/A4-portrait"]),
        ],
    ),
]

RISK_ENVIRONMENT_PACK: List[MapCompositionTemplate] = [
    composition(
        cid="composition.risk_exposure_report",
        name="Risk Exposure Report",
        description="风险暴露报告版式：风险分级面 + 统计面板 + 图表 + "
                    "A4 版式；不确定性披露为可选槽（interactive 生效）。",
        models=["risk_exposure_classes", "vulnerability_index", "hotspot_overlay"],
        outputs=["interactive", "png", "pdf"],
        profile="report",
        fallback="composition.statistical_report",
        priority=48,
        tags=["risk", "exposure", "report"],
        slots=[
            title_slot(preferred_templates=["title/report"]),
            subtitle_slot(),
            legend_slot(["legend"],
                        cardinality="required", required=True,
                        preferred_templates=["legend/report"]),
            north_arrow_slot(),
            scale_bar_slot(),
            attribution_slot(),
            ComponentSlot(id="uncertainty_panel", category="disclosure.uncertainty_panel",
                          allowed_component_types=["uncertainty_panel"],
                          cardinality="optional", position_zone="bottom-right",
                          fallback_zones=["bottom-left"]),
            stats_slot(cardinality="recommended"),
            charts_slot(max_count=2),
            map_border_slot(cardinality="required", required=True,
                            preferred_templates=["frame/report"]),
            export_slot(cardinality="required", required=True,
                        preferred_templates=["export-layout/A4-portrait"]),
        ],
    ),
    composition(
        cid="composition.environment_monitoring",
        name="Environment Monitoring Map",
        description="环境监测版式：连续场 + colorbar + 图表 + A4 横版。",
        models=["raster_surface", "spectral_index_surface", "terrain_analytical_surface"],
        outputs=["interactive", "png", "pdf"],
        profile="standard",
        fallback="composition.density_exploration",
        priority=49,
        tags=["environment", "monitoring", "raster"],
        slots=[
            title_slot(),
            legend_slot(["continuous_colorbar"],
                        cardinality="required", required=True, max_count=2,
                        zone="bottom-right",
                        preferred_templates=["colorbar/horizontal"]),
            north_arrow_slot(),
            scale_bar_slot(fallback_zones=["bottom-center"]),
            attribution_slot(),
            charts_slot(max_count=2),
            map_border_slot(cardinality="optional"),
            export_slot(cardinality="optional",
                        preferred_templates=["export-layout/A4-landscape"]),
        ],
    ),
]

PLANNING_EQUITY_PACK: List[MapCompositionTemplate] = [
    composition(
        cid="composition.zoning_plan_map",
        name="Zoning / Land-use Plan Map",
        description="区划/用地图版式：横向分类图例 + compact 归属 + 图框，"
                    "规划成果的公开表达。",
        models=["zoning_planning", "categorical_thematic"],
        outputs=["png", "pdf", "svg"],
        profile="report",
        fallback="composition.report_map",
        priority=50,
        tags=["planning", "zoning", "land-use"],
        slots=[
            title_slot(preferred_templates=["title/government"]),
            subtitle_slot(),
            legend_slot(["categorical_legend"],
                        cardinality="required", required=True, max_count=2,
                        preferred_templates=["categorical-legend/horizontal"]),
            north_arrow_slot(),
            scale_bar_slot(preferred_templates=["scale-bar/dual-unit"]),
            attribution_slot(preferred_templates=["attribution/compact"]),
            map_border_slot(cardinality="required", required=True,
                            preferred_templates=["frame/neatline"]),
            export_slot(cardinality="required", required=True,
                        preferred_templates=["export-layout/A4-portrait"]),
        ],
    ),
    composition(
        cid="composition.equity_assessment_report",
        name="Equity Assessment Report",
        description="公平性评估版式：发散评估面 + 方法论披露（分母/指标口径）+ "
                    "统计面板 + A4 版式。",
        models=["equity_assessment", "normalized_choropleth", "diverging_choropleth"],
        outputs=["interactive", "png", "pdf"],
        profile="report",
        fallback="composition.statistical_report",
        priority=51,
        tags=["equity", "report", "disclosure"],
        slots=[
            title_slot(preferred_templates=["title/report"]),
            subtitle_slot(),
            legend_slot(["legend"],
                        cardinality="required", required=True,
                        preferred_templates=["legend/report"]),
            north_arrow_slot(),
            scale_bar_slot(),
            attribution_slot(),
            ComponentSlot(id="methodology_note", category="disclosure.methodology_note",
                          allowed_component_types=["methodology_note"],
                          cardinality="optional", position_zone="bottom-left"),
            stats_slot(cardinality="recommended"),
            charts_slot(max_count=2),
            map_border_slot(cardinality="required", required=True,
                            preferred_templates=["frame/report"]),
            export_slot(cardinality="required", required=True,
                        preferred_templates=["export-layout/A4-portrait"]),
        ],
    ),
]
