# -*- coding: utf-8 -*-
"""Build review/qa-loop/round-2.pool.csv from verified gis_harness scan findings."""
import csv, hashlib

# (sev, cat, file, line, excerpt, issue, blast, cost_lines, risk)
rows = [
 (1,"correctness","app/services/gis_harness/tool_surface.py",149,"done_states = {complete, completed, skipped, done, ok}","done-set omits available which _mark_progress writes to satisfied data rows (session_plan.py:522) - phase stuck at PHASE_DATA, analysis domains never activated in pi path",7,2,1),
 (1,"correctness","app/services/gis_harness/map_critique.py",79,"str(k): v for k, v in (observation.get(layers) or {}).items()","_observed_layers assumes layers is dict but canonical payload is list (chat_schema.py:147) - AttributeError swallowed by pipeline except -> all five V7 critique checks silently disabled",8,20,1),
 (1,"correctness","app/services/gis_harness/recipes.py",233,"unique_ratio=_ratio_or_none(meta.get(uniqueRatio))","EligibilityContext reads uniqueRatio/missingRatio keys but producer emits type+null_ratio (dataset_profile.py) - V4 field-cardinality/missing-ratio gates fail open on every real profile",6,6,1),
 (1,"correctness","app/services/gis_harness/planner.py",698,"candidates=[str(getattr(c, id, )) for c in (candidates or [])][:8],","candidates only bound on the fallback path - explicit recipe_id path raises UnboundLocalError swallowed by except -> CANDIDATE_WORKFLOWS/SELECTED_WORKFLOW evidence chain missing for most production plans",6,2,1),
 (1,"correctness","app/services/gis_harness/trace_store.py",327,"if not pass_protected and seg_protected >= count: break","oldest-segment-fully-protected breaks out of the whole eviction pass instead of continuing to newer segments - pass 2 force-evicts oldest PROTECTED records while droppable newer ones survive, violating documented eviction order",4,8,1),
 (1,"correctness","app/services/gis_harness/tools.py",608,"overlay_refs = list(overlay_refs or [])","documented overlay/boundary refs input normalized then never read - product silently incomplete for agents passing auxiliary refs; delivery machinery exists, consumer missing",5,8,1),
 (1,"error-handling","app/services/gis_harness/tools.py",806,"converted, _, _warn = convert_analysis_to_mapspec_layer(analysis_payload)","converter warnings (third tuple element) assigned to _warn and dropped at both call sites - degradation disclosures die at this seam",4,4,1),
 (1,"correctness","app/services/gis_harness/components.py",1234,"if chartRef in bindings:","rebind_component never removes stale inline options.chart when rebinding chart_panel - renderer inline-first keeps showing old chart while binding claims new ref; mutate_component sibling path pops correctly",5,6,1),
 (1,"correctness","app/services/gis_harness/plan_candidates.py",505,"top1 = next((c for c in candidates if c.kind == recipe), None)","after feasible-first sort the first recipe-kind candidate is not the routing top-1 - rerouted stays False exactly in the blocked-top-1 scenario the zero-drift rewrite was built for",4,4,1),
 (1,"correctness","app/services/gis_harness/completion/pipeline.py",121,"return findings[:MAX_FINDINGS]","_validate_all truncates to 12 findings before status computation at :285 whose own comment says status must judge full findings - 13th+ errors silently dropped, unrepairable error can be misjudged complete",6,6,1),
 (1,"correctness","app/services/gis_harness/runtime_state_machine.py",295,"return verdict.startswith(READY) and final_status in (","legacy map_product block missing product_verdict key -> verdict None -> AttributeError propagating out of derive_runtime_phase, swallowed by all production callers - V7 state machine silently frozen",8,2,1),
 (1,"correctness","app/services/gis_harness/completion/pipeline.py",415,"if final_gate and str(stored.get(product_verdict) or ()) not in _READY_VERDICTS:","map_product_block persists derive_product_verdict dict; str(dict) never in READY verdicts - final_gate dedup never skips, full finalization re-runs every turn-settle breaking documented idempotency",6,4,1),
 (1,"correctness","app/services/gis_harness/workflow_instance.py",615,"str(chapter.get(workflow_contract) or ),","writer coerces contract to str so gate_fingerprint isinstance(dict) never fires and contract component always empty; reader passes raw dict - fingerprints never match when contract exists, documented skip-gate dead, full re-derive every trigger",7,4,1),
 (2,"correctness","app/services/gis_harness/tool_surface.py",123,"return PHASE_PLANNING, (no plan steps -> planning)","missing trailing comma makes evidence a bare str - evidence.extend appends 24 single chars when plan has zero steps; diagnostic-only",1,1,1),
 (2,"correctness","app/services/gis_harness/plan_graph.py",339,"output_ref=str(req.get(bound_ref) or step.get(bound_ref) or ),","output_ref is a copy-paste duplicate of bound_ref, never an independent produced-ref; fallback consumer dead",2,2,1),
 (2,"resource","app/services/gis_harness/capability_graph.py",553,"fp = hashlib.sha256(json.dumps(source_fingerprints()...","every get_capability_graph call recomputes fingerprints under global lock constructing fresh ModelRegistryStore with full disk glob - per-request disk I/O serializing all planning callers",5,5,1),
 (2,"error-handling","app/services/gis_harness/completion/repairs.py",151,"except Exception: return set()","provenance read failure fail-opens to empty removal set bypassing user-wins guard - repair can resurrect user-deleted components",3,3,1),
 (2,"error-handling","app/services/gis_harness/context_layers.py",405,"except Exception:  # checkpoint 失败不阻断","one broad except silently skips entire checkpoint write incl int() type errors - stale layers persist with debug-level trace",4,4,1),
 (2,"concurrency","app/services/gis_harness/failure_taxonomy.py",270,"self._counts[key] = [1, now]","TTL-expired reset assigns without move_to_end - just-reset key can be LRU-evicted ahead of older unexpired keys; attempt budgets under-count",2,2,1),
 (2,"duplication","app/services/gis_harness/gis_ontology.py",1648,"if _re.search(rf(?<![a-z])...)","keyword matching implemented twice (match_intent inline + _keyword_hit_count) with import re inside per-keyword loop - match scoring and escalation scoring can drift",3,5,1),
 (2,"deadcode","app/services/gis_harness/plan_graph.py",351,"def _dep_satisfied(graph: PlanGraph, dep_capability: str)","zero callers - superseded by inner _sat closure",1,1,1),
 (2,"deadcode","app/services/gis_harness/failure_taxonomy.py",204,"def from_geocompute_failure_class(geo_fc)","zero production callers for exported adapter",1,1,1),
 (2,"deadcode","app/services/gis_harness/workflow_v4/package.py",100,"def next_version(previous: Optional[str], *, change: str,)","zero production callers for version bump helper",1,1,1),
 (2,"correctness","app/services/gis_harness/workflow_v4/package.py",107,"cur = parse_semver(previous or 1.0.0) or (1, 0, 0)","malformed semver silently coerced to 1.0.0 contradicting own no-silent-degrade contract (only guards change arg)",1,2,1),
 (2,"deadcode","app/services/gis_harness/component_composer.py",173,"if title_text and not options.get(title): pass","no-op branch with pass body - unfinished intent evaluated on every composition",1,1,1),
 (2,"hardcoding","app/services/gis_harness/component_composer.py",60,"attribution_text: str = (c) OpenStreetMap contributors","default attribution hardcoded to OSM regardless of actual data source",3,2,1),
 (2,"concurrency","app/services/gis_harness/gis_ontology.py",1742,"if _singleton is None: _singleton = TaskOntology()","unlocked lazy singleton (same at component_composer.py:308); reset swaps object under live readers",2,3,1),
 (2,"typing","app/services/gis_harness/gis_ontology.py",1809,"assert desc is not None","assert-based narrowing stripped under -O leaving AttributeError path",1,1,1),
 (2,"correctness","app/services/gis_harness/map_verification.py",251,"desc = descriptors.get(str(ref))","absent-from-descriptors treated as confirmed eviction though inputs.py pops unknown refs on storage jitter; no ref: prefix filter unlike siblings - false eviction warnings downgrade FINAL_MAP_VERIFIED",4,5,1),
 (2,"deadcode","app/services/gis_harness/map_critique.py",180,"bbox = observation.get(result_bbox)","check_invalid_bounds reads result_bbox no producer writes into observations - C_INVALID_BOUNDS check dead in production",2,2,1),
 (2,"correctness","app/services/gis_harness/map_critique.py",58,"comps = mapspec.get(components)","reads top-level components but MapSpec stores layout.components; exports gate reads a key no producer writes - check_publication_components doubly inert",2,3,1),
 (2,"correctness","app/services/gis_harness/recipes.py",552,"feature_count = int(feature_count) if isinstance(...) else 0","absent featureCount coerced to 0 -> INSUFFICIENT_POINTS false failures contradicting facts-absent-equals-unknown contract; data_qualification.py:451 skips correctly",3,2,1),
 (2,"concurrency","app/services/gis_harness/plan_runtime.py",407,"used = int((recovery.get(loops) or {}).get(REPLAN_LOOP) or 0)","replan budget read before session lock, increment after release - concurrent finalizer exits both pass gate and both increment; replan_remaining from stale used",3,4,1),
 (2,"error-handling","app/services/gis_harness/runtime_repair.py",545,"if batch.committed and any(o.status == applied for o in batch.outcomes):","visibility-restore batch marks ALL requested ids applied when ANY single outcome applied - user-wins-rejected intents recorded as applied, contradicting adjacent comment",3,4,1),
 (2,"gis-correctness","app/services/gis_harness/completion/map_verification.py",95,"return px / n * 360.0 - 180.0","_lng_of does not wrap/clamp - at low zoom derived viewport bbox spans beyond +-180 intersecting every result bbox; F_EXTENT_MISMATCH fail-open exactly where meant to close gap",3,3,1),
 (2,"correctness","app/services/gis_harness/data_qualification.py",509,"c.get(check, ) for c in checks if not c.get(passed))","unknown checks recorded passed=False and listed alongside real failures in user-facing detail - absent evidence mislabeled as violated",3,3,1),
 (2,"deadcode","app/services/gis_harness/recipes.py",459,"if rule.min_samples is not None:","no registered recipe declares min_samples/field_expectations/allowed_distribution_shapes/requires_temporal/min_point_density - five of six ADR-0151 V4 dimensions inert for every recipe",4,4,1),
 (2,"deadcode","app/services/gis_harness/completion/map_verification.py",319,"def verify_final_map(","zero-caller convenience export; pipeline calls collect/aggregate directly",1,1,1),
 (2,"correctness","app/services/gis_harness/fallback_v3.py",131,"has_executable = bool(states & {eligible, transform_required})","all-degraded role set falls to descriptive-only branch while producer defines degraded as executable-with-disclosure - shared vocabulary two incompatible meanings",3,3,1),
 (2,"duplication","app/services/gis_harness/data_qualification.py",98,"def _geometry_category(geometry_types: Sequence[str]) -> str:","re-implements recipes._geometry_category instead of importing (docstring cites same semantics); same reduction in three places",2,3,1),
 (2,"correctness","app/services/gis_harness/workflow_compiler.py",216,"selected = registry.get(recipe_id) if recipe_id else (...)","non-empty unregistered recipe_id -> AttributeError where planner falls back; funnel points include persisted chapter ids (STALE_PLAN scenario)",4,3,1),
 (2,"error-handling","app/services/gis_harness/workflow_compiler.py",512,"dim_states[dim] = not (wc.get(data_blockers) or [])","planner contract-eval failure returns status:error without keys -> completion contract records data/science as satisfied, masking the failure; adjacent comment warns exactly this",4,3,1),
 (2,"correctness","app/services/gis_harness/planner.py",970,"if recipe is None: finalized.status = finalized","finalize_with_profile marks plan finalized with zero eligibility/fallback/contract checks when recipe no longer resolves (stale-plan scenario module itself guards elsewhere)",4,4,1),
 (2,"deadcode","app/services/gis_harness/goal_graph.py",405,"def validate_candidate_graph(","zero callers - docstring claims it arbitrates all LLM-suggested graphs; guarantee unenforced",2,2,1),
 (2,"deadcode","app/services/gis_harness/candidate_planner_v8.py",112,"def plan_candidates_v8(","entire 176-line ADR-0137 capability-candidate planning chain test-only, unwired",2,3,1),
 (2,"deadcode","app/services/gis_harness/trace_store.py",612,"def read_chains_since(session_id: str, after_seq: int)","read_chains_since + iter_session_chains test-only; docstrings named consumer does not exist",2,2,1),
 (2,"deadcode","app/services/gis_harness/planner.py",72,"def resolve_tool_for_capability(","test-only compat shim; production resolves via AlgorithmResolver",1,1,1),
 (2,"deadcode","app/services/gis_harness/product_lineage.py",267,"if src_ref and _live(src_ref) in (expired, failed):","sole production caller never supplies liveness inputs - dead_outputs always [], death-gated branch and dead-ref exclusion can never fire in production",3,3,1),
 (2,"concurrency","app/services/gis_harness/trace_store.py",462,"with _WRITE_LOCK, _FileLock(v6_dir / trace_v6.lock):","one global threading lock serializes all sessions reads+writes; non-POSIX has no inter-process lock",3,4,1),
 (2,"hardcoding","app/services/gis_harness/planner.py",304,"if n < 8:","kriging sample floor 8 hand-mirrored in planner from registry min_features and duplicated across 5+ recipe-pack obligation sites",2,3,1),
 (2,"correctness","app/services/gis_harness/tools.py",220,"dup_id = (dup or {}).get(id) or f{target_id}-copy*","action=duplicate reports fabricated placeholder id with literal * as new component id; real id in res never resolved",2,3,1),
 (2,"deadcode","app/services/gis_harness/resume_verify.py",350,"if raw_ref in rev_map or raw_ref not in ref_map.values():","tautological condition - else branch (LIVE with no verdict entry) unreachable; intended rehydrated-ref path dead",1,2,1),
 (2,"concurrency","app/services/gis_harness/tools.py",333,"cache_key = (str(project_id), str(turn_id))","turn-less contexts collapse all turns to one cache key with no TTL - verified-recipe ordering stale for process lifetime",2,3,1),
 (2,"resource","app/services/gis_harness/recovery_ledger.py",205,"self._cache[session_id] = (mtime, entries)","per-session read cache unbounded over process lifetime on multi-tenant deployments; _mutate only pops mutated session",3,3,1),
 (2,"correctness","app/services/gis_harness/tools.py",966,"elif Point in _primary_geoms or not _primary_geoms:","empty geometry set with missing descriptor marks poi_query AND point_profile done - #1067 guard does not cover missing-profile case; completeness overstated",3,3,1),
 (2,"correctness","app/services/gis_harness/tools.py",927,"planned.bound_ref = primary_ref or ""","binding backfill and artifact lineage attribute every bound layer incl non-primary to primary_ref - provenance wrong when multiple refs feed product",3,4,1),
 (2,"gis-correctness","app/services/gis_harness/completion/validators/semantics.py",38,"if tail.isdigit() and int(tail) in (4326, 4490):","OGC urn form yields non-digit tail CRS84 -> flagged crs_not_wgs84 while short form passes - false-positive CRS warning for legitimate alias",2,2,1),
 (2,"gis-correctness","app/services/gis_harness/workflow_schema.py",363,"TIME_FIELD_HINTS = (time, date, year, month, day, ...","substring matching lets holiday/sunday_count satisfy temporal evidence - temporal obligations cleared by unrelated fields; hints shared with data_qualification",3,3,1),
 (2,"deadcode","app/services/gis_harness/intent_acceptance.py",35,"READY_VERDICTS = (READY, READY_WITH_WARNINGS)","exported constant zero importers; pipeline redefines identical private tuple - drift risk",1,2,1),
 (2,"deadcode","app/services/gis_harness/durable_context.py",44,"REBUILDABLE_KEYS: Tuple[str, ...] = (","zero references anywhere - rebuildable tier exists only as data, never consulted",1,1,1),
 (2,"deadcode","app/services/gis_harness/durable_context.py",72,"def classify_context_key(key: str) -> str:","no production caller - durable/forbidden whitelist gate enforced nowhere at runtime",2,2,1),
 (2,"duplication","app/services/gis_harness/analysis_graph.py",217,"facets = build_facet_completion(","identical build_facet_completion computed twice per graph build (line 89 and 217) on every analysis-graph request",2,2,1),
 (2,"typing","app/services/gis_harness/registry_validation.py",116,"assert model is not None","assert-based None-narrowing at 6 sites in validation code - crashes rather than reports under -O",1,2,1),
 (2,"deadcode","app/services/gis_harness/resume_verify.py",487,"_ = missing_new","set computed then discarded via _ = - dead assignment",1,1,1),
 (2,"deadcode","app/services/gis_harness/workflow_schema.py",450,"elif not req.required:","redundant arm assigning same status as following else; missing_policy=degrade silently ignored for optional roles",1,1,1),
 (2,"hardcoding","app/services/gis_harness/tools.py",1362,"if estimate_json_bytes(chart) > 32 * 1024:","32KB chart threshold magic literal in tool code; D2 budget not surfaced as config",1,2,1),
 (2,"hardcoding","app/services/gis_harness/tools.py",674,"min_points = 10","broad except around settings import silently substitutes hardcoded heatmap minimum duplicating settings default",1,2,1),
 (2,"correctness","app/services/gis_harness/workflow_v4/diff.py",188,"if isinstance(e, dict) and str(e.get(from, )) == removed_id:","_survivor compares port-suffixed endpoints against bare node ids - never matches, always empty target no-op contradicting no-op contract; test-only callers today",2,3,1),
 (2,"error-handling","app/services/gis_harness/components.py",869,"if isinstance(v, float) and not math.isfinite(v):","non-finite scores silently converted to None before validator runs - validators finite-score branch unreachable through factory path; NaN published as null",2,2,1),
 (2,"concurrency","app/services/gis_harness/product_templates.py",314,"_registry = ProductTemplateRegistry()","lazy singleton assigns global before load_builtins - concurrent first caller can observe empty registry",2,2,1),
 (2,"deadcode","app/services/gis_harness/resume_anchor.py",451,"owner_token: Optional[str] = None","owner_token initialized None and returned without assignment - API response always carries owner_token null (contract-frozen)",1,1,1),
 (2,"correctness","app/services/gis_harness/components.py",426,"if not isinstance(value, (int, float, str)) or isinstance(value, bool):","validate_stats_payload no length bound on string value while siblings capped - multi-MB string reaches MapSpec/export payload",2,2,1),
 (2,"deadcode","app/services/gis_harness/runtime_bridge.py",55,"def capability_node_id(capability: str) -> str:","capability_node_id/role_node_id/artifact_lineage/node_lineage exported zero callers incl tests (W3 consumption API unwired)",2,3,1),
 (2,"deadcode","app/services/gis_harness/components.py",163,"def from_legacy(cls, data: Dict[str, Any]) -> CartographyComponent:","from_legacy classmethod test-only",1,1,1),
 (2,"correctness","app/services/gis_harness/runtime_bridge.py",406,"if len(artifact_index) >= 96:","artifact index silently stops admitting refs past 96 with no truncation/disclosure flag unlike sibling bounded faces",2,2,1),
 (2,"error-handling","app/services/gis_harness/components.py",190,"except Exception:  pass  # catalog unavailable","registry lookup failures swallowed with no logging - variant coercion and legend derivation silently disabled; invalid variants accepted",3,3,1),
 (2,"hardcoding","app/services/gis_harness/qualification_v8.py",269,"if modelops.seeds not in owner_key and global-builtin not in owner_key:","builtin-scope allowlist two hardcoded strings duplicated at :277 inside gating logic",1,2,1),
 (2,"hardcoding","app/services/gis_harness/continuation.py",116,"if failure and ledger_attempts >= 3:","failure budget 3 hardcoded instead of deriving from failure_taxonomy REMEDIATION_POLICY per-class max_attempts",1,2,1),
 (2,"duplication","app/services/gis_harness/completion/contracts.py",262,"disclosed_warning_codes = {str(w.get(code)) for w in mw if w.get(code)}","verbatim re-computation of identical set comprehension bound at :187 - two names one fact",1,1,1),
 (2,"correctness","app/services/gis_harness/workflow_v4/acquisition.py",182,"status = str(getattr(r, status, ) or (r.get(status) if isinstance(r, dict) else unresolved))","dict fallback: None or None -> str(None) = literal None string defeating default and role skip - every channel infeasible for dict roles without status; latent (dict branch unexercised)",2,3,1),
 (2,"correctness","app/services/gis_harness/completion/validators/layout.py",10,"第一版布局冲突检测：floating 矩形重叠 + zone 容量/exclusive 超限","docstring declares zone capacity/exclusive detection but only floating-overlap implemented - pipeline gets zero zone findings",2,2,1),
 (2,"correctness","app/services/gis_harness/qualification_v8.py",243,"f[{lo}, {hi}] m/px,","res==0 with undeclared resolution range renders [None, None] m/px in user-facing degraded disclosure",1,2,1),
 (2,"deadcode","app/services/gis_harness/runtime_bridge.py",238,"typed_by_id: Dict[str, Dict[str, Any]] = {}","local dict built in first DAG pass never read afterwards - dead work per invocation",1,1,1),
 (2,"deadcode","app/services/gis_harness/visual_evaluator.py",67,"def get_visual_evaluator() -> Optional[Callable[..., Any]]:","all three W9 seam exports zero production callers (module admits unwired roadmap item)",2,2,1),
 (2,"deadcode","app/services/gis_harness/delegation.py",301,"async def delegate_cartography_qa(","documented production driver zero production callers - env-gated QA delegation never wired",2,2,1),
 (2,"deadcode","app/services/gis_harness/runtime_state_machine.py",607,"def runtime_phase_of(chapter: Optional[Dict[str, Any]]) -> str:","exported read-only phase API zero production callers despite docstring consumption claim",1,1,1),
 (2,"deadcode","app/services/gis_harness/plan_candidates.py",203,"def _output_quality(recipe: Any, ontology_scores: Dict[str, float]) -> float:","ontology_scores parameter never referenced in body - caller computes and passes scores that are discarded",1,1,1),
 (2,"deadcode","app/services/gis_harness/product_action.py",76,"def advise_next_product_action(","chapter parameter never used in body - signature implies chapter-dependent advice that does not exist",1,1,1),
 (2,"hardcoding","app/services/gis_harness/runtime_state_machine.py",251,"return await runtime re-observation in summary","phase derivation substring-matches an English f-string produced in another module - cross-module contract lives in two free-text literals",2,2,1),
 (2,"concurrency","app/services/gis_harness/delegation.py",318,"for rec in _parse_records(stored):","idempotency check reads ledger outside session lock then persists later - concurrent calls both pass (latent, no production caller)",1,2,1),
 (2,"concurrency","app/services/gis_harness/runtime_state_machine.py",771,"render_seq = observation_sequence(await load_render_observation(...))","render observation sequence computed before lock but written inside - observation during wait recorded under stale seq",2,3,1),
 (2,"correctness","app/services/gis_harness/workflow_instance.py",611,"new_state.transitions = _merge_transitions(","docstring claims ring-merge of transitions but _merge_transitions only reads stored stages and returns current revision diffs - audit trail drops all history on every content change",3,4,1),
 (2,"correctness","app/services/gis_harness/recipe_packs/exposure.py",32,"fallbacks=[RecipeFallback(when=population missing, reason_code=DATA_ROLE_MISSING_POPULATION,...","element fallback declares reason code no producer can emit (role renamed to denominator) - declared use mapping can never trigger",1,1,1),
 (2,"deadcode","app/services/gis_harness/workflow_v4/recompute.py",137,"if src not in node_set and . in src:","src/dst normalization unconditionally overwritten by _node_id_of before use - dead stores duplicating engine logic",1,1,1),
 (2,"deadcode","app/services/gis_harness/workflow_instance.py",848,"if sci.get(divergent) and sci.get(direction) == worsened:","branch unreachable - _derive_science only ever sets unblocked or equal",1,1,1),
 (2,"deadcode","app/services/gis_harness/workflow_instance.py",113,"BLOCK_DATA = BLOCKED_BY_DATA","BLOCK_* vocabulary and WorkflowEventKind exported with zero consumers",1,2,1),
 (2,"hardcoding","app/services/gis_harness/workflow_v4/methodology.py",532,"keywords_en=(slope, aspect,  dem, dem , watershed...","space-padded dem keywords can never match CJK-embedded dem - standalone-DEM Chinese queries never route via professional keywords",2,2,1),
]

def score(sev, blast, lines, risk):
    w = {0: 9, 1: 3, 2: 1}[sev]
    cost = lines / 50 + 1
    return round(w * blast / (cost * risk), 2)

def fp(f, l, e):
    return hashlib.md5(f"{f}:{l}:{e}".encode("utf-8")).hexdigest()[:8]

with open("review/qa-loop/round-2.pool.csv", "w", newline="", encoding="utf-8") as fh:
    w = csv.writer(fh)
    w.writerow(["id","fingerprint","severity","category","file","line","excerpt","issue","blast_radius","fix_cost_lines","risk","score","status"])
    for i, (sev, cat, f, ln, ex, iss, bl, cl, rk) in enumerate(rows, 1):
        status = "fixed" if (sev == 1 and ln in (149, 295, 615)) else "open"
        w.writerow([f"R2Q{i:03d}", fp(f, ln, ex), f"P{sev}", cat, f, ln, ex, iss, bl, cl, rk, score(sev, bl, cl, rk), status])

cnt = {0: 0, 1: 0, 2: 0}
for r in rows:
    cnt[r[0]] += 1
print("round-2 pool rows:", len(rows), "P0:", cnt[0], "P1:", cnt[1], "P2:", cnt[2])
