/**
 * AUTO-GENERATED by app/lib/cartography/ts_projection.py —— DO NOT EDIT.
 *
 * MapSpec 契约的权威 schema 在 app/lib/cartography/mapspec_schema.py
 * （Pydantic 模型族）；本文件是其 TypeScript 投影。修改契约请改 schema
 * 后运行 `python -m app.lib.cartography.ts_projection` 再生成。
 *
 * V6（ADR-0120 W3）：消除手维护平行 schema（原 types.ts 手写镜像）。
 */

export type StyleMethodType = "constant" | "interpolate" | "step" | "match" | "field";

export interface ConstantStyleMethod {
  method: "constant";
  value: string | number | boolean;
}

export interface InterpolateStyleMethod {
  method: "interpolate";
  field: string;
  stops: Array<[number, string | number]>;
}

export interface StepStyleMethod {
  method: "step";
  field: string;
  stops: Array<[number, string | number]>;
  default?: string | number;
}

export interface MatchStyleMethod {
  method: "match";
  field: string;
  cases: Array<[string | number, string | number]>;
  default: string | number;
}

export interface FieldStyleMethod {
  method: "field";
  field: string;
}

export type StyleMethod =
  | ConstantStyleMethod
  | InterpolateStyleMethod
  | StepStyleMethod
  | MatchStyleMethod
  | FieldStyleMethod
  | string
  | number
  | boolean;

export interface MapSpecLayerPaint {
  color?: StyleMethod;
  radius?: StyleMethod;
  width?: StyleMethod;
  opacity?: StyleMethod;
  strokeColor?: StyleMethod;
  strokeWidth?: StyleMethod;
  [key: string]: StyleMethod | undefined;
}

export interface MapSpecLayerLayout {
  visibility?: "visible" | "none";
  labelField?: string;
  labelSize?: number | StyleMethod;
  labelColor?: string | StyleMethod;
  [key: string]: any;
}

export interface MapSpec {
  version: string;
  view?: MapSpecView;
  sources: Record<string, DataFabricMapSpecSource | GeoJSONMapSpecSource | RasterMapSpecSource | VectorMapSpecSource>;
  layers: MapSpecLayer[];
  layout?: MapSpecLayoutConfig;
  thresholds?: MapThresholds;
}

export interface MapSpecView {
  center?: [number, number];
  zoom?: number;
  pitch?: number;
  bearing?: number;
}

export type MapSpecSource =
    | GeoJSONMapSpecSource
  | VectorMapSpecSource
  | RasterMapSpecSource
  | DataFabricMapSpecSource;

export interface GeoJSONMapSpecSource {
  type: "geojson";
  dataPath?: string;
  url?: string;
  inlineData?: any;
  cluster?: ClusterSourceConfig;
  content_revision?: number;
}

export interface VectorMapSpecSource {
  type: "vector";
  tiles: string[];
  minzoom?: number;
  maxzoom?: number;
}

export interface RasterMapSpecSource {
  type: "raster";
  imageRef: string;
  bounds: [number, number, number, number];
  imageSize?: [number, number];
}

export interface DataFabricMapSpecSource {
  type: "data_fabric" | "wms" | "wmts" | "pmtiles";
  catalog_item_id?: string;
  lazy?: boolean;
  ref_id?: string;
  url?: string;
  dataPath?: string;
  inlineData?: unknown;
  profile?: Record<string, unknown>;
  profile_fingerprint?: string;
  data_fingerprint?: string;
}

export interface ClusterSourceConfig {
  radius?: number;
  maxzoom?: number;
}

export interface MapSpecLayer {
  id: string;
  source: string;
  type: "circle" | "line" | "fill" | "symbol" | "heatmap" | "raster" | "fill-extrusion";
  paint?: MapSpecLayerPaint;
  layout?: MapSpecLayerLayout;
  label?: MapSpecLayerLabel;
  filter?: unknown[];
  sourceLayer?: string;
  cluster?: ClusterSourceConfig;
  legend_spec?: Record<string, unknown>;
  visible?: boolean;
}

export interface MapSpecLayerLabel {
  field: string;
  size?: number | StyleMethod;
  color?: string | StyleMethod;
  haloColor?: string;
  haloWidth?: number;
}

export interface MapSpecLegendConfig {
  title?: string;
  position?: "top-right" | "top-left" | "bottom-right" | "bottom-left";
  visible?: boolean;
}

export interface MapSpecControlConfig {
  type: "navigation" | "scale" | "fullscreen";
  position?: "top-right" | "top-left" | "bottom-right" | "bottom-left";
}

export interface ComponentPlacement {
  mode: "anchor" | "floating";
  anchor?: string;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  zIndex?: number;
  collapsed?: boolean;
}

export interface MapSpecComponent {
  id: string;
  type: "basemap" | "legend" | "continuous_colorbar" | "categorical_legend" | "north_arrow" | "scale_bar" | "title" | "subtitle" | "annotation" | "graticule" | "map_border" | "attribution" | "statistics_panel" | "chart_panel" | "table_panel" | "export_layout" | "inset_map" | "methodology_note" | "uncertainty_panel" | "decision_panel";
  enabled?: boolean;
  position?: "top-left" | "top-center" | "top-right" | "bottom-left" | "bottom-center" | "bottom-right" | "none";
  priority?: number;
  style?: Record<string, unknown>;
  options?: Record<string, unknown>;
  compatibility?: Record<string, unknown>;
  variant?: string;
  placement?: ComponentPlacement;
}

export interface LayerOverride {
  visible?: boolean;
  opacity?: number;
}

export interface FramePageSize {
  width: number;
  height: number;
}

export interface MapSpecFrame {
  id?: string;
  title?: string;
  view?: MapSpecView;
  extent?: [number, number, number, number];
  layerOverrides?: Record<string, LayerOverride>;
  pageSize?: FramePageSize;
  enabled?: boolean;
}

export interface MapLabelConfig {
  collision?: "deterministic";
  maxLabels?: number;
}

export interface MapSpecLayoutConfig {
  legend?: MapSpecLegendConfig;
  controls?: MapSpecControlConfig[];
  margins?: Record<string, number>;
  components?: MapSpecComponent[];
  frames?: MapSpecFrame[];
  labels?: MapLabelConfig;
}

export interface MapThresholds {
  maxFeatures?: number;
  timeoutMs?: number;
}
