"""
HarnessEvaluator - 5-Dimensional Evaluation Metric Calculator & Quality Gate
"""
import logging
from typing import Any, Dict

logger = logging.getLogger(__name__)

# Default Acceptance Thresholds
DEFAULT_THRESHOLDS = {
    "ToolChoiceAccuracy": 90.0,
    "MapSpecValidity": 95.0,
    "CursorResolutionRate": 100.0,
    "StepEfficiency": 80.0,
    "ErrorRecoveryRate": 80.0,
}


class HarnessEvaluator:
    """Evaluates telemetry from PiAgentHarness against 5 quality gate thresholds."""

    def __init__(self, thresholds: Dict[str, float] | None = None):
        self.thresholds = {**DEFAULT_THRESHOLDS, **(thresholds or {})}

    def evaluate_session(
        self,
        harness_metrics: Dict[str, float]
    ) -> Dict[str, Any]:
        """
        Evaluate harness metrics against quality gate thresholds.

        :param harness_metrics: Dictionary of computed metric scores.
        :return: Evaluation result containing metrics, thresholds, checks, and overall pass status.
        """
        checks: Dict[str, Dict[str, Any]] = {}
        all_passed = True

        for metric_name, target_threshold in self.thresholds.items():
            actual_score = harness_metrics.get(metric_name, 0.0)
            passed = actual_score >= target_threshold
            if not passed:
                all_passed = False

            checks[metric_name] = {
                "score": actual_score,
                "target": target_threshold,
                "passed": passed,
            }

        return {
            "overall_passed": all_passed,
            "metrics": harness_metrics,
            "thresholds": self.thresholds,
            "checks": checks,
        }

    def generate_markdown_report(
        self,
        session_id: str,
        evaluation_result: Dict[str, Any]
    ) -> str:
        """Generate a formatted Markdown evaluation report."""
        overall_status = "✅ PASSED" if evaluation_result["overall_passed"] else "❌ FAILED"
        lines = [
            f"# Pi GIS Agent Evaluation Report: {session_id}",
            "",
            f"**Overall Status**: {overall_status}",
            "",
            "## 5-Dimensional Quality Gate Metrics",
            "",
            "| Metric Name | Score (%) | Target (%) | Status |",
            "|---|---|---|---|",
        ]

        for name, chk in evaluation_result["checks"].items():
            status_icon = "🟢 PASS" if chk["passed"] else "🔴 FAIL"
            lines.append(
                f"| {name} | {chk['score']}% | {chk['target']}% | {status_icon} |"
            )

        lines.extend([
            "",
            "---",
            "*Report generated by Pi GIS Agent Harness Evaluation Suite.*",
        ])

        return "\n".join(lines)
