import { useEffect } from 'react';
import { useHudStore } from '@/lib/store/useHudStore';

export function ExportLayoutTab() {
  const exportSettings = useHudStore((s) => s.exportSettings);
  const updateExportSettings = useHudStore((s) => s.updateExportSettings);

  // Helper to update specific fields
  const handleChange = (key: keyof typeof exportSettings, value: any) => {
    updateExportSettings({ [key]: value });
  };

  // Auto-enable export mode when tab is opened
  useEffect(() => {
    updateExportSettings({ isExportMode: true });
    return () => {
      updateExportSettings({ isExportMode: false });
    };
  }, [updateExportSettings]);

  return (
    <div className="flex flex-col h-full overflow-y-auto bg-slate-50">
      <div className="p-4 border-b bg-white">
        <h2 className="font-semibold text-slate-800">专题制图排版</h2>
        <p className="text-xs text-slate-500 mt-1">配置地图元素与输出格式</p>
      </div>

      <div className="p-4 space-y-6 flex-1">
        {/* Texts */}
        <div className="space-y-3">
          <label className="block text-sm font-medium text-slate-700">主标题</label>
          <input 
            type="text" 
            value={exportSettings.title} 
            onChange={(e) => handleChange('title', e.target.value)} 
            placeholder="如：成都市高校分布图" 
            className="w-full text-sm border rounded px-3 py-2" 
          />
          
          <label className="block text-sm font-medium text-slate-700 mt-2">副标题</label>
          <input 
            type="text" 
            value={exportSettings.subtitle} 
            onChange={(e) => handleChange('subtitle', e.target.value)} 
            placeholder="如：数据来源: OSM, 制图日期: 2026" 
            className="w-full text-sm border rounded px-3 py-2" 
          />
        </div>

        {/* Elements */}
        <div className="space-y-2">
          <label className="block text-sm font-medium text-slate-700">地图元素</label>
          <div className="flex items-center gap-2">
            <input 
              id="checkbox-compass"
              type="checkbox" 
              checked={exportSettings.showCompass} 
              onChange={(e) => handleChange('showCompass', e.target.checked)} 
            /> 
            <label htmlFor="checkbox-compass" className="text-sm">指北针</label>
          </div>
          <div className="flex items-center gap-2">
            <input 
              id="checkbox-scale"
              type="checkbox" 
              checked={exportSettings.showScale} 
              onChange={(e) => handleChange('showScale', e.target.checked)} 
            /> 
            <label htmlFor="checkbox-scale" className="text-sm">比例尺</label>
          </div>
          <div className="flex items-center gap-2">
            <input 
              id="checkbox-legend"
              type="checkbox" 
              checked={exportSettings.showLegend} 
              onChange={(e) => handleChange('showLegend', e.target.checked)} 
            /> 
            <label htmlFor="checkbox-legend" className="text-sm">图例</label>
          </div>
          <div className="flex items-center gap-2">
            <input 
              id="checkbox-watermark"
              type="checkbox" 
              checked={exportSettings.showWatermark} 
              onChange={(e) => handleChange('showWatermark', e.target.checked)} 
            /> 
            <label htmlFor="checkbox-watermark" className="text-sm">水印 (Generated by WebGIS AI)</label>
          </div>
        </div>

        {/* Paper & Quality */}
        <div className="space-y-3 border-t pt-4">
          <label className="block text-sm font-medium text-slate-700">输出设置</label>
          <select 
            value={exportSettings.format} 
            onChange={(e) => handleChange('format', e.target.value)} 
            className="w-full text-sm border rounded px-3 py-2"
          >
            <option value="png">PNG 图片</option>
            <option value="pdf">PDF 文档</option>
          </select>
          <select 
            value={exportSettings.paperSize} 
            onChange={(e) => handleChange('paperSize', e.target.value)} 
            className="w-full text-sm border rounded px-3 py-2"
          >
            <option value="screen">当前屏幕比例 (Screen)</option>
            <option value="A4">A4 纸张尺寸</option>
          </select>
          <select 
            value={exportSettings.orientation} 
            onChange={(e) => handleChange('orientation', e.target.value)} 
            disabled={exportSettings.paperSize === 'screen'} 
            className="w-full text-sm border rounded px-3 py-2 disabled:opacity-50"
          >
            <option value="landscape">横向 (Landscape)</option>
            <option value="portrait">纵向 (Portrait)</option>
          </select>
          <select 
            value={exportSettings.dpi} 
            onChange={(e) => handleChange('dpi', Number(e.target.value))} 
            className="w-full text-sm border rounded px-3 py-2"
          >
            <option value={96}>标准清晰度 (96 DPI)</option>
            <option value={150}>高清晰度 (150 DPI)</option>
            {exportSettings.paperSize === 'screen' && <option value={300}>超清排版 (300 DPI)</option>}
          </select>
        </div>
      </div>
      
      <div className="p-4 bg-white border-t">
        <button 
          className="w-full bg-blue-600 text-white font-medium py-2 rounded shadow hover:bg-blue-700 transition" 
          onClick={() => {
            // We will wire this up later to useMapAction
            alert("Export pending implementation");
          }}
        >
          导出 {exportSettings.format.toUpperCase()}
        </button>
      </div>
    </div>
  );
}

export default ExportLayoutTab;